CMaNGOS_TBC: areatrigger_scripts.cpp File Reference
areatrigger_scripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/scripts/kalimdor/world_kalimdor.h"
#include "world_map_scripts.h"
Data Structures
struct AncientSpawn
struct Location
Enumerations
enum { GO_COILFANG_WATERFALL = 184212 }
enum { SPELL_TELE_A_TO = 37389 , QUEST_GAINING_ACCESS_A = 10589 , SPELL_TELE_H_TO = 37387 , QUEST_GAINING_ACCESS_H = 10604 }
enum { QUEST_MANOR_RAVENHOLDT = 6681 , NPC_RAVENHOLDT = 13936 }
enum { QUEST_SCENT_OF_LARKORWI = 4291 , NPC_LARKORWI_MATE = 9683 }
enum {
QUEST_ANCIENT_LEAF = 7632 , NPC_VARTRUS = 14524 , NPC_STOMA = 14525 , NPC_HASTAT = 14526 ,
MAX_ANCIENTS = 3
}
enum { QUEST_SPECIAL_DELIVERY_TO_SHATTRATH = 10280 }
enum {
QUEST_RESUPPLYING_THE_EXCAVATION = 273 , NPC_SAEAN = 1380 , NPC_MIRAN = 1379 , NPC_HULDAR = 2057 ,
NPC_DARK_IRON_AMBUSHER = 1981 , FACTION_HOSTILE = 14 , SAY_MIRAN_AMBUSH = -1010029
}
enum { SPELL_A52_NEURALYZER = 34400 }
enum { NPC_TWILIGHT_CORRUPTER = 15625 , ITEM_FRAGMENT_NIGHTMARE = 21149 , QUEST_NIGHTMARE_CORRUPTION = 8735 , SAY_TWILIGHT_CORRUPTER_SPAWN = -1000411 }
enum { GO_WONDERVOLT_TRAP = 180797 }
enum { NPC_JUSTINE_DEMALIER = 12481 , QUEST_THE_FIRST_AND_THE_LAST = 6182 }
Functions
bool AreaTrigger_at_childrens_week_spot (Player *pPlayer, AreaTriggerEntry const *pAt)
bool AreaTrigger_at_coilfang_waterfall (Player *pPlayer, AreaTriggerEntry const *)
bool AreaTrigger_at_legion_teleporter (Player *pPlayer, AreaTriggerEntry const *)
bool AreaTrigger_at_ravenholdt (Player *pPlayer, AreaTriggerEntry const *)
bool AreaTrigger_at_scent_larkorwi (Player *pPlayer, AreaTriggerEntry const *pAt)
bool AreaTrigger_at_murkdeep (Player *pPlayer, AreaTriggerEntry const *)
bool AreaTrigger_at_ancient_leaf (Player *pPlayer, AreaTriggerEntry const *)
bool AreaTrigger_at_haramad_teleport (Player *pPlayer, AreaTriggerEntry const *)
bool AreaTrigger_at_huldar_miran (Player *pPlayer, AreaTriggerEntry const *)
bool AreaTrigger_at_area_52 (Player *player, AreaTriggerEntry const *at)
bool AreaTrigger_at_twilight_grove (Player *player, AreaTriggerEntry const *)
bool AreaTrigger_at_hive_tower (Player *player, AreaTriggerEntry const *)
bool AreaTrigger_at_wondervolt (Player *player, AreaTriggerEntry const *)
bool AreaTrigger_at_stormwind_recruiter (Player *player, AreaTriggerEntry const *)
void AddSC_areatrigger_scripts ()
Variables
static uint32 TriggerOrphanSpell [6][3]
static const AncientSpawn afSpawnLocations [MAX_ANCIENTS]
static const Location m_miranAmbushSpawns []
static const Location m_twilightCorrupterSpawn = { -10326.3f, -487.423f, 50.1127f, 5.73692f }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
GO_COILFANG_WATERFALL
Definition at line 73 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_TELE_A_TO
QUEST_GAINING_ACCESS_A
SPELL_TELE_H_TO
QUEST_GAINING_ACCESS_H
Definition at line 92 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_MANOR_RAVENHOLDT
NPC_RAVENHOLDT
Definition at line 125 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_SCENT_OF_LARKORWI
NPC_LARKORWI_MATE
Definition at line 143 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_ANCIENT_LEAF
NPC_VARTRUS
NPC_STOMA
NPC_HASTAT
MAX_ANCIENTS
Definition at line 205 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_SPECIAL_DELIVERY_TO_SHATTRATH
Definition at line 252 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_RESUPPLYING_THE_EXCAVATION
NPC_SAEAN
NPC_MIRAN
NPC_HULDAR
NPC_DARK_IRON_AMBUSHER
FACTION_HOSTILE
SAY_MIRAN_AMBUSH
Definition at line 270 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_A52_NEURALYZER
Definition at line 350 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_TWILIGHT_CORRUPTER
ITEM_FRAGMENT_NIGHTMARE
QUEST_NIGHTMARE_CORRUPTION
SAY_TWILIGHT_CORRUPTER_SPAWN
Definition at line 373 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
GO_WONDERVOLT_TRAP
Definition at line 439 of file areatrigger_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_JUSTINE_DEMALIER
QUEST_THE_FIRST_AND_THE_LAST
Definition at line 472 of file areatrigger_scripts.cpp.
Function Documentation
AddSC_areatrigger_scripts()
void AddSC_areatrigger_scripts ()
Definition at line 490 of file areatrigger_scripts.cpp.
References AreaTrigger_at_ancient_leaf(), AreaTrigger_at_area_52(), AreaTrigger_at_childrens_week_spot(), AreaTrigger_at_coilfang_waterfall(), AreaTrigger_at_haramad_teleport(), AreaTrigger_at_hive_tower(), AreaTrigger_at_huldar_miran(), AreaTrigger_at_legion_teleporter(), AreaTrigger_at_murkdeep(), AreaTrigger_at_ravenholdt(), AreaTrigger_at_scent_larkorwi(), AreaTrigger_at_stormwind_recruiter(), AreaTrigger_at_twilight_grove(), AreaTrigger_at_wondervolt(), Script::Name, Script::pAreaTrigger, and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_ancient_leaf()
bool AreaTrigger_at_ancient_leaf (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 229 of file areatrigger_scripts.cpp.
References afSpawnLocations, GetClosestCreatureWithEntry(), Player::GetQuestStatus(), IN_MILLISECONDS, Unit::IsAlive(), Player::IsGameMaster(), MINUTE, NPC_HASTAT, NPC_STOMA, NPC_VARTRUS, QUEST_ANCIENT_LEAF, QUEST_STATUS_COMPLETE, WorldObject::SummonCreature(), and TEMPSPAWN_TIMED_DESPAWN.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_area_52()
bool AreaTrigger_at_area_52 (Player * player, AreaTriggerEntry const * at)
Definition at line 355 of file areatrigger_scripts.cpp.
References Unit::CastSpell(), Unit::HasAura(), SQLStorage::LookupEntry(), SpellCastTargets::setDestination(), SpellCastTargets::setUnitTarget(), SPELL_A52_NEURALYZER, sSpellTemplate, TRIGGERED_OLD_TRIGGERED, AreaTriggerEntry::x, AreaTriggerEntry::y, and AreaTriggerEntry::z.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_childrens_week_spot()
bool AreaTrigger_at_childrens_week_spot (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 55 of file areatrigger_scripts.cpp.
References Unit::CastSpell(), Object::GetEntry(), Unit::GetMiniPet(), AreaTriggerEntry::id, TRIGGERED_OLD_TRIGGERED, and TriggerOrphanSpell.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_coilfang_waterfall()
bool AreaTrigger_at_coilfang_waterfall (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 78 of file areatrigger_scripts.cpp.
References GetClosestGameObjectWithEntry(), GO_COILFANG_WATERFALL, and GO_READY.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_haramad_teleport()
bool AreaTrigger_at_haramad_teleport (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 257 of file areatrigger_scripts.cpp.
References Player::IsCurrentQuest(), QUEST_SPECIAL_DELIVERY_TO_SHATTRATH, and Player::TeleportTo().
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_hive_tower()
bool AreaTrigger_at_hive_tower (Player * player, AreaTriggerEntry const *)
Definition at line 414 of file areatrigger_scripts.cpp.
References aSpawnLocations, InstanceData::GetData(), WorldObject::GetInstanceData(), IN_MILLISECONDS, IN_PROGRESS, Unit::IsAlive(), Player::IsGameMaster(), MINUTE, NOT_STARTED, NPC_HIVE_ASHI_DRONES, POS_IDX_HIVE_DRONES_START, POS_IDX_HIVE_DRONES_STOP, InstanceData::SetData(), WorldObject::SummonCreature(), TEMPSPAWN_TIMED_OR_DEAD_DESPAWN, and TYPE_HIVE.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_huldar_miran()
bool AreaTrigger_at_huldar_miran (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 296 of file areatrigger_scripts.cpp.
References Player::CompleteQuest(), DoScriptText(), FACTION_HOSTILE, GetClosestCreatureWithEntry(), WorldObject::GetInstanceData(), Player::GetQuestStatus(), Unit::IsAlive(), Player::IsGameMaster(), Unit::IsInCombat(), m_miranAmbushSpawns, NPC_DARK_IRON_AMBUSHER, NPC_HULDAR, NPC_MIRAN, NPC_SAEAN, QUEST_RESUPPLYING_THE_EXCAVATION, QUEST_STATUS_COMPLETE, QUEST_STATUS_NONE, SAY_MIRAN_AMBUSH, Player::SendQuestCompleteEvent(), Creature::SetFactionTemporary(), WorldObject::SummonCreature(), TEMPFACTION_RESTORE_RESPAWN, and TEMPSPAWN_CORPSE_TIMED_DESPAWN.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_legion_teleporter()
bool AreaTrigger_at_legion_teleporter (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 101 of file areatrigger_scripts.cpp.
References ALLIANCE, Unit::CastSpell(), Player::GetQuestRewardStatus(), Player::GetTeam(), HORDE, Unit::IsAlive(), Unit::IsInCombat(), QUEST_GAINING_ACCESS_A, QUEST_GAINING_ACCESS_H, SPELL_TELE_A_TO, SPELL_TELE_H_TO, and TRIGGERED_NONE.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_murkdeep()
bool AreaTrigger_at_murkdeep (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 164 of file areatrigger_scripts.cpp.
References aSpawnLocations, GetClosestCreatureWithEntry(), WorldObject::GetInstanceData(), Player::GetQuestStatus(), WorldObject::GetRandomPoint(), ScriptedInstance::GetSingleCreatureFromStorage(), Unit::IsAlive(), Player::IsGameMaster(), NPC_GREYMIST_COASTRUNNNER, NPC_MURKDEEP, POS_IDX_MURKDEEP_MOVE, POS_IDX_MURKDEEP_SPAWN, QUEST_STATUS_INCOMPLETE, QUEST_WANTED_MURKDEEP, WorldObject::SummonCreature(), and TEMPSPAWN_DEAD_DESPAWN.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_ravenholdt()
bool AreaTrigger_at_ravenholdt (Player * pPlayer, AreaTriggerEntry const *)
Definition at line 131 of file areatrigger_scripts.cpp.
References Player::GetQuestStatus(), Player::KilledMonsterCredit(), NPC_RAVENHOLDT, QUEST_MANOR_RAVENHOLDT, and QUEST_STATUS_INCOMPLETE.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_scent_larkorwi()
bool AreaTrigger_at_scent_larkorwi (Player * pPlayer, AreaTriggerEntry const * pAt)
Definition at line 149 of file areatrigger_scripts.cpp.
References GetClosestCreatureWithEntry(), Player::GetQuestStatus(), IN_MILLISECONDS, Unit::IsAlive(), Player::IsGameMaster(), MINUTE, NPC_LARKORWI_MATE, QUEST_SCENT_OF_LARKORWI, QUEST_STATUS_INCOMPLETE, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_OOC_DESPAWN, AreaTriggerEntry::x, AreaTriggerEntry::y, and AreaTriggerEntry::z.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_stormwind_recruiter()
bool AreaTrigger_at_stormwind_recruiter (Player * player, AreaTriggerEntry const *)
Definition at line 478 of file areatrigger_scripts.cpp.
References AI_EVENT_CUSTOM_EVENTAI_A, ALLIANCE, GetClosestCreatureWithEntry(), Player::GetQuestRewardStatus(), Player::GetTeam(), Player::IsGameMaster(), NPC_JUSTINE_DEMALIER, and QUEST_THE_FIRST_AND_THE_LAST.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_twilight_grove()
bool AreaTrigger_at_twilight_grove (Player * player, AreaTriggerEntry const *)
Definition at line 383 of file areatrigger_scripts.cpp.
References DoScriptText(), GetClosestCreatureWithEntry(), WorldObject::GetInstanceData(), Player::GetQuestStatus(), Player::HasItemCount(), IN_MILLISECONDS, Unit::IsAlive(), Player::IsGameMaster(), ITEM_FRAGMENT_NIGHTMARE, Location::m_fO, Location::m_fX, Location::m_fY, Location::m_fZ, m_twilightCorrupterSpawn, MINUTE, NPC_TWILIGHT_CORRUPTER, QUEST_NIGHTMARE_CORRUPTION, QUEST_STATUS_COMPLETE, QUEST_STATUS_NONE, SAY_TWILIGHT_CORRUPTER_SPAWN, WorldObject::SummonCreature(), and TEMPSPAWN_TIMED_OOC_DESPAWN.
Referenced by AddSC_areatrigger_scripts().
AreaTrigger_at_wondervolt()
bool AreaTrigger_at_wondervolt (Player * player, AreaTriggerEntry const *)
Definition at line 444 of file areatrigger_scripts.cpp.
References EFFECT_INDEX_0, GetClosestGameObjectWithEntry(), GO_WONDERVOLT_TRAP, Unit::HasAura(), and Player::IsGameMaster().
Referenced by AddSC_areatrigger_scripts().
Variable Documentation
afSpawnLocations
const AncientSpawn afSpawnLocations[MAX_ANCIENTS] static
Initial value:
=
{
    { NPC_VARTRUS, 6204.051758f, -1172.575684f, 370.079224f, 0.86052f },
    { NPC_STOMA,   6246.953613f, -1155.985718f, 366.182953f, 2.90269f },
    { NPC_HASTAT,  6193.449219f, -1137.834106f, 366.260529f, 5.77332f },
}
Definition at line 222 of file areatrigger_scripts.cpp.
Referenced by AreaTrigger_at_ancient_leaf().
m_miranAmbushSpawns
const Location m_miranAmbushSpawns[] static
Initial value:
=
{
    { -5760.73f, -3437.71f, 305.54f, 2.41f },
    { -5759.85f, -3441.29f, 305.57f, 2.24f },
    { -5757.75f, -3437.61f, 304.32f, 2.56f },
}
Definition at line 289 of file areatrigger_scripts.cpp.
Referenced by AreaTrigger_at_huldar_miran().
m_twilightCorrupterSpawn
const Location m_twilightCorrupterSpawn = { -10326.3f, -487.423f, 50.1127f, 5.73692f } static
Definition at line 381 of file areatrigger_scripts.cpp.
Referenced by AreaTrigger_at_twilight_grove().
TriggerOrphanSpell
uint32 TriggerOrphanSpell[6][3] static
Initial value:
=
{
    {3546, 14305, 65056},
    {3547, 14444, 65059},
    {3548, 14305, 65055},
    {3549, 14444, 65058},
    {3550, 14444, 65057},
    {3552, 14305, 65054}
}
Definition at line 45 of file areatrigger_scripts.cpp.
Referenced by AreaTrigger_at_childrens_week_spot().