CMaNGOS_TBC: boss_gothik.cpp File Reference
boss_gothik.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "naxxramas.h"
Data Structures
struct boss_gothikAI
struct SummonUnrelenting
struct CheckGothikSide
struct GothikSideAssault
Enumerations
enum {
SAY_SPEECH_1 = -1533040 , SAY_SPEECH_2 = -1533140 , SAY_SPEECH_3 = -1533141 , SAY_SPEECH_4 = -1533142 ,
SAY_KILL = -1533041 , SAY_DEATH = -1533042 , SAY_TELEPORT = -1533043 , PHASE_SPEECH = 0 ,
PHASE_BALCONY = 1 , PHASE_TELEPORT_DOWN = 2 , PHASE_TELEPORTING = 3 , PHASE_STOP_TELEPORTING = 4 ,
SPELL_TELEPORT_RIGHT = 28025 , SPELL_TELEPORT_LEFT = 28026 , SPELL_HARVESTSOUL = 28679 , SPELL_SHADOWBOLT = 29317 ,
SPELL_IMMUNE_ALL = 29230 , SPELL_RESET_GOTHIK_EVENT = 28035 , SPELL_SUMMON_SPECTRAL_TRAINEE = 27921 , SPELL_SUMMON_SPECTRAL_KNIGHT = 27932 ,
SPELL_SUMMON_SPECTRAL_RIVENDARE = 27939 , SPELL_CHECK_SPECTRAL_SIDE = 28749 , SPELL_CHECK_UNRELENTING_SIDE = 29875
}
Functions
UnitAI * GetAI_boss_gothik (Creature *creature)
bool EffectDummyCreature_spell_anchor (Unit *, uint32 spellId, SpellEffectIndex effIndex, Creature *creatureTarget, ObjectGuid)
void AddSC_boss_gothik ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_SPEECH_1
SAY_SPEECH_2
SAY_SPEECH_3
SAY_SPEECH_4
SAY_KILL
SAY_DEATH
SAY_TELEPORT
PHASE_SPEECH
PHASE_BALCONY
PHASE_TELEPORT_DOWN
PHASE_TELEPORTING
PHASE_STOP_TELEPORTING
SPELL_TELEPORT_RIGHT
SPELL_TELEPORT_LEFT
SPELL_HARVESTSOUL
SPELL_SHADOWBOLT
SPELL_IMMUNE_ALL
SPELL_RESET_GOTHIK_EVENT
SPELL_SUMMON_SPECTRAL_TRAINEE
SPELL_SUMMON_SPECTRAL_KNIGHT
SPELL_SUMMON_SPECTRAL_RIVENDARE
SPELL_CHECK_SPECTRAL_SIDE
SPELL_CHECK_UNRELENTING_SIDE
Definition at line 27 of file boss_gothik.cpp.
Function Documentation
AddSC_boss_gothik()
void AddSC_boss_gothik ()
Definition at line 510 of file boss_gothik.cpp.
References EffectDummyCreature_spell_anchor(), Script::GetAI, GetAI_boss_gothik(), Script::Name, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyCreature_spell_anchor()
bool EffectDummyCreature_spell_anchor (Unit * , uint32 spellId, SpellEffectIndex effIndex, Creature * creatureTarget, ObjectGuid)
Definition at line 329 of file boss_gothik.cpp.
References Unit::CastSpell(), EFFECT_INDEX_0, instance_naxxramas::GetClosestAnchorForGothik(), Object::GetEntry(), instance_naxxramas::GetGothikSummonPoints(), WorldObject::GetInstanceData(), NPC_SUB_BOSS_TRIGGER, Unit::RemoveAurasDueToSpell(), SPELL_A_TO_ANCHOR_1, SPELL_A_TO_ANCHOR_2, SPELL_A_TO_SKULL, SPELL_B_TO_ANCHOR_1, SPELL_B_TO_ANCHOR_2, SPELL_B_TO_SKULL, SPELL_C_TO_ANCHOR_1, SPELL_C_TO_ANCHOR_2, SPELL_C_TO_SKULL, SPELL_RESET_GOTHIK_EVENT, SPELL_SUMMON_KNIGHT, SPELL_SUMMON_MOUNTED_KNIGHT, SPELL_SUMMON_SPECTRAL_KNIGHT, SPELL_SUMMON_SPECTRAL_RIVENDARE, SPELL_SUMMON_SPECTRAL_TRAINEE, SPELL_SUMMON_TRAINEE, TRIGGERED_OLD_TRIGGERED, and urand().
Referenced by AddSC_boss_gothik().
GetAI_boss_gothik()
UnitAI* GetAI_boss_gothik (Creature * creature)
Definition at line 324 of file boss_gothik.cpp.
Referenced by AddSC_boss_gothik().