CMaNGOS_TBC: boss_heigan.cpp File Reference
boss_heigan.cpp File Reference
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "AI/ScriptDevAI/include/sc_common.h"
#include "naxxramas.h"
Data Structures
struct boss_heiganAI
struct npc_diseased_maggotAI
struct PlagueWaveController
Enumerations
enum {
PHASE_GROUND = 1 , PHASE_PLATFORM = 2 , SAY_AGGRO1 = -1533109 , SAY_AGGRO2 = -1533110 ,
SAY_AGGRO3 = -1533111 , SAY_SLAY = -1533112 , SAY_TAUNT1 = -1533113 , SAY_TAUNT2 = -1533114 ,
SAY_TAUNT3 = -1533115 , SAY_TAUNT4 = -1533117 , SAY_CHANNELING = -1533116 , SAY_DEATH = -1533118 ,
SPELL_DECREPIT_FEVER = 29998 , SPELL_MANA_BURN = 29310 , SPELL_TELEPORT_SELF = 30211 , SPELL_TELEPORT_PLAYERS = 29273 ,
SPELL_PLAGUE_CLOUD = 29350 , SPELL_PLAGUE_WAVE_SLOW = 29351 , SPELL_PLAGUE_WAVE_FAST = 30114 , MAX_PLAYERS_TELEPORT = 3 ,
NPC_PLAGUE_WAVE = 17293 , NPC_WORLD_TRIGGER = 15384
}
enum HeiganActions {
HEIGAN_FEVER , HEIGAN_MANA_BURN , HEIGAN_TELEPORT_PLAYERS , HEIGAN_TAUNT ,
HEIGAN_ERUPTION , HEIGAN_PLATFORM_PHASE , HEIGAN_GROUND_PHASE , HEIGAN_CHANNELING ,
HEIGAN_ACTION_MAX , HEIGAN_DOOR
}
Functions
UnitAI * GetAI_npc_diseased_maggot (Creature *creature)
void AddSC_boss_heigan ()
Variables
static const float resetX = 2825.0f
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PHASE_GROUND
PHASE_PLATFORM
SAY_AGGRO1
SAY_AGGRO2
SAY_AGGRO3
SAY_SLAY
SAY_TAUNT1
SAY_TAUNT2
SAY_TAUNT3
SAY_TAUNT4
SAY_CHANNELING
SAY_DEATH
SPELL_DECREPIT_FEVER
SPELL_MANA_BURN
SPELL_TELEPORT_SELF
SPELL_TELEPORT_PLAYERS
SPELL_PLAGUE_CLOUD
SPELL_PLAGUE_WAVE_SLOW
SPELL_PLAGUE_WAVE_FAST
MAX_PLAYERS_TELEPORT
NPC_PLAGUE_WAVE
NPC_WORLD_TRIGGER
Definition at line 30 of file boss_heigan.cpp.
HeiganActions
enum HeiganActions
Enumerator
HEIGAN_FEVER
HEIGAN_MANA_BURN
HEIGAN_TELEPORT_PLAYERS
HEIGAN_TAUNT
HEIGAN_ERUPTION
HEIGAN_PLATFORM_PHASE
HEIGAN_GROUND_PHASE
HEIGAN_CHANNELING
HEIGAN_ACTION_MAX
HEIGAN_DOOR
Definition at line 64 of file boss_heigan.cpp.
Function Documentation
AddSC_boss_heigan()
void AddSC_boss_heigan ()
Definition at line 343 of file boss_heigan.cpp.
References Script::GetAI, GetAI_npc_diseased_maggot(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_npc_diseased_maggot()
UnitAI* GetAI_npc_diseased_maggot (Creature * creature)
Definition at line 326 of file boss_heigan.cpp.
Referenced by AddSC_boss_heigan().
Variable Documentation
resetX
const float resetX = 2825.0f static
Definition at line 61 of file boss_heigan.cpp.
Referenced by boss_heiganAI::boss_heiganAI().