CMaNGOS_TBC: boss_thaddius.cpp File Reference
boss_thaddius.cpp File Reference
#include "AI/ScriptDevAI/base/CombatAI.h"
#include "AI/ScriptDevAI/include/sc_common.h"
#include "naxxramas.h"
Data Structures
struct boss_thaddiusAI
struct boss_thaddiusAddsAI
struct boss_stalaggAI
struct boss_feugenAI
struct PolarityShift
struct ThaddiusChargeDamage
struct ThaddiusCharge
Enumerations
enum {
SAY_STAL_AGGRO = -1533023 , SAY_STAL_SLAY = -1533024 , SAY_STAL_DEATH = -1533025 , SAY_FEUG_AGGRO = -1533026 ,
SAY_FEUG_SLAY = -1533027 , SAY_FEUG_DEATH = -1533028 , SAY_AGGRO_1 = -1533030 , SAY_AGGRO_2 = -1533031 ,
SAY_AGGRO_3 = -1533032 , SAY_SLAY = -1533033 , SAY_ELECT = -1533034 , SAY_DEATH = -1533035 ,
EMOTE_TESLA_OVERLOAD = -1533150 , SPELL_THADIUS_SPAWN = 28160 , SPELL_THADIUS_LIGHTNING_VISUAL = 28136 , SPELL_BALL_LIGHTNING = 28299 ,
SPELL_CHAIN_LIGHTNING = 28167 , SPELL_POLARITY_SHIFT = 28089 , SPELL_POSITIVE_CHARGE = 28059 , SPELL_NEGATIVE_CHARGE = 28084 ,
SPELL_POSITIVE_CHARGE_BUFF = 29659 , SPELL_NEGATIVE_CHARGE_BUFF = 29660 , SPELL_POSITIVE_CHARGE_DAMAGE = 28062 , SPELL_NEGATIVE_CHARGE_DAMAGE = 28085 ,
SPELL_BESERK = 27680 , SPELL_WARSTOMP = 28125 , SPELL_MAGNETIC_PULL_A = 28338 , SPELL_MAGNETIC_PULL_B = 28339 ,
SPELL_STATIC_FIELD = 28135 , SPELL_POWERSURGE = 28134 , SPELL_FEUGEN_CHAIN = 28111 , SPELL_STALAGG_CHAIN = 28096 ,
SPELL_FEUGEN_TESLA_PASSIVE = 28109 , SPELL_STALAGG_TESLA_PASSIVE = 28097 , SPELL_SHOCK_OVERLOAD = 28159 , SPELL_TRIGGER_TESLAS = 28359
}
enum ThaddiusActions {
THADDIUS_POLARITY_SHIFT , THADDIUS_CHAIN_LIGHTNING , THADDIUS_BALL_LIGHTNING , THADDIUS_BERSERK ,
THADDIUS_ACTION_MAX
}
Functions
bool EffectDummyNPC_spell_thaddius_encounter (Unit *, uint32 spellId, SpellEffectIndex effIndex, Creature *creatureTarget, ObjectGuid)
UnitAI * GetAI_boss_stalagg (Creature *creature)
UnitAI * GetAI_boss_feugen (Creature *creature)
void AddSC_boss_thaddius ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_STAL_AGGRO
SAY_STAL_SLAY
SAY_STAL_DEATH
SAY_FEUG_AGGRO
SAY_FEUG_SLAY
SAY_FEUG_DEATH
SAY_AGGRO_1
SAY_AGGRO_2
SAY_AGGRO_3
SAY_SLAY
SAY_ELECT
SAY_DEATH
EMOTE_TESLA_OVERLOAD
SPELL_THADIUS_SPAWN
SPELL_THADIUS_LIGHTNING_VISUAL
SPELL_BALL_LIGHTNING
SPELL_CHAIN_LIGHTNING
SPELL_POLARITY_SHIFT
SPELL_POSITIVE_CHARGE
SPELL_NEGATIVE_CHARGE
SPELL_POSITIVE_CHARGE_BUFF
SPELL_NEGATIVE_CHARGE_BUFF
SPELL_POSITIVE_CHARGE_DAMAGE
SPELL_NEGATIVE_CHARGE_DAMAGE
SPELL_BESERK
SPELL_WARSTOMP
SPELL_MAGNETIC_PULL_A
SPELL_MAGNETIC_PULL_B
SPELL_STATIC_FIELD
SPELL_POWERSURGE
SPELL_FEUGEN_CHAIN
SPELL_STALAGG_CHAIN
SPELL_FEUGEN_TESLA_PASSIVE
SPELL_STALAGG_TESLA_PASSIVE
SPELL_SHOCK_OVERLOAD
SPELL_TRIGGER_TESLAS
Definition at line 34 of file boss_thaddius.cpp.
ThaddiusActions
enum ThaddiusActions
Enumerator
THADDIUS_POLARITY_SHIFT
THADDIUS_CHAIN_LIGHTNING
THADDIUS_BALL_LIGHTNING
THADDIUS_BERSERK
THADDIUS_ACTION_MAX
Definition at line 92 of file boss_thaddius.cpp.
Function Documentation
AddSC_boss_thaddius()
void AddSC_boss_thaddius ()
Definition at line 715 of file boss_thaddius.cpp.
References EffectDummyNPC_spell_thaddius_encounter(), Script::GetAI, GetAI_boss_feugen(), GetAI_boss_stalagg(), Script::Name, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
EffectDummyNPC_spell_thaddius_encounter()
bool EffectDummyNPC_spell_thaddius_encounter (Unit * , uint32 spellId, SpellEffectIndex effIndex, Creature * creatureTarget, ObjectGuid)
Definition at line 231 of file boss_thaddius.cpp.
References Unit::CastSpell(), EFFECT_INDEX_0, Object::GetEntry(), WorldObject::GetInstanceData(), GO_CONS_NOX_TESLA_FEUGEN, GO_CONS_NOX_TESLA_STALAGG, GO_STATE_READY, Unit::HasAura(), NPC_THADDIUS, Unit::RemoveAurasDueToSpell(), Creature::SetInCombatWithZone(), SPELL_SHOCK_OVERLOAD, SPELL_THADIUS_LIGHTNING_VISUAL, SPELL_THADIUS_SPAWN, and TRIGGERED_NONE.
Referenced by AddSC_boss_thaddius().
GetAI_boss_feugen()
UnitAI* GetAI_boss_feugen (Creature * creature)
Definition at line 604 of file boss_thaddius.cpp.
Referenced by AddSC_boss_thaddius().
GetAI_boss_stalagg()
UnitAI* GetAI_boss_stalagg (Creature * creature)
Definition at line 533 of file boss_thaddius.cpp.
Referenced by AddSC_boss_thaddius().