CMaNGOS_TBC: boss_kelthuzad.cpp File Reference
boss_kelthuzad.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "naxxramas.h"
Data Structures
struct boss_kelthuzadAI
struct npc_icecrown_guardianAI
struct TriggerKTAdd
struct ChainsKelThuzad
struct FrostBlast
struct GuardianPeriodic
Enumerations
enum {
SAY_SUMMON_MINIONS = -1533105 , SAY_AGGRO1 = -1533094 , SAY_AGGRO2 = -1533095 , SAY_AGGRO3 = -1533096 ,
SAY_SLAY1 = -1533097 , SAY_SLAY2 = -1533098 , SAY_DEATH = -1533099 , SAY_CHAIN1 = -1533100 ,
SAY_CHAIN2 = -1533101 , SAY_REQUEST_AID = -1533103 , SAY_ANSWER_REQUEST = -1533104 , SPELL_SUMMON_TYPE_A = 28421 ,
SPELL_SUMMON_TYPE_B = 28422 , SPELL_SUMMON_TYPE_C = 28423 , SPELL_CHANNEL_VISUAL_EFFECT = 29422 , SPELL_SUMMON_PERIODIC_A_1 = 29410 ,
SPELL_SUMMON_PERIODIC_A_2 = 29391 , SPELL_SUMMON_PERIODIC_A_3 = 28425 , SPELL_SUMMON_PERIODIC_A_4 = 29392 , SPELL_SUMMON_PERIODIC_A_5 = 29409 ,
SPELL_SUMMON_PERIODIC_B_1 = 28426 , SPELL_SUMMON_PERIODIC_B_2 = 29393 , SPELL_SUMMON_PERIODIC_B_3 = 29394 , SPELL_SUMMON_PERIODIC_B_4 = 29398 ,
SPELL_SUMMON_PERIODIC_B_5 = 29411 , SPELL_SUMMON_PERIODIC_C_1 = 29399 , SPELL_SUMMON_PERIODIC_C_2 = 29400 , SPELL_SUMMON_PERIODIC_C_3 = 28427 ,
SPELL_SUMMON_PERIODIC_C_4 = 29401 , SPELL_SUMMON_PERIODIC_C_5 = 29412 , MAX_SUMMON_TICKS = 5 * MINUTE + 10 , MAX_CHANNEL_TICKS = 5 * MINUTE + 25 ,
NPC_WORLD_TRIGGER = 15384 , SPELL_FROST_BOLT = 28478 , SPELL_FROST_BOLT_NOVA = 28479 , SPELL_CHAINS_OF_KELTHUZAD = 28408 ,
SPELL_CHAINS_OF_KELTHUZAD_SCALE = 28409 , SPELL_CHAINS_OF_KELTHUZAD_TARGET = 28410 , SPELL_MANA_DETONATION = 27819 , SPELL_SHADOW_FISSURE = 27810 ,
SPELL_FROST_BLAST = 27808 , SPELL_FROST_BLAST_DAMAGE = 29879 , SPELL_SUMMON_TYPE_D = 28454 , SPELL_SUMMON_PERIODIC_D = 28453 ,
SPELL_GUARDIAN_INIT = 29898 , MAX_CONTROLLED_TARGETS = 4
}
enum Phase { PHASE_NORMAL , PHASE_GUARDIANS }
enum { SPELL_GUARDIAN_PASSIVE = 29897 , SPELL_GUARDIAN_SHACKLE = 29899 , SPELL_BLOOD_TAP = 28470 }
Functions
UnitAI * GetAI_boss_kelthuzad (Creature *creature)
UnitAI * GetAI_npc_icecrown_guardian (Creature *creature)
void AddSC_boss_kelthuzad ()
Variables
static const uint32 phaseOneAdds [] = {NPC_SOLDIER_FROZEN, NPC_UNSTOPPABLE_ABOM, NPC_SOUL_WEAVER}
static const std::vector< std::vector< uint32 > > soulWeaverSpellsTimers
static const std::vector< std::vector< uint32 > > unstoppableAbominationSpellsTimers
static const std::vector< std::vector< uint32 > > soldierFrozenWasteSpellsTimers
static const std::map< uint32, std::vector< uint32 > > summoningSpells
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_SUMMON_MINIONS
SAY_AGGRO1
SAY_AGGRO2
SAY_AGGRO3
SAY_SLAY1
SAY_SLAY2
SAY_DEATH
SAY_CHAIN1
SAY_CHAIN2
SAY_REQUEST_AID
SAY_ANSWER_REQUEST
SPELL_SUMMON_TYPE_A
SPELL_SUMMON_TYPE_B
SPELL_SUMMON_TYPE_C
SPELL_CHANNEL_VISUAL_EFFECT
SPELL_SUMMON_PERIODIC_A_1
SPELL_SUMMON_PERIODIC_A_2
SPELL_SUMMON_PERIODIC_A_3
SPELL_SUMMON_PERIODIC_A_4
SPELL_SUMMON_PERIODIC_A_5
SPELL_SUMMON_PERIODIC_B_1
SPELL_SUMMON_PERIODIC_B_2
SPELL_SUMMON_PERIODIC_B_3
SPELL_SUMMON_PERIODIC_B_4
SPELL_SUMMON_PERIODIC_B_5
SPELL_SUMMON_PERIODIC_C_1
SPELL_SUMMON_PERIODIC_C_2
SPELL_SUMMON_PERIODIC_C_3
SPELL_SUMMON_PERIODIC_C_4
SPELL_SUMMON_PERIODIC_C_5
MAX_SUMMON_TICKS
MAX_CHANNEL_TICKS
NPC_WORLD_TRIGGER
SPELL_FROST_BOLT
SPELL_FROST_BOLT_NOVA
SPELL_CHAINS_OF_KELTHUZAD
SPELL_CHAINS_OF_KELTHUZAD_SCALE
SPELL_CHAINS_OF_KELTHUZAD_TARGET
SPELL_MANA_DETONATION
SPELL_SHADOW_FISSURE
SPELL_FROST_BLAST
SPELL_FROST_BLAST_DAMAGE
SPELL_SUMMON_TYPE_D
SPELL_SUMMON_PERIODIC_D
SPELL_GUARDIAN_INIT
MAX_CONTROLLED_TARGETS
Definition at line 27 of file boss_kelthuzad.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_GUARDIAN_PASSIVE
SPELL_GUARDIAN_SHACKLE
SPELL_BLOOD_TAP
Definition at line 542 of file boss_kelthuzad.cpp.
Phase
enum Phase
Enumerator
PHASE_NORMAL
PHASE_GUARDIANS
Definition at line 134 of file boss_kelthuzad.cpp.
Function Documentation
AddSC_boss_kelthuzad()
void AddSC_boss_kelthuzad ()
Definition at line 716 of file boss_kelthuzad.cpp.
References Script::GetAI, GetAI_boss_kelthuzad(), GetAI_npc_icecrown_guardian(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_kelthuzad()
UnitAI* GetAI_boss_kelthuzad (Creature * creature)
Definition at line 533 of file boss_kelthuzad.cpp.
Referenced by AddSC_boss_kelthuzad().
GetAI_npc_icecrown_guardian()
UnitAI* GetAI_npc_icecrown_guardian (Creature * creature)
Definition at line 613 of file boss_kelthuzad.cpp.
Referenced by AddSC_boss_kelthuzad().
Variable Documentation
phaseOneAdds
const uint32 phaseOneAdds[] = {NPC_SOLDIER_FROZEN, NPC_UNSTOPPABLE_ABOM, NPC_SOUL_WEAVER} static
Definition at line 98 of file boss_kelthuzad.cpp.
Referenced by boss_kelthuzadAI::UpdateSummoning().
soldierFrozenWasteSpellsTimers
const std::vector<std::vector<uint32> > soldierFrozenWasteSpellsTimers static
Initial value:
{
        {7,   SPELL_SUMMON_PERIODIC_A_1},
        {73,  SPELL_SUMMON_PERIODIC_A_2},
        {134, SPELL_SUMMON_PERIODIC_A_3},
        {189, SPELL_SUMMON_PERIODIC_A_4},
        {244, SPELL_SUMMON_PERIODIC_A_5},
        {292, 0}
}
Definition at line 118 of file boss_kelthuzad.cpp.
Referenced by boss_kelthuzadAI::UpdateSummoning().
soulWeaverSpellsTimers
const std::vector<std::vector<uint32> > soulWeaverSpellsTimers static
Initial value:
{
        {1,   SPELL_SUMMON_PERIODIC_C_1},
        {42,  SPELL_SUMMON_PERIODIC_C_4},
        {63,  SPELL_SUMMON_PERIODIC_C_3},
        {154, SPELL_SUMMON_PERIODIC_C_5},
        {290, 0}
}
Definition at line 101 of file boss_kelthuzad.cpp.
Referenced by boss_kelthuzadAI::UpdateSummoning().
summoningSpells
const std::map<uint32, std::vector<uint32> > summoningSpells static
Initial value:
{
        {NPC_SOUL_WEAVER,      {SPELL_SUMMON_PERIODIC_C_1, SPELL_SUMMON_PERIODIC_C_2, SPELL_SUMMON_PERIODIC_C_3, SPELL_SUMMON_PERIODIC_C_4, SPELL_SUMMON_PERIODIC_C_5}},
        {NPC_UNSTOPPABLE_ABOM, {SPELL_SUMMON_PERIODIC_B_1, SPELL_SUMMON_PERIODIC_B_2, SPELL_SUMMON_PERIODIC_B_3, SPELL_SUMMON_PERIODIC_B_4, SPELL_SUMMON_PERIODIC_B_5}},
        {NPC_SOLDIER_FROZEN,   {SPELL_SUMMON_PERIODIC_A_1, SPELL_SUMMON_PERIODIC_A_2, SPELL_SUMMON_PERIODIC_A_3, SPELL_SUMMON_PERIODIC_A_4, SPELL_SUMMON_PERIODIC_A_5}}
}
Definition at line 128 of file boss_kelthuzad.cpp.
Referenced by boss_kelthuzadAI::StopAllSummoningForNPC().
unstoppableAbominationSpellsTimers
const std::vector<std::vector<uint32> > unstoppableAbominationSpellsTimers static
Initial value:
{
        {15,  SPELL_SUMMON_PERIODIC_B_1},
        {76,  SPELL_SUMMON_PERIODIC_B_2},
        {127, SPELL_SUMMON_PERIODIC_B_3},
        {228, SPELL_SUMMON_PERIODIC_B_4},
        {259, SPELL_SUMMON_PERIODIC_B_5},
        {291, 0}
}
Definition at line 109 of file boss_kelthuzad.cpp.
Referenced by boss_kelthuzadAI::UpdateSummoning().