CMaNGOS_TBC: boss_four_horsemen.cpp File Reference
boss_four_horsemen.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "naxxramas.h"
Data Structures
struct Location2DPoint
struct boss_horsmenAI
struct boss_lady_blaumeuxAI
struct boss_alexandros_mograineAI
struct boss_thane_korthazzAI
struct boss_sir_zeliekAI
Enumerations
enum {
SAY_BLAU_AGGRO = -1533044 , SAY_BLAU_SPECIAL = -1533048 , SAY_BLAU_SLAY = -1533049 , SAY_BLAU_DEATH = -1533050 ,
SAY_MORG_AGGRO1 = -1533065 , SAY_MORG_AGGRO2 = -1533066 , SAY_MORG_AGGRO3 = -1533067 , SAY_MORG_SLAY1 = -1533068 ,
SAY_MORG_SLAY2 = -1533069 , SAY_MORG_SPECIAL = -1533070 , SAY_MORG_DEATH = -1533074 , SAY_KORT_AGGRO = -1533051 ,
SAY_KORT_SPECIAL = -1533055 , SAY_KORT_SLAY = -1533056 , SAY_KORT_DEATH = -1533057 , SAY_ZELI_AGGRO = -1533058 ,
SAY_ZELI_SPECIAL = -1533062 , SAY_ZELI_SLAY = -1533063 , SAY_ZELI_DEATH = -1533064 , SPELL_SHIELDWALL = 29061 ,
SPELL_MARK_OF_BLAUMEUX = 28833 , SPELL_VOID_ZONE = 28863 , SPELL_SPIRIT_BLAUMEUX = 28931 , SPELL_MARK_OF_MOGRAINE = 28834 ,
SPELL_RIGHTEOUS_FIRE = 28882 , SPELL_SPIRIT_MOGRAINE = 28928 , SPELL_MARK_OF_KORTHAZZ = 28832 , SPELL_METEOR = 28884 ,
SPELL_SPIRIT_KORTHAZZ = 28932 , SPELL_MARK_OF_ZELIEK = 28835 , SPELL_HOLY_WRATH = 28883 , SPELL_SPIRIT_ZELIEK = 28934 ,
INDEX_BLAUMEUX = 0 , INDEX_MORGRAINE = 1 , INDEX_KORTHAZZ = 2 , INDEX_ZELIEK = 3 ,
MAX_MARK_STACKS = 100
}
Functions
UnitAI * GetAI_boss_horsmen (Creature *creature)
UnitAI * GetAI_boss_lady_blaumeux (Creature *creature)
UnitAI * GetAI_boss_alexandros_mograine (Creature *creature)
UnitAI * GetAI_boss_thane_korthazz (Creature *creature)
UnitAI * GetAI_boss_sir_zeliek (Creature *creature)
void AddSC_boss_four_horsemen ()
Variables
static int32 const aggroSayList [4] = { SAY_BLAU_AGGRO, 0, SAY_KORT_AGGRO, SAY_ZELI_AGGRO }
static int32 const deathSayList [4] = { SAY_BLAU_DEATH, SAY_MORG_DEATH, SAY_KORT_DEATH, SAY_ZELI_DEATH }
static int32 const killSayList [4] = { SAY_BLAU_SLAY, 0, SAY_KORT_SLAY, SAY_ZELI_SLAY }
static uint32 const spiritSpellList [4] = { SPELL_SPIRIT_BLAUMEUX, SPELL_SPIRIT_MOGRAINE, SPELL_SPIRIT_KORTHAZZ, SPELL_SPIRIT_ZELIEK }
static uint32 const markSpellList [4] = { SPELL_MARK_OF_BLAUMEUX, SPELL_MARK_OF_MOGRAINE, SPELL_MARK_OF_KORTHAZZ, SPELL_MARK_OF_ZELIEK }
static const Location2DPoint resetCoords [3]
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_BLAU_AGGRO
SAY_BLAU_SPECIAL
SAY_BLAU_SLAY
SAY_BLAU_DEATH
SAY_MORG_AGGRO1
SAY_MORG_AGGRO2
SAY_MORG_AGGRO3
SAY_MORG_SLAY1
SAY_MORG_SLAY2
SAY_MORG_SPECIAL
SAY_MORG_DEATH
SAY_KORT_AGGRO
SAY_KORT_SPECIAL
SAY_KORT_SLAY
SAY_KORT_DEATH
SAY_ZELI_AGGRO
SAY_ZELI_SPECIAL
SAY_ZELI_SLAY
SAY_ZELI_DEATH
SPELL_SHIELDWALL
SPELL_MARK_OF_BLAUMEUX
SPELL_VOID_ZONE
SPELL_SPIRIT_BLAUMEUX
SPELL_MARK_OF_MOGRAINE
SPELL_RIGHTEOUS_FIRE
SPELL_SPIRIT_MOGRAINE
SPELL_MARK_OF_KORTHAZZ
SPELL_METEOR
SPELL_SPIRIT_KORTHAZZ
SPELL_MARK_OF_ZELIEK
SPELL_HOLY_WRATH
SPELL_SPIRIT_ZELIEK
INDEX_BLAUMEUX
INDEX_MORGRAINE
INDEX_KORTHAZZ
INDEX_ZELIEK
MAX_MARK_STACKS
Definition at line 27 of file boss_four_horsemen.cpp.
Function Documentation
AddSC_boss_four_horsemen()
void AddSC_boss_four_horsemen ()
Definition at line 369 of file boss_four_horsemen.cpp.
References Script::GetAI, GetAI_boss_alexandros_mograine(), GetAI_boss_lady_blaumeux(), GetAI_boss_sir_zeliek(), GetAI_boss_thane_korthazz(), Script::Name, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_alexandros_mograine()
UnitAI* GetAI_boss_alexandros_mograine (Creature * creature)
Definition at line 294 of file boss_four_horsemen.cpp.
Referenced by AddSC_boss_four_horsemen().
GetAI_boss_horsmen()
UnitAI* GetAI_boss_horsmen (Creature * creature)
Definition at line 202 of file boss_four_horsemen.cpp.
GetAI_boss_lady_blaumeux()
UnitAI* GetAI_boss_lady_blaumeux (Creature * creature)
Definition at line 241 of file boss_four_horsemen.cpp.
Referenced by AddSC_boss_four_horsemen().
GetAI_boss_sir_zeliek()
UnitAI* GetAI_boss_sir_zeliek (Creature * creature)
Definition at line 364 of file boss_four_horsemen.cpp.
Referenced by AddSC_boss_four_horsemen().
GetAI_boss_thane_korthazz()
UnitAI* GetAI_boss_thane_korthazz (Creature * creature)
Definition at line 329 of file boss_four_horsemen.cpp.
Referenced by AddSC_boss_four_horsemen().
Variable Documentation
aggroSayList
int32 const aggroSayList[4] = { SAY_BLAU_AGGRO, 0, SAY_KORT_AGGRO, SAY_ZELI_AGGRO } static
Definition at line 90 of file boss_four_horsemen.cpp.
Referenced by boss_horsmenAI::Aggro().
deathSayList
int32 const deathSayList[4] = { SAY_BLAU_DEATH, SAY_MORG_DEATH, SAY_KORT_DEATH, SAY_ZELI_DEATH } static
Definition at line 91 of file boss_four_horsemen.cpp.
Referenced by boss_horsmenAI::JustDied().
killSayList
int32 const killSayList[4] = { SAY_BLAU_SLAY, 0, SAY_KORT_SLAY, SAY_ZELI_SLAY } static
Definition at line 92 of file boss_four_horsemen.cpp.
Referenced by boss_horsmenAI::KilledUnit().
markSpellList
uint32 const markSpellList[4] = { SPELL_MARK_OF_BLAUMEUX, SPELL_MARK_OF_MOGRAINE, SPELL_MARK_OF_KORTHAZZ, SPELL_MARK_OF_ZELIEK } static
Definition at line 96 of file boss_four_horsemen.cpp.
Referenced by boss_horsmenAI::UpdateAI().
resetCoords
const Location2DPoint resetCoords[3] static
Initial value:
= {
        {2577.3f, -3024.0f},
        {2585.9f, -3015.1f},
        {2594.6f, -3006.7f}
}
Definition at line 104 of file boss_four_horsemen.cpp.
Referenced by boss_horsmenAI::boss_horsmenAI().
spiritSpellList
uint32 const spiritSpellList[4] = { SPELL_SPIRIT_BLAUMEUX, SPELL_SPIRIT_MOGRAINE, SPELL_SPIRIT_KORTHAZZ, SPELL_SPIRIT_ZELIEK } static
Definition at line 95 of file boss_four_horsemen.cpp.
Referenced by boss_horsmenAI::JustDied().