CMaNGOS_TBC: boss_anubrekhan.cpp File Reference
boss_anubrekhan.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "naxxramas.h"
Data Structures
struct boss_anubrekhanAI
Enumerations
enum {
SAY_GREET1 = -1533000 , SAY_GREET2 = -1533004 , SAY_GREET3 = -1533005 , SAY_GREET4 = -1533006 ,
SAY_GREET5 = -1533007 , SAY_AGGRO1 = -1533001 , SAY_AGGRO2 = -1533002 , SAY_AGGRO3 = -1533003 ,
SAY_SLAY = -1533008 , SPELL_DOUBLE_ATTACK = 18943 , SPELL_IMPALE = 28783 , SPELL_LOCUSTSWARM = 28785 ,
SPELL_ANUB_AURA = 29103 , SPELL_SUMMON_GUARD = 29508 , SPELL_DESPAWN_GUARDS = 29379 , SPELL_SPAWN_CORPSE_SCARABS = 28961
}
Functions
UnitAI * GetAI_boss_anubrekhan (Creature *creature)
bool GOUse_go_anub_door (Player *, GameObject *go)
void AddSC_boss_anubrekhan ()
Variables
static const DialogueEntry introDialogue []
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_GREET1
SAY_GREET2
SAY_GREET3
SAY_GREET4
SAY_GREET5
SAY_AGGRO1
SAY_AGGRO2
SAY_AGGRO3
SAY_SLAY
SPELL_DOUBLE_ATTACK
SPELL_IMPALE
SPELL_LOCUSTSWARM
SPELL_ANUB_AURA
SPELL_SUMMON_GUARD
SPELL_DESPAWN_GUARDS
SPELL_SPAWN_CORPSE_SCARABS
Definition at line 27 of file boss_anubrekhan.cpp.
Function Documentation
AddSC_boss_anubrekhan()
void AddSC_boss_anubrekhan ()
Definition at line 234 of file boss_anubrekhan.cpp.
References Script::GetAI, GetAI_boss_anubrekhan(), GOUse_go_anub_door(), Script::Name, Script::pGOUse, and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_boss_anubrekhan()
UnitAI* GetAI_boss_anubrekhan (Creature * creature)
Definition at line 211 of file boss_anubrekhan.cpp.
Referenced by AddSC_boss_anubrekhan().
GOUse_go_anub_door()
bool GOUse_go_anub_door (Player * , GameObject * go)
Definition at line 216 of file boss_anubrekhan.cpp.
References DONE, WorldObject::GetInstanceData(), IN_PROGRESS, NPC_ANUB_REKHAN, and TYPE_ANUB_REKHAN.
Referenced by AddSC_boss_anubrekhan().
Variable Documentation
introDialogue
const DialogueEntry introDialogue[] static
Initial value:
=
{
    {SAY_GREET1,  NPC_ANUB_REKHAN,  7000},
    {SAY_GREET2,  NPC_ANUB_REKHAN,  13000},
    {SAY_GREET3,  NPC_ANUB_REKHAN,  11000},
    {SAY_GREET4,  NPC_ANUB_REKHAN,  10000},
    {SAY_GREET5,  NPC_ANUB_REKHAN,  0},
}
Definition at line 51 of file boss_anubrekhan.cpp.