CMaNGOS_TBC: instance_naxxramas Class Reference
instance_naxxramas Class Reference
#include <naxxramas.h>
Public Member Functions
instance_naxxramas (Map *pMap)
~instance_naxxramas ()
void Initialize () override
bool IsEncounterInProgress () const override
void OnPlayerEnter (Player *player) override
void OnCreatureCreate (Creature *creature) override
void OnObjectCreate (GameObject *gameObject) override
void OnCreatureDeath (Creature *creature) override
void OnCreatureRespawn (Creature *creature) override
void SetData (uint32 type, uint32 data) override
uint32 GetData (uint32 type) const override
const char * Save () const override
void Load (const char *chrIn) override
void Update (const uint32 diff) override
void InitializeGothikTriggers ()
bool IsSuitableTriggerForSummon (Unit *trigger, uint8 flag)
Creature * GetClosestAnchorForGothik (Creature *source, bool rightSide)
void GetGothikSummonPoints (CreatureList &lList, bool rightSide)
bool IsInRightSideGothikArea (Unit *pUnit)
void DoTaunt ()
bool DoHandleEvent (uint32 eventId)
bool DoHandleAreaTrigger (AreaTriggerEntry const *areaTrigger)
Public Member Functions inherited from ScriptedInstance
ScriptedInstance (Map *map)
~ScriptedInstance ()
GameObject * GetSingleGameObjectFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded GameObject that was stored in m_goEntryGuidStore. Can return nullptr.
Creature * GetSingleCreatureFromStorage (uint32 entry, bool skipDebugLog=false) const
Returns a pointer to a loaded Creature that was stored in m_goEntryGuidStore. Can return nullptr.
void GetCreatureGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void GetGameObjectGuidVectorFromStorage (uint32 entry, GuidVector &entryGuidVector, bool skipDebugLog=false) const
void DoUseDoorOrButton (ObjectGuid guid, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or a button.
void DoUseDoorOrButton (uint32 entry, uint32 withRestoreTime=0, bool useAlternativeState=false)
Function that uses a door or button that is stored in m_goEntryGuidStore.
void DoUseOpenableObject (uint32 entry, bool open, uint32 withRestoreTime=0, bool useAlternativeState=false)
void DoRespawnGameObject (ObjectGuid guid, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GameObject with given time.
void DoRespawnGameObject (uint32 entry, uint32 timeToDespawn=MINUTE)
Function that respawns a despawned GO that is stored in m_goEntryGuidStore.
void DoToggleGameObjectFlags (ObjectGuid guid, uint32 GOflags, bool apply)
Function that toggles the GO-flags of a GameObject.
void DoToggleGameObjectFlags (uint32 entry, uint32 GOflags, bool apply)
Function that uses a door or button that is stored in m_goEntryGuidStore.
virtual void DoUpdateWorldState (uint32 stateId, uint32 stateData)
Helper function to update a world state for all players in the map.
Player * GetPlayerInMap (bool bOnlyAlive=false, bool bCanBeGamemaster=true) const
Get the first found Player* (with requested properties) in the map. Can return nullptr.
void DoOrSimulateScriptTextForThisInstance (int32 textEntry, uint32 creatureEntry)
void BanPlayersIfNoGm (const std::string &reason)
Public Member Functions inherited from InstanceData
InstanceData (Map *map)
virtual ~InstanceData ()
void SaveToDB () const
virtual void OnPlayerDeath (Player *)
virtual void OnPlayerResurrect (Player *)
virtual void OnPlayerLeave (Player *)
virtual void OnObjectSpawn (GameObject *)
virtual void OnCreatureEnterCombat (Creature *)
virtual void OnCreatureEvade (Creature *)
virtual void OnCreatureDespawn (Creature *)
virtual void OnCreatureGroupDespawn (CreatureGroup *, Creature *)
virtual void OnEventHappened (uint16, bool, bool)
virtual uint64 GetData64 (uint32) const
virtual void SetData64 (uint32, uint64)
ObjectGuid GetGuid (uint32 dataIdx) const
void SetGuid (uint32 dataIdx, ObjectGuid value)
virtual bool CheckConditionCriteriaMeet (Player const *source, uint32 instance_condition_id, WorldObject const *conditionSource, uint32 conditionSourceType) const
virtual void FillInitialWorldStates (ByteBuffer &, uint32 &, uint32, uint32)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, uint32 value)
void FillInitialWorldStateData (ByteBuffer &data, uint32 &count, uint32 state, int32 value)
virtual void ShowChatCommands (ChatHandler *)
virtual void ExecuteChatCommand (ChatHandler *, char *)
Protected Member Functions
void JustDidDialogueStep (int32 entry) override
Will be called when a dialogue step was done.
Protected Member Functions inherited from ScriptedInstance
void DespawnGuids (GuidVector &spawns)
void RespawnDbGuids (std::vector< uint32 > &spawns, uint32 respawnDelay)
Protected Attributes
uint32 m_auiEncounter [MAX_ENCOUNTER]
std::string m_strInstData
GuidList m_thaddiusTeslaCoilList
GuidList m_gothikTriggerList
GuidList m_zombieChowList
GuidList m_faerlinaFollowersList
GuidList m_unrelentingSideList
GuidList m_spectralSideList
GuidList m_icrecrownGuardianList
std::unordered_map< ObjectGuid, GothTrigger > m_gothikTriggerMap
uint32 m_sapphironSpawnTimer
uint32 m_tauntTimer
uint8 m_horsemenKilled
uint32 m_livingPoisonTimer
uint32 m_screamsTimer
uint32 m_horsemenTauntTimer
uint32 m_despawnKTTriggerTimer
uint32 m_checkGuardiansTimer
uint32 m_shackledGuardians
bool isFaerlinaIntroDone
Protected Attributes inherited from ScriptedInstance
EntryGuidMap m_goEntryGuidStore
EntryGuidMap m_npcEntryGuidStore
EntryGuidCollection m_npcEntryGuidCollection
EntryGuidCollection m_goEntryGuidCollection
Additional Inherited Members
Public Types inherited from ScriptedInstance
typedef std::map< uint32, ObjectGuid > EntryGuidMap
typedef std::unordered_map< uint32, GuidVector > EntryGuidCollection
Data Fields inherited from InstanceData
Map * instance
Private Member Functions inherited from DialogueHelper
DialogueHelper (DialogueEntry const *dialogueArray)
Constructor for DialogueHelper.
DialogueHelper (DialogueEntryTwoSide const *dialogueTwoSideArray)
Constructor for DialogueHelper (Two Sides)
virtual ~DialogueHelper ()=default
void InitializeDialogueHelper (ScriptedInstance *instance, bool canSimulateText=false)
Function to initialize the dialogue helper for instances. If not used with instances, GetSpeakerByEntry MUST be overwritten to obtain the speakers.
void SetDialogueSide (bool isFirstSide)
Set if take first entries or second entries.
void StartNextDialogueText (int32 textEntry)
Function to start a (part of a) dialogue.
void DialogueUpdate (uint32 diff)
Call this function within any DialogueUpdate method. This is required for saying next steps in a dialogue.
void DisableDialogue ()
virtual Creature * GetSpeakerByEntry (uint32)
Will be called to get a speaker, MUST be implemented if not used in instances.
Detailed Description
Definition at line 257 of file naxxramas.h.
Constructor & Destructor Documentation
instance_naxxramas()
instance_naxxramas::instance_naxxramas (Map * pMap)
Definition at line 51 of file naxxramas.cpp.
References Initialize().
~instance_naxxramas()
instance_naxxramas::~instance_naxxramas () inline
Definition at line 261 of file naxxramas.h.
Member Function Documentation
DoHandleAreaTrigger()
bool instance_naxxramas::DoHandleAreaTrigger (AreaTriggerEntry const * areaTrigger)
Definition at line 1206 of file naxxramas.cpp.
References AREATRIGGER_FAERLINA_INTRO, AREATRIGGER_FROSTWYRM_TELE, AREATRIGGER_KELTHUZAD, AREATRIGGER_THADDIUS_DOOR, DONE, DoScriptText(), FAIL, GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), AreaTriggerEntry::id, IN_PROGRESS, isFaerlinaIntroDone, NOT_STARTED, NPC_THADDIUS, SAY_FAERLINA_INTRO, SAY_THADDIUS_GREET, SetData(), SPECIAL, DialogueHelper::StartNextDialogueText(), TYPE_FAERLINA, TYPE_FOUR_HORSEMEN, TYPE_KELTHUZAD, TYPE_LOATHEB, TYPE_MAEXXNA, and TYPE_THADDIUS.
DoHandleEvent()
bool instance_naxxramas::DoHandleEvent (uint32 eventId)
Definition at line 1022 of file naxxramas.cpp.
References EVENT_CLEAR_SHACKLES, EVENT_GUARDIAN_SHACKLE, EVENT_ID_DECIMATE, Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), IN_MILLISECONDS, InstanceData::instance, m_checkGuardiansTimer, m_shackledGuardians, m_zombieChowList, NPC_GLUTH, and REACT_PASSIVE.
DoTaunt()
void instance_naxxramas::DoTaunt ()
Definition at line 991 of file naxxramas.cpp.
References DONE, ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), m_auiEncounter, NPC_KELTHUZAD, SAY_KELTHUZAD_TAUNT1, SAY_KELTHUZAD_TAUNT2, SAY_KELTHUZAD_TAUNT3, SAY_KELTHUZAD_TAUNT4, TYPE_FOUR_HORSEMEN, TYPE_KELTHUZAD, TYPE_LOATHEB, TYPE_MAEXXNA, and TYPE_THADDIUS.
Referenced by Update().
GetClosestAnchorForGothik()
Creature * instance_naxxramas::GetClosestAnchorForGothik (Creature * source, bool rightSide)
Definition at line 936 of file naxxramas.cpp.
References Map::GetCreature(), InstanceData::instance, and m_gothikTriggerMap.
Referenced by EffectDummyCreature_spell_anchor(), and OnCreatureDeath().
GetData()
uint32 instance_naxxramas::GetData (uint32 type) const override virtual
Reimplemented from InstanceData.
Definition at line 740 of file naxxramas.cpp.
References m_auiEncounter, and MAX_ENCOUNTER.
Referenced by DoHandleAreaTrigger(), and OnPlayerEnter().
GetGothikSummonPoints()
void instance_naxxramas::GetGothikSummonPoints (CreatureList & lList, bool rightSide)
Definition at line 961 of file naxxramas.cpp.
References Map::GetCreature(), InstanceData::instance, and m_gothikTriggerMap.
Referenced by EffectDummyCreature_spell_anchor().
Initialize()
void instance_naxxramas::Initialize () override virtual
Reimplemented from InstanceData.
Definition at line 66 of file naxxramas.cpp.
References DialogueHelper::InitializeDialogueHelper(), and m_auiEncounter.
Referenced by instance_naxxramas().
InitializeGothikTriggers()
void instance_naxxramas::InitializeGothikTriggers ()
Definition at line 878 of file naxxramas.cpp.
References Map::GetCreature(), WorldObject::GetPositionZ(), ScriptedInstance::GetSingleCreatureFromStorage(), InstanceData::instance, GothTrigger::isAnchorHigh, IsInRightSideGothikArea(), GothTrigger::isRightSide, m_gothikTriggerList, m_gothikTriggerMap, NPC_GOTHIK, script_error_log(), SUMMON_FLAG_KNIGHT, SUMMON_FLAG_RIDER, SUMMON_FLAG_TRAINEE, and GothTrigger::summonTypeFlag.
Referenced by SetData().
IsEncounterInProgress()
bool instance_naxxramas::IsEncounterInProgress () const override virtual
Reimplemented from InstanceData.
Definition at line 411 of file naxxramas.cpp.
References IN_PROGRESS, m_auiEncounter, SPECIAL, TYPE_GOTHIK, and TYPE_KELTHUZAD.
IsInRightSideGothikArea()
bool instance_naxxramas::IsInRightSideGothikArea (Unit * pUnit)
Definition at line 977 of file naxxramas.cpp.
References WorldObject::GetPositionY(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_MILI_GOTH_COMBAT_GATE, and script_error_log().
Referenced by boss_gothikAI::HasPlayersInLeftSide(), InitializeGothikTriggers(), and boss_gothikAI::UpdateAI().
IsSuitableTriggerForSummon()
bool instance_naxxramas::IsSuitableTriggerForSummon (Unit * trigger, uint8 flag)
Definition at line 986 of file naxxramas.cpp.
References Object::GetObjectGuid(), and m_gothikTriggerMap.
JustDidDialogueStep()
void instance_naxxramas::JustDidDialogueStep (int32) override protected virtual
Will be called when a dialogue step was done.
Reimplemented from DialogueHelper.
Definition at line 73 of file naxxramas.cpp.
References FOLLOWERS_AURA, FOLLOWERS_KNEEL, FOLLOWERS_STAND, Map::GetCreature(), InstanceData::instance, isFaerlinaIntroDone, m_faerlinaFollowersList, SPELL_DARK_CHANNELING, TRIGGERED_OLD_TRIGGERED, UNIT_STAND_STATE_KNEEL, and UNIT_STAND_STATE_STAND.
Load()
void instance_naxxramas::Load (const char * chrIn) override virtual
Reimplemented from InstanceData.
Definition at line 715 of file naxxramas.cpp.
References IN_PROGRESS, m_auiEncounter, NOT_STARTED, OUT_LOAD_INST_DATA, OUT_LOAD_INST_DATA_COMPLETE, and OUT_LOAD_INST_DATA_FAIL.
OnCreatureCreate()
void instance_naxxramas::OnCreatureCreate (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 135 of file naxxramas.cpp.
References Map::GetCreature(), Object::GetEntry(), WorldObject::GetMap(), Object::GetObjectGuid(), WorldObject::GetSpawnerGuid(), IN_MILLISECONDS, ObjectGuid::IsCreature(), Creature::IsTemporarySummon(), m_faerlinaFollowersList, m_gothikTriggerList, m_icrecrownGuardianList, m_livingPoisonTimer, ScriptedInstance::m_npcEntryGuidStore, m_spectralSideList, m_thaddiusTeslaCoilList, m_unrelentingSideList, m_zombieChowList, NPC_ANUB_REKHAN, NPC_BLAUMEUX, NPC_FAERLINA, NPC_FEUGEN, NPC_GLUTH, NPC_GOTHIK, NPC_GUARDIAN, NPC_KELTHUZAD, NPC_MOGRAINE, NPC_NAXXRAMAS_ACOLYTE, NPC_NAXXRAMAS_CULTIST, NPC_NAXXRAMAS_TRIGGER, NPC_SAPPHIRON, NPC_SOLDIER_FROZEN, NPC_SOUL_WEAVER, NPC_SPECT_DEATH_KNIGHT, NPC_SPECT_HORSE, NPC_SPECT_RIDER, NPC_SPECT_TRAINEE, NPC_SPIRIT_OF_BLAUMEUX, NPC_SPIRIT_OF_KORTHAZZ, NPC_SPIRIT_OF_MOGRAINE, NPC_SPIRIT_OF_ZELIREK, NPC_STALAGG, NPC_SUB_BOSS_TRIGGER, NPC_TESLA_COIL, NPC_THADDIUS, NPC_THANE, NPC_THE_LICHKING, NPC_TOXIC_TUNNEL, NPC_UNREL_DEATH_KNIGHT, NPC_UNREL_RIDER, NPC_UNREL_TRAINEE, NPC_UNSTOPPABLE_ABOM, NPC_ZELIEK, NPC_ZOMBIE_CHOW, and Unit::SetCanEnterCombat().
OnCreatureDeath()
void instance_naxxramas::OnCreatureDeath (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 346 of file naxxramas.cpp.
References Unit::CastSpell(), DONE, ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), Creature::ForcedDespawn(), GetClosestAnchorForGothik(), Object::GetEntry(), Object::GetObjectGuid(), m_auiEncounter, m_spectralSideList, m_unrelentingSideList, m_zombieChowList, NPC_KELTHUZAD, NPC_MR_BIGGLESWORTH, NPC_SOLDIER_FROZEN, NPC_SOUL_WEAVER, NPC_SPECT_DEATH_KNIGHT, NPC_SPECT_HORSE, NPC_SPECT_RIDER, NPC_SPECT_TRAINEE, NPC_UNREL_DEATH_KNIGHT, NPC_UNREL_RIDER, NPC_UNREL_TRAINEE, NPC_UNSTOPPABLE_ABOM, NPC_ZOMBIE_CHOW, SAY_KELTHUZAD_CAT_DIED, SPELL_A_TO_ANCHOR_1, SPELL_B_TO_ANCHOR_1, SPELL_C_TO_ANCHOR_1, TRIGGERED_OLD_TRIGGERED, and TYPE_KELTHUZAD.
OnCreatureRespawn()
void instance_naxxramas::OnCreatureRespawn (Creature * creature) override virtual
Reimplemented from InstanceData.
Definition at line 393 of file naxxramas.cpp.
References Object::GetEntry(), Creature::IsTemporarySummon(), NPC_CORPSE_SCARAB, NPC_GUARDIAN, NPC_SOLDIER_FROZEN, NPC_SOUL_WEAVER, NPC_UNSTOPPABLE_ABOM, NPC_ZOMBIE_CHOW, and Creature::SetInCombatWithZone().
OnObjectCreate()
void instance_naxxramas::OnObjectCreate (GameObject * gameObject) override virtual
Reimplemented from InstanceData.
Definition at line 213 of file naxxramas.cpp.
References DONE, GAMEOBJECT_FLAGS, Object::GetEntry(), Object::GetObjectGuid(), GO_ARAC_ANUB_DOOR, GO_ARAC_ANUB_GATE, GO_ARAC_EYE_BOSS, GO_ARAC_EYE_RAMP, GO_ARAC_FAER_DOOR, GO_ARAC_FAER_WEB, GO_ARAC_MAEX_INNER_DOOR, GO_ARAC_MAEX_OUTER_DOOR, GO_ARAC_PORTAL, GO_CHEST_HORSEMEN_NORM, GO_CONS_EYE_BOSS, GO_CONS_EYE_RAMP, GO_CONS_GLUT_EXIT_DOOR, GO_CONS_NOX_TESLA_FEUGEN, GO_CONS_NOX_TESLA_STALAGG, GO_CONS_PATH_EXIT_DOOR, GO_CONS_PORTAL, GO_CONS_THAD_DOOR, GO_FLAG_NO_INTERACT, GO_JUST_DEACTIVATED, GO_KELTHUZAD_EXIT_DOOR, GO_KELTHUZAD_TRIGGER, GO_KELTHUZAD_WATERFALL_DOOR, GO_KELTHUZAD_WINDOW_1, GO_KELTHUZAD_WINDOW_2, GO_KELTHUZAD_WINDOW_3, GO_KELTHUZAD_WINDOW_4, GO_MILI_EYE_BOSS, GO_MILI_EYE_RAMP, GO_MILI_GOTH_COMBAT_GATE, GO_MILI_GOTH_ENTRY_GATE, GO_MILI_GOTH_EXIT_GATE, GO_MILI_HORSEMEN_DOOR, GO_MILI_PORTAL, GO_PLAG_EYE_BOSS, GO_PLAG_EYE_RAMP, GO_PLAG_HEIG_ENTRY_DOOR, GO_PLAG_HEIG_EXIT_HALLWAY, GO_PLAG_LOAT_DOOR, GO_PLAG_NOTH_ENTRY_DOOR, GO_PLAG_NOTH_EXIT_DOOR, GO_PLAG_PORTAL, GO_STATE_ACTIVE, GO_STATE_READY, m_auiEncounter, ScriptedInstance::m_goEntryGuidStore, NOT_STARTED, Object::RemoveFlag(), GameObject::SetGoState(), GameObject::SetLootState(), TYPE_ANUB_REKHAN, TYPE_FAERLINA, TYPE_FOUR_HORSEMEN, TYPE_GLUTH, TYPE_GOTHIK, TYPE_HEIGAN, TYPE_KELTHUZAD, TYPE_LOATHEB, TYPE_MAEXXNA, TYPE_NOTH, TYPE_PATCHWERK, TYPE_SAPPHIRON, and TYPE_THADDIUS.
OnPlayerEnter()
void instance_naxxramas::OnPlayerEnter (Player * player) override virtual
Reimplemented from InstanceData.
Definition at line 122 of file naxxramas.cpp.
References GetData(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_SAPPHIRON, sapphironPositions, SPECIAL, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, and TYPE_SAPPHIRON.
Save()
const char* instance_naxxramas::Save () const inline override virtual
Reimplemented from InstanceData.
Definition at line 278 of file naxxramas.h.
References m_strInstData.
SetData()
void instance_naxxramas::SetData (uint32 type, uint32 data) override virtual
Reimplemented from InstanceData.
Definition at line 423 of file naxxramas.cpp.
References DONE, ScriptedInstance::DoRespawnGameObject(), DoScriptText(), ScriptedInstance::DoToggleGameObjectFlags(), ScriptedInstance::DoUseDoorOrButton(), EMOTE_FLEE, FAIL, Map::GetCreature(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_ARAC_ANUB_DOOR, GO_ARAC_ANUB_GATE, GO_ARAC_EYE_BOSS, GO_ARAC_EYE_RAMP, GO_ARAC_FAER_DOOR, GO_ARAC_FAER_WEB, GO_ARAC_MAEX_INNER_DOOR, GO_ARAC_MAEX_OUTER_DOOR, GO_ARAC_PORTAL, GO_CHEST_HORSEMEN_NORM, GO_CONS_EYE_BOSS, GO_CONS_EYE_RAMP, GO_CONS_GLUT_EXIT_DOOR, GO_CONS_NOX_TESLA_FEUGEN, GO_CONS_NOX_TESLA_STALAGG, GO_CONS_PATH_EXIT_DOOR, GO_CONS_PORTAL, GO_CONS_THAD_DOOR, GO_FLAG_NO_INTERACT, GO_KELTHUZAD_EXIT_DOOR, GO_KELTHUZAD_TRIGGER, GO_KELTHUZAD_WATERFALL_DOOR, GO_KELTHUZAD_WINDOW_1, GO_KELTHUZAD_WINDOW_2, GO_KELTHUZAD_WINDOW_3, GO_KELTHUZAD_WINDOW_4, GO_MILI_EYE_BOSS, GO_MILI_EYE_RAMP, GO_MILI_GOTH_COMBAT_GATE, GO_MILI_GOTH_ENTRY_GATE, GO_MILI_GOTH_EXIT_GATE, GO_MILI_HORSEMEN_DOOR, GO_MILI_PORTAL, GO_PLAG_EYE_BOSS, GO_PLAG_EYE_RAMP, GO_PLAG_HEIG_ENTRY_DOOR, GO_PLAG_HEIG_EXIT_HALLWAY, GO_PLAG_LOAT_DOOR, GO_PLAG_NOTH_ENTRY_DOOR, GO_PLAG_NOTH_EXIT_DOOR, GO_PLAG_PORTAL, GO_STATE_ACTIVE, IN_MILLISECONDS, IN_PROGRESS, InitializeGothikTriggers(), InstanceData::instance, m_auiEncounter, m_checkGuardiansTimer, m_despawnKTTriggerTimer, m_horsemenKilled, m_icrecrownGuardianList, m_sapphironSpawnTimer, m_shackledGuardians, m_spectralSideList, m_strInstData, m_tauntTimer, m_thaddiusTeslaCoilList, m_unrelentingSideList, MINUTE, NPC_BLAUMEUX, NPC_FEUGEN, NPC_KELTHUZAD, NPC_MOGRAINE, NPC_SPIRIT_OF_BLAUMEUX, NPC_SPIRIT_OF_KORTHAZZ, NPC_SPIRIT_OF_MOGRAINE, NPC_SPIRIT_OF_ZELIREK, NPC_STALAGG, NPC_THANE, NPC_ZELIEK, OUT_SAVE_INST_DATA, OUT_SAVE_INST_DATA_COMPLETE, InstanceData::SaveToDB(), SPECIAL, SPELL_CHANNEL_VISUAL, SPELL_SPECTRAL_ASSAULT, SPELL_UNRELENTING_ASSAULT, DialogueHelper::StartNextDialogueText(), TRIGGERED_OLD_TRIGGERED, TYPE_ANUB_REKHAN, TYPE_FAERLINA, TYPE_FOUR_HORSEMEN, TYPE_GLUTH, TYPE_GOTHIK, TYPE_GROBBULUS, TYPE_HEIGAN, TYPE_KELTHUZAD, TYPE_LOATHEB, TYPE_MAEXXNA, TYPE_NOTH, TYPE_PATCHWERK, TYPE_RAZUVIOUS, TYPE_SAPPHIRON, and TYPE_THADDIUS.
Referenced by boss_anubrekhanAI::Aggro(), boss_gothikAI::Aggro(), boss_thaddiusAddsAI::Aggro(), DoHandleAreaTrigger(), boss_gothikAI::EnterEvadeMode(), boss_kelthuzadAI::EnterEvadeMode(), boss_anubrekhanAI::JustDied(), boss_gothikAI::JustDied(), boss_kelthuzadAI::JustDied(), boss_anubrekhanAI::JustReachedHome(), boss_gothikAI::JustReachedHome(), boss_thaddiusAddsAI::JustReachedHome(), and boss_gothikAI::UpdateAI().
Update()
void instance_naxxramas::Update (const uint32 diff) override virtual
Reimplemented from InstanceData.
Definition at line 748 of file naxxramas.cpp.
References DialogueHelper::DialogueUpdate(), DONE, ScriptedInstance::DoOrSimulateScriptTextForThisInstance(), DoScriptText(), DoTaunt(), ScriptedInstance::GetPlayerInMap(), ScriptedInstance::GetSingleCreatureFromStorage(), ScriptedInstance::GetSingleGameObjectFromStorage(), GO_JUST_DEACTIVATED, GO_KELTHUZAD_TRIGGER, IN_MILLISECONDS, livingPoisonPositions, m_auiEncounter, m_checkGuardiansTimer, m_despawnKTTriggerTimer, SpawnLocation::m_fO, SpawnLocation::m_fX, SpawnLocation::m_fY, SpawnLocation::m_fZ, m_horsemenTauntTimer, m_livingPoisonTimer, m_sapphironSpawnTimer, m_screamsTimer, m_shackledGuardians, m_tauntTimer, MAX_SHACKLES, MINUTE, NOT_STARTED, NPC_BLAUMEUX, NPC_KELTHUZAD, NPC_LIVING_POISON, NPC_MOGRAINE, NPC_NAXXRAMAS_TRIGGER, NPC_SAPPHIRON, NPC_THANE, NPC_ZELIEK, sapphironPositions, SAY_BLAU_TAUNT3, SAY_KELTHUZAD_SHACKLES_1, SAY_KELTHUZAD_SHACKLES_2, SAY_KORT_TAUNT3, SAY_MORG_TAUNT3, SAY_ZELI_TAUNT3, SOUND_SCREAM1, SPELL_CLEAR_ALL_SHACKLES, WorldObject::SummonCreature(), TEMPSPAWN_DEAD_DESPAWN, TRIGGERED_OLD_TRIGGERED, TYPE_FOUR_HORSEMEN, TYPE_THADDIUS, and urand().
Field Documentation
isFaerlinaIntroDone
bool instance_naxxramas::isFaerlinaIntroDone protected
Definition at line 321 of file naxxramas.h.
Referenced by DoHandleAreaTrigger(), and JustDidDialogueStep().
m_auiEncounter
uint32 instance_naxxramas::m_auiEncounter[MAX_ENCOUNTER] protected
Definition at line 298 of file naxxramas.h.
Referenced by DoTaunt(), GetData(), Initialize(), IsEncounterInProgress(), Load(), OnCreatureDeath(), OnObjectCreate(), SetData(), and Update().
m_checkGuardiansTimer
uint32 instance_naxxramas::m_checkGuardiansTimer protected
Definition at line 318 of file naxxramas.h.
Referenced by DoHandleEvent(), SetData(), and Update().
m_despawnKTTriggerTimer
uint32 instance_naxxramas::m_despawnKTTriggerTimer protected
Definition at line 317 of file naxxramas.h.
Referenced by SetData(), and Update().
m_faerlinaFollowersList
GuidList instance_naxxramas::m_faerlinaFollowersList protected
Definition at line 304 of file naxxramas.h.
Referenced by JustDidDialogueStep(), and OnCreatureCreate().
m_gothikTriggerList
GuidList instance_naxxramas::m_gothikTriggerList protected
Definition at line 302 of file naxxramas.h.
Referenced by InitializeGothikTriggers(), and OnCreatureCreate().
m_gothikTriggerMap
std::unordered_map<ObjectGuid, GothTrigger> instance_naxxramas::m_gothikTriggerMap protected
Definition at line 309 of file naxxramas.h.
Referenced by GetClosestAnchorForGothik(), GetGothikSummonPoints(), InitializeGothikTriggers(), and IsSuitableTriggerForSummon().
m_horsemenKilled
uint8 instance_naxxramas::m_horsemenKilled protected
Definition at line 313 of file naxxramas.h.
Referenced by SetData().
m_horsemenTauntTimer
uint32 instance_naxxramas::m_horsemenTauntTimer protected
Definition at line 316 of file naxxramas.h.
Referenced by Update().
m_icrecrownGuardianList
GuidList instance_naxxramas::m_icrecrownGuardianList protected
Definition at line 307 of file naxxramas.h.
Referenced by OnCreatureCreate(), and SetData().
m_livingPoisonTimer
uint32 instance_naxxramas::m_livingPoisonTimer protected
Definition at line 314 of file naxxramas.h.
Referenced by OnCreatureCreate(), and Update().
m_sapphironSpawnTimer
uint32 instance_naxxramas::m_sapphironSpawnTimer protected
Definition at line 311 of file naxxramas.h.
Referenced by SetData(), and Update().
m_screamsTimer
uint32 instance_naxxramas::m_screamsTimer protected
Definition at line 315 of file naxxramas.h.
Referenced by Update().
m_shackledGuardians
uint32 instance_naxxramas::m_shackledGuardians protected
Definition at line 319 of file naxxramas.h.
Referenced by DoHandleEvent(), SetData(), and Update().
m_spectralSideList
GuidList instance_naxxramas::m_spectralSideList protected
Definition at line 306 of file naxxramas.h.
Referenced by OnCreatureCreate(), OnCreatureDeath(), and SetData().
m_strInstData
std::string instance_naxxramas::m_strInstData protected
Definition at line 299 of file naxxramas.h.
Referenced by Save(), and SetData().
m_tauntTimer
uint32 instance_naxxramas::m_tauntTimer protected
Definition at line 312 of file naxxramas.h.
Referenced by SetData(), and Update().
m_thaddiusTeslaCoilList
GuidList instance_naxxramas::m_thaddiusTeslaCoilList protected
Definition at line 301 of file naxxramas.h.
Referenced by OnCreatureCreate(), and SetData().
m_unrelentingSideList
GuidList instance_naxxramas::m_unrelentingSideList protected
Definition at line 305 of file naxxramas.h.
Referenced by OnCreatureCreate(), OnCreatureDeath(), and SetData().
m_zombieChowList
GuidList instance_naxxramas::m_zombieChowList protected
Definition at line 303 of file naxxramas.h.
Referenced by DoHandleEvent(), OnCreatureCreate(), and OnCreatureDeath().
The documentation for this class was generated from the following files:
naxxramas.h
naxxramas.cpp