CMaNGOS_TBC: SpellAuraHolder Class Reference
SpellAuraHolder Class Reference
#include <SpellAuras.h>
Public Member Functions
SpellAuraHolder (SpellEntry const *spellproto, Unit *target, WorldObject *caster, Item *castItem, SpellEntry const *triggeredBy)
~SpellAuraHolder ()
void AddAura (Aura *aura, SpellEffectIndex index)
void RemoveAura (SpellEffectIndex index)
void ApplyAuraModifiers (bool apply, bool real=false)
void _AddSpellAuraHolder ()
void _RemoveSpellAuraHolder ()
void HandleSpellSpecificBoosts (bool apply)
void CleanupTriggeredSpells ()
void setDiminishGroup (DiminishingGroup group)
DiminishingGroup getDiminishGroup () const
uint32 GetStackAmount () const
void SetStackAmount (uint32 stackAmount, Unit *newCaster)
bool ModStackAmount (int32 num, Unit *newCaster)
Aura * GetAuraByEffectIndex (SpellEffectIndex index) const
SpellEntry const * GetTriggeredBy () const
uint32 GetId () const
SpellEntry const * GetSpellProto () const
SpellAuraHolderState GetState () const
void SetState (SpellAuraHolderState state)
ObjectGuid const & GetCasterGuid () const
void SetCasterGuid (ObjectGuid guid)
ObjectGuid const & GetCastItemGuid () const
Unit * GetCaster () const
Unit * GetTarget () const
void SetTarget (Unit *target)
bool IsPermanent () const
void SetPermanent (bool permanent)
bool IsPassive () const
bool IsDeathPersistent () const
bool IsPersistent () const
bool IsPositive () const
bool IsAreaAura () const
bool IsWeaponBuffCoexistableWith (SpellAuraHolder const *ref) const
bool IsNeedVisibleSlot (Unit const *caster) const
bool IsRemovedOnShapeLost () const
bool IsDeleted () const
bool IsEmptyHolder () const
bool IsSaveToDbHolder () const
bool IsCharm () const
void SetDeleted ()
void UpdateHolder (uint32 diff)
void Update (uint32 diff)
void RefreshHolder ()
TrackedAuraType GetTrackedAuraType () const
void SetTrackedAuraType (TrackedAuraType val)
void UnregisterAndCleanupTrackedAuras ()
int32 GetAuraMaxDuration () const
void SetAuraMaxDuration (int32 duration)
int32 GetAuraDuration () const
void SetAuraDuration (int32 duration)
void SetHeartbeatResist (uint32 chance, int32 originalDuration, uint32 drLevel)
uint8 GetAuraSlot () const
void SetAuraSlot (uint8 slot)
uint8 GetAuraLevel () const
void SetAuraLevel (uint8 level)
uint32 GetAuraCharges () const
void SetAuraCharges (uint32 charges, bool update=true)
bool DropAuraCharge ()
void ResetSpellModCharges ()
bool HasModifier (const uint64 &modId) const
uint32 GetAuraApplyTime () const
uint32 GetAuraApplyMSTime () const
void SetRemoveMode (AuraRemoveMode mode)
void SetLoadedState (ObjectGuid const &casterGUID, ObjectGuid const &itemGUID, uint32 stackAmount, uint32 charges, int32 maxduration, int32 duration)
bool HasMechanic (uint32 mechanic) const
bool HasMechanicMask (uint32 mechanicMask) const
bool IsDispellableByMask (uint32 dispelMask, Unit const *caster, SpellEntry const *spellInfo) const
void UpdateAuraDuration ()
void LoginAuraDuration ()
void ForceUpdateAuraDuration ()
void SendAuraDuration ()
void SendAuraDurationToCaster (Player *caster, uint32 slot=MAX_AURAS)
void SendAuraDurationToCasterNeedUpdate (Player *caster)
void SetAura (uint32 slot, bool remove)
void SetAuraFlag (uint32 slot, bool add)
void SetAuraLevel (uint32 slot, uint32 level)
void SetCreationDelayFlag ()
bool HasAuraType (AuraType type)
bool IsProcReady (TimePoint const &now) const
void SetProcCooldown (std::chrono::milliseconds cooldown, TimePoint const &now)
bool IsReducedProcChancePast60 ()
void SetReducedProcChancePast60 ()
AuraScript * GetAuraScript () const
void OnHolderInit (WorldObject *caster)
void OnDispel (Unit *dispeller, uint32 dispellingSpellId, uint32 originalStacks)
void PresetAuraStacks (uint32 stacks)
Data Fields
Aura * m_auras [MAX_EFFECT_INDEX]
Private Member Functions
void UpdateAuraApplication ()
void ClearExtraAuraInfo (Unit *caster)
void UpdateHeartbeatResist (uint32 diff)
Private Attributes
SpellEntry const * m_spellProto
Unit * m_target
ObjectGuid m_casterGuid
ObjectGuid m_castItemGuid
time_t m_applyTime
uint32 m_applyMSTime
SpellEntry const * m_triggeredBy
SpellAuraHolderState m_spellAuraHolderState
uint8 m_auraSlot
uint8 m_auraLevel
uint32 m_procCharges
uint32 m_stackAmount
int32 m_maxDuration
int32 m_duration
int32 m_timeCla
float m_heartbeatResistChance
int32 m_heartbeatResistInterval
int32 m_heartbeatResistTimer
AuraRemoveMode m_removeMode: 8
DiminishingGroup m_AuraDRGroup: 8
TrackedAuraType m_trackedAuraType: 8
bool m_permanent: 1
bool m_isPassive: 1
bool m_isDeathPersist: 1
bool m_isRemovedOnShapeLost: 1
bool m_deleted: 1
bool m_skipUpdate: 1
TimePoint m_procCooldown
bool m_reducedProcChancePast60
AuraScript * m_auraScript
Detailed Description
Definition at line 93 of file SpellAuras.h.
Constructor & Destructor Documentation
SpellAuraHolder()
SpellAuraHolder::SpellAuraHolder (SpellEntry const * spellproto, Unit * target, WorldObject * caster, Item * castItem, SpellEntry const * triggeredBy)
Definition at line 7796 of file SpellAuras.cpp.
References CalculateSpellDuration(), SpellEntry::DurationIndex, GetCasterGuid(), Map::GetCurrentMSTime(), GetId(), WorldObject::GetMap(), Object::GetObjectGuid(), WorldObject::GetSpellModOwner(), SpellEntry::Id, IsDeathPersistentSpell(), IsPassiveSpell(), IsRemovedOnShapeshiftLost(), Object::isType(), SQLStorage::LookupEntry(), m_applyMSTime, m_applyTime, m_auras, m_auraScript, m_casterGuid, m_duration, m_isDeathPersist, m_isPassive, m_isRemovedOnShapeLost, m_maxDuration, m_permanent, m_procCharges, m_spellProto, m_stackAmount, m_trackedAuraType, MANGOS_ASSERT, OnHolderInit(), SpellEntry::procCharges, SPELLMOD_CHARGES, sSpellMgr, sSpellTemplate, SpellEntry::StackAmount, TRACK_AURA_TYPE_NOT_TRACKED, TRACK_AURA_TYPE_SINGLE_TARGET, and TYPEMASK_UNIT.
~SpellAuraHolder()
SpellAuraHolder::~SpellAuraHolder ()
Definition at line 8417 of file SpellAuras.cpp.
References m_auras, and MAX_EFFECT_INDEX.
Member Function Documentation
_AddSpellAuraHolder()
void SpellAuraHolder::_AddSpellAuraHolder ()
Definition at line 7877 of file SpellAuras.cpp.
References Unit::ApplyDiminishingAura(), AURA_INTERRUPT_FLAG_STANDING_CANCELS, AURA_STATE_CONFLAGRATE, AURA_STATE_DEADLY_POISON, AURA_STATE_FAERIE_FIRE, AURA_STATE_JUDGEMENT, AURA_STATE_SWIFTMEND, SpellEntry::AuraInterruptFlags, CONFIG_UINT32_MAX_PLAYER_LEVEL, DIMINISHING_NONE, GetAuraSlot(), Object::GetByteValue(), GetCaster(), getDiminishGroup(), GetId(), Unit::GetLevel(), Unit::GetSpellAuraHolderMap(), GetSpellProto(), Object::GetUInt32Value(), SpellEntry::HasAttribute(), SpellEntry::IsFitToFamily(), IsNeedVisibleSlot(), IsPositive(), IsSealSpell(), Unit::IsSitState(), m_spellProto, m_target, MAX_AURAS, Unit::ModifyAuraState(), NULL_AURA_SLOT, SetAura(), SetAuraFlag(), SetAuraLevel(), SetAuraSlot(), Object::SetFlag(), Unit::SetStandState(), SPELL_ATTR_EX_PREVENTS_ANIM, SPELL_ATTR_SS_PREVENT_INVIS, SPELLFAMILY_DRUID, SPELLFAMILY_ROGUE, SPELLFAMILY_WARLOCK, sWorld, UNIT_FIELD_AURA, UNIT_FIELD_BYTES_2, UNIT_FIELD_FLAGS, UNIT_FLAG_PREVENT_ANIM, UNIT_STAND_STATE_SIT, UpdateAuraApplication(), UpdateAuraDuration(), and Unit::UpdateAuraForGroup().
Referenced by Unit::AddSpellAuraHolder().
_RemoveSpellAuraHolder()
void SpellAuraHolder::_RemoveSpellAuraHolder ()
Definition at line 7992 of file SpellAuras.cpp.
References WorldObject::AddCooldown(), Unit::ApplyDiminishingAura(), AURA_REMOVE_BY_DEFAULT, AURA_REMOVE_BY_DELETE, AURA_REMOVE_BY_STACK, AURA_STATE_CONFLAGRATE, AURA_STATE_DEADLY_POISON, AURA_STATE_FAERIE_FIRE, AURA_STATE_JUDGEMENT, AURA_STATE_SWIFTMEND, CleanupTriggeredSpells(), ClearExtraAuraInfo(), CONFIG_UINT32_MAX_PLAYER_LEVEL, DIMINISHING_NONE, GetAuraSlot(), GetCaster(), GetCastItemGuid(), getDiminishGroup(), Unit::GetDynObject(), GetId(), Unit::GetLevel(), GetSpellProto(), Object::GetTypeId(), Object::GetUInt32Value(), SpellEntry::HasAttribute(), Unit::HasAuraWithCondition(), SpellEntry::IsFitToFamilyMask(), IsPersistent(), IsSealSpell(), m_procCharges, m_removeMode, m_spellProto, m_stackAmount, m_target, MAX_AURAS, Unit::ModifyAuraState(), Object::RemoveFlag(), SetAura(), SetAuraFlag(), SetAuraLevel(), SPELL_ATTR_COOLDOWN_ON_EVENT, SPELL_ATTR_EX_PREVENTS_ANIM, SPELL_ATTR_SS_PREVENT_INVIS, SPELLFAMILY_DRUID, SPELLFAMILY_PALADIN, SPELLFAMILY_ROGUE, SPELLFAMILY_WARLOCK, SpellEntry::SpellFamilyFlags, SpellEntry::SpellFamilyName, sWorld, TYPEID_PLAYER, UNIT_FIELD_AURA, UNIT_FIELD_FLAGS, UNIT_FLAG_PREVENT_ANIM, UpdateAuraApplication(), and Unit::UpdateAuraForGroup().
Referenced by Unit::RemoveSpellAuraHolder().
AddAura()
void SpellAuraHolder::AddAura (Aura * aura, SpellEffectIndex index)
Definition at line 7860 of file SpellAuras.cpp.
References m_auras.
Referenced by Player::_LoadAuras(), Pet::_LoadAuras(), go_aura_generator::CheckAndApplyAura(), Spell::EffectApplyAreaAura(), Spell::EffectApplyAura(), ChatHandler::HandleAuraCommand(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), Unit::RemoveAurasDueToSpellBySteal(), AreaAura::Update(), go_aura_generator_000AI::UpdateAI(), and MaNGOS::DynamicObjectUpdater::VisitHelper().
ApplyAuraModifiers()
void SpellAuraHolder::ApplyAuraModifiers (bool apply, bool real = false)
Definition at line 7870 of file SpellAuras.cpp.
References ByteConverter::apply(), GetAuraByEffectIndex(), IsDeleted(), and MAX_EFFECT_INDEX.
Referenced by Unit::AddSpellAuraHolder().
CleanupTriggeredSpells()
void SpellAuraHolder::CleanupTriggeredSpells ()
Definition at line 8104 of file SpellAuras.cpp.
References SpellEntry::EffectAmplitude, SpellEntry::EffectApplyAuraName, SpellEntry::EffectTriggerSpell, GetSpellDuration(), SQLStorage::LookupEntry(), m_spellProto, m_target, MAX_EFFECT_INDEX, Unit::RemoveAurasDueToSpell(), SPELL_AURA_PERIODIC_TRIGGER_SPELL, and sSpellTemplate.
Referenced by _RemoveSpellAuraHolder().
ClearExtraAuraInfo()
void SpellAuraHolder::ClearExtraAuraInfo (Unit * caster) private
Definition at line 8750 of file SpellAuras.cpp.
References Object::GetPackGUID(), GetSpellProto(), Object::GetTypeId(), m_target, SMSG_CLEAR_EXTRA_AURA_INFO, and TYPEID_PLAYER.
Referenced by _RemoveSpellAuraHolder(), and SetStackAmount().
DropAuraCharge()
bool SpellAuraHolder::DropAuraCharge ()
Definition at line 8513 of file SpellAuras.cpp.
References GetCaster(), GetCasterGuid(), Object::GetObjectGuid(), SpellEntry::Id, IsAreaAura(), m_auras, m_procCharges, m_spellProto, m_target, MAX_EFFECT_INDEX, and UpdateAuraApplication().
Referenced by Unit::ProcDamageAndSpellFor().
ForceUpdateAuraDuration()
void SpellAuraHolder::ForceUpdateAuraDuration ()
Definition at line 8788 of file SpellAuras.cpp.
References GetAuraSlot(), GetCaster(), GetSpellProto(), Object::IsPlayer(), MAX_AURAS, SendAuraDuration(), SendAuraDurationToCasterNeedUpdate(), and SPELL_ATTR_EX5_DO_NOT_DISPLAY_DURATION.
Referenced by Unit::DelaySpellAuraHolder().
GetAuraApplyMSTime()
uint32 SpellAuraHolder::GetAuraApplyMSTime () const inline
Definition at line 175 of file SpellAuras.h.
References m_applyMSTime.
GetAuraApplyTime()
uint32 SpellAuraHolder::GetAuraApplyTime () const inline
Definition at line 174 of file SpellAuras.h.
References m_applyTime.
Referenced by Player::DuelComplete().
GetAuraByEffectIndex()
Aura* SpellAuraHolder::GetAuraByEffectIndex (SpellEffectIndex index) const inline
Definition at line 115 of file SpellAuras.h.
References m_auras.
Referenced by Pet::_SaveAuras(), Player::_SaveAuras(), Unit::AddSpellAuraHolder(), ApplyAuraModifiers(), ChatHandler::HandleListAurasCommand(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), IsSimilarExistingAuraStronger(), Drink::OnApply(), Drink::OnPeriodicDummy(), Unit::ProcDamageAndSpellFor(), Unit::RemoveAurasDueToSpellBySteal(), Unit::RemoveSingleAuraFromSpellAuraHolder(), and MaNGOS::DynamicObjectUpdater::VisitHelper().
GetAuraCharges()
uint32 SpellAuraHolder::GetAuraCharges () const inline
Definition at line 166 of file SpellAuras.h.
References m_procCharges.
Referenced by Pet::_SaveAuras(), Player::_SaveAuras(), Unit::HandleDummyAuraProc(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), Unit::ProcDamageAndSpellFor(), and Unit::RemoveAurasDueToSpellBySteal().
GetAuraDuration()
int32 SpellAuraHolder::GetAuraDuration () const inline
Definition at line 157 of file SpellAuras.h.
References m_duration.
Referenced by Pet::_SaveAuras(), Player::_SaveAuras(), Unit::_UpdateSpells(), Unit::DelaySpellAuraHolder(), Spell::EffectDummy(), Aura::GetAuraDuration(), Unit::RemoveAurasDueToSpellBySteal(), SendAuraDuration(), SendAuraDurationToCaster(), SendAuraDurationToCasterNeedUpdate(), and MaNGOS::DynamicObjectUpdater::VisitHelper().
GetAuraLevel()
uint8 SpellAuraHolder::GetAuraLevel () const inline
Definition at line 164 of file SpellAuras.h.
References m_auraLevel.
GetAuraMaxDuration()
int32 SpellAuraHolder::GetAuraMaxDuration () const inline
Definition at line 155 of file SpellAuras.h.
References m_maxDuration.
Referenced by Pet::_SaveAuras(), Player::_SaveAuras(), Spell::DoSpellHitOnUnit(), Aura::GetAuraMaxDuration(), Player::GetMirrorTimerBuff(), RefreshHolder(), SendAuraDuration(), SendAuraDurationToCaster(), and SendAuraDurationToCasterNeedUpdate().
GetAuraScript()
AuraScript* SpellAuraHolder::GetAuraScript () const inline
Definition at line 214 of file SpellAuras.h.
References m_auraScript.
Referenced by Aura::GetAuraScript(), OnDispel(), and OnHolderInit().
GetAuraSlot()
uint8 SpellAuraHolder::GetAuraSlot () const inline
Definition at line 162 of file SpellAuras.h.
References m_auraSlot.
Referenced by _AddSpellAuraHolder(), _RemoveSpellAuraHolder(), ForceUpdateAuraDuration(), SendAuraDuration(), Player::SendAuraDurationsForTarget(), Player::SendAuraDurationsOnLogin(), SendAuraDurationToCaster(), SendAuraDurationToCasterNeedUpdate(), Player::SendExtraAuraDurationsOnLogin(), and UpdateAuraDuration().
GetCaster()
Unit * SpellAuraHolder::GetCaster () const
Definition at line 8215 of file SpellAuras.cpp.
References WorldObject::GetMap(), Object::GetObjectGuid(), Map::GetUnit(), ObjectGuid::IsGameObject(), Object::IsInWorld(), m_casterGuid, and m_target.
Referenced by _AddSpellAuraHolder(), _RemoveSpellAuraHolder(), Unit::AddSpellAuraHolder(), DropAuraCharge(), ForceUpdateAuraDuration(), Aura::GetCaster(), HandleSpellSpecificBoosts(), Spell::ProcessDispelList(), Unit::RemoveSpellAuraHolder(), SetStackAmount(), UnregisterAndCleanupTrackedAuras(), and UpdateAuraDuration().
GetCasterGuid()
ObjectGuid const& SpellAuraHolder::GetCasterGuid () const inline
Definition at line 123 of file SpellAuras.h.
References m_casterGuid.
Referenced by Pet::_SaveAuras(), Player::_SaveAuras(), Unit::AddSpellAuraHolder(), go_aura_generator::ChangeState(), go_aura_generator::CheckAndApplyAura(), Spell::CheckCast(), Unit::DelaySpellAuraHolder(), DropAuraCharge(), Player::DuelComplete(), Spell::EvaluateResultLists(), Aura::GetCasterGuid(), WorldSession::HandleCancelAuraOpcode(), ChatHandler::HandleListAurasCommand(), HandleSpellSpecificBoosts(), Unit::IsTriggeredAtSpellProcEvent(), IsWeaponBuffCoexistableWith(), UnstableAffliction::OnDispel(), Spell::ProcessDispelList(), Unit::RemoveAllGroupBuffsFromCaster(), Unit::RemoveAuraHolderDueToSpellByDispel(), Unit::RemoveAurasOnCast(), Player::RemoveItemDependentAurasAndCasts(), Unit::RemoveNoStackAurasDueToAuraHolder(), Player::SendAuraDurationsForTarget(), SpellAuraHolder(), Update(), and go_aura_generator_000AI::UpdateAI().
GetCastItemGuid()
ObjectGuid const& SpellAuraHolder::GetCastItemGuid () const inline
Definition at line 125 of file SpellAuras.h.
References m_castItemGuid.
Referenced by _RemoveSpellAuraHolder(), Pet::_SaveAuras(), Player::_SaveAuras(), Aura::GetCastItemGuid(), IsWeaponBuffCoexistableWith(), and Unit::RemoveNoStackAurasDueToAuraHolder().
getDiminishGroup()
DiminishingGroup SpellAuraHolder::getDiminishGroup () const inline
Definition at line 109 of file SpellAuras.h.
References m_AuraDRGroup.
Referenced by _AddSpellAuraHolder(), _RemoveSpellAuraHolder(), and Unit::RemoveNoStackAurasDueToAuraHolder().
GetId()
uint32 SpellAuraHolder::GetId (void) const inline
Definition at line 118 of file SpellAuras.h.
References SpellEntry::Id, and m_spellProto.
Referenced by _AddSpellAuraHolder(), _RemoveSpellAuraHolder(), Pet::_SaveAuras(), Player::_SaveAuras(), Unit::_UpdateSpells(), Unit::AddSpellAuraHolder(), Player::DuelComplete(), Spell::EvaluateResultLists(), ChatHandler::HandleListAurasCommand(), HandleSpellSpecificBoosts(), Unit::IsTriggeredAtSpellProcEvent(), IsWeaponBuffCoexistableWith(), Spell::ProcessDispelList(), Player::RemoveItemDependentAurasAndCasts(), Unit::RemoveNoStackAurasDueToAuraHolder(), Unit::RemoveSpellAuraHolder(), SendAuraDurationToCaster(), SendAuraDurationToCasterNeedUpdate(), SetAura(), SpellAuraHolder(), and Update().
GetSpellProto()
SpellEntry const* SpellAuraHolder::GetSpellProto () const inline
Definition at line 119 of file SpellAuras.h.
References m_spellProto.
Referenced by _AddSpellAuraHolder(), Player::_LoadAuras(), _RemoveSpellAuraHolder(), Pet::_SaveAuras(), Unit::AddSpellAuraHolder(), Aura::Aura(), Spell::CheckCast(), ClearExtraAuraInfo(), DynamicObject::Delay(), Spell::EffectEnchantHeldItem(), Spell::EffectStealBeneficialBuff(), ForceUpdateAuraDuration(), UnitConditionMgr::getConditionValue(), PlayerbotClassAI::GetDispelTarget(), Aura::GetId(), Aura::GetMiscBValue(), Aura::GetMiscValue(), Aura::GetSpellProto(), WorldSession::HandleCancelAuraOpcode(), ChatHandler::HandleListAurasCommand(), Unit::HandlePeriodicAuraProc(), HandleSpellSpecificBoosts(), Unit::HasNegativeAuraWithInterruptFlag(), IsDispellableByMask(), IsSaveToDbHolder(), IsSimilarExistingAuraStronger(), PlayerbotHunterAI::IsTargetEnraged(), Unit::IsTriggeredAtSpellProcEvent(), IsWeaponBuffCoexistableWith(), UnstableAffliction::OnDispel(), Unit::ProcDamageAndSpellFor(), Spell::ProcessDispelList(), Unit::RemoveAllGroupBuffsFromCaster(), Unit::RemoveAurasDueToSpellBySteal(), Unit::RemoveAurasOnCast(), Player::RemoveItemDependentAurasAndCasts(), Unit::RemoveNoStackAurasDueToAuraHolder(), Unit::RemoveSpellAuraHolder(), SetAuraMaxDuration(), SetStackAmount(), UnregisterAndCleanupTrackedAuras(), Update(), and UpdateAuraDuration().
GetStackAmount()
uint32 SpellAuraHolder::GetStackAmount () const inline
Definition at line 111 of file SpellAuras.h.
References m_stackAmount.
Referenced by Pet::_SaveAuras(), Player::_SaveAuras(), Unit::AddSpellAuraHolder(), CreatureEventAI::CheckEvent(), PlayerbotMageAI::DoNextCombatManeuverPVE(), PlayerbotWarriorAI::DoNextCombatManeuverPVE(), Spell::EffectDispel(), Spell::EffectStealBeneficialBuff(), Aura::GetStackAmount(), Unit::HandleDummyAuraProc(), ChatHandler::HandleListAurasCommand(), Unit::HandlePeriodicAuraProc(), and Unit::RemoveAuraHolderDueToSpellByDispel().
GetState()
SpellAuraHolderState SpellAuraHolder::GetState () const inline
Definition at line 120 of file SpellAuras.h.
References m_spellAuraHolderState.
Referenced by Unit::ProcDamageAndSpell(), and Unit::ProcDamageAndSpellFor().
GetTarget()
Unit* SpellAuraHolder::GetTarget () const inline
Definition at line 127 of file SpellAuras.h.
References m_target.
Referenced by Unit::AddSpellAuraHolder(), Aura::GetTarget(), Aura::GetTriggerTarget(), IsDispellableByMask(), Unit::IsTriggeredAtSpellProcEvent(), DarkFiendAura::OnDispel(), InhibitMagic::OnHolderInit(), SetStackAmount(), Update(), and UpdateHeartbeatResist().
GetTrackedAuraType()
TrackedAuraType SpellAuraHolder::GetTrackedAuraType () const inline
Definition at line 151 of file SpellAuras.h.
References m_trackedAuraType.
Referenced by Player::_LoadAuras(), Pet::_LoadAuras(), Unit::AddSpellAuraHolder(), IsSaveToDbHolder(), and UnregisterAndCleanupTrackedAuras().
GetTriggeredBy()
SpellEntry const* SpellAuraHolder::GetTriggeredBy () const inline
Definition at line 116 of file SpellAuras.h.
References m_triggeredBy.
Referenced by Unit::RemoveNoStackAurasDueToAuraHolder().
HandleSpellSpecificBoosts()
void SpellAuraHolder::HandleSpellSpecificBoosts (bool apply)
Definition at line 8294 of file SpellAuras.cpp.
References ByteConverter::apply(), Unit::CastSpell(), SpellEntry::EffectImplicitTargetA, Unit::GetAurasByType(), GetCaster(), GetCasterGuid(), Unit::getHostileRefManager(), GetId(), Object::GetObjectGuid(), GetSpellProto(), HostileRefManager::GetThreatRedirectionTarget(), SQLStorage::LookupEntry(), m_target, MECHANIC_BLEED, MECHANIC_POLYMORPH, Unit::RemoveAurasByCasterSpell(), HostileRefManager::ResetThreatRedirection(), SPELL_AURA_PERIODIC_DAMAGE, SPELLFAMILY_GENERIC, SPELLFAMILY_HUNTER, SPELLFAMILY_MAGE, SPELLFAMILY_WARRIOR, sSpellTemplate, TARGET_UNIT, TARGET_UNIT_ENEMY, and TRIGGERED_OLD_TRIGGERED.
Referenced by Unit::AddSpellAuraHolder(), and Unit::RemoveSpellAuraHolder().
HasAuraType()
bool SpellAuraHolder::HasAuraType (AuraType type)
Definition at line 8726 of file SpellAuras.cpp.
References SpellEntry::EffectApplyAuraName, m_auras, and m_spellProto.
Referenced by Player::SendExtraAuraDurationsOnLogin().
HasMechanic()
bool SpellAuraHolder::HasMechanic (uint32 mechanic) const
Definition at line 8551 of file SpellAuras.cpp.
References SpellEntry::EffectMechanic, m_auras, m_spellProto, MAX_EFFECT_INDEX, and SpellEntry::Mechanic.
Referenced by UnitConditionMgr::getConditionValue().
HasMechanicMask()
bool SpellAuraHolder::HasMechanicMask (uint32 mechanicMask) const
Definition at line 8562 of file SpellAuras.cpp.
References SpellEntry::EffectMechanic, m_auras, m_spellProto, MAX_EFFECT_INDEX, and SpellEntry::Mechanic.
Referenced by Unit::HasMechanicMaskOrDispelMaskAura().
HasModifier()
bool SpellAuraHolder::HasModifier (const uint64 & modId) const
Definition at line 8542 of file SpellAuras.cpp.
References m_auras, and MAX_EFFECT_INDEX.
IsAreaAura()
bool SpellAuraHolder::IsAreaAura () const
Definition at line 8600 of file SpellAuras.cpp.
References m_auras.
Referenced by Unit::AddSpellAuraHolder(), and DropAuraCharge().
IsCharm()
bool SpellAuraHolder::IsCharm () const
Definition at line 8668 of file SpellAuras.cpp.
References IsCharmAura(), m_auras, and m_spellProto.
Referenced by IsDispellableByMask().
IsDeathPersistent()
bool SpellAuraHolder::IsDeathPersistent () const inline
Definition at line 133 of file SpellAuras.h.
References m_isDeathPersist.
IsDeleted()
bool SpellAuraHolder::IsDeleted () const inline
Definition at line 140 of file SpellAuras.h.
References m_deleted.
Referenced by Unit::AddSpellAuraHolder(), ApplyAuraModifiers(), Unit::ProcDamageAndSpellFor(), Unit::RemoveSpellAuraHolder(), and Update().
IsDispellableByMask()
bool SpellAuraHolder::IsDispellableByMask (uint32 dispelMask, Unit const * caster, SpellEntry const * spellInfo) const
Definition at line 8573 of file SpellAuras.cpp.
References Unit::CanAssistSpell(), DISPEL_MAGIC, GetSpellProto(), GetTarget(), IsCharm(), and IsPositive().
Referenced by Spell::EffectDispel(), and Unit::HasMechanicMaskOrDispelMaskAura().
IsEmptyHolder()
bool SpellAuraHolder::IsEmptyHolder () const
Definition at line 8618 of file SpellAuras.cpp.
References m_auras.
Referenced by Player::_LoadAuras(), Pet::_LoadAuras(), and Spell::DoSpellHitOnUnit().
IsNeedVisibleSlot()
bool SpellAuraHolder::IsNeedVisibleSlot (Unit const * caster) const
Definition at line 8264 of file SpellAuras.cpp.
References SpellEntry::Effect, Aura::GetModifier(), Object::GetTypeId(), Modifier::m_auraname, m_auras, m_isPassive, m_spellProto, m_target, MAX_EFFECT_INDEX, SPELL_AURA_NONE, SPELL_EFFECT_APPLY_AREA_AURA_ENEMY, SPELL_EFFECT_APPLY_AREA_AURA_FRIEND, SPELL_EFFECT_APPLY_AREA_AURA_OWNER, SPELL_EFFECT_APPLY_AREA_AURA_PARTY, SPELL_EFFECT_APPLY_AREA_AURA_PET, and TYPEID_UNIT.
Referenced by _AddSpellAuraHolder().
IsPassive()
bool SpellAuraHolder::IsPassive () const inline
Definition at line 132 of file SpellAuras.h.
References m_isPassive.
Referenced by Unit::_UpdateSpells(), Unit::AddSpellAuraHolder(), Spell::EffectStealBeneficialBuff(), ChatHandler::HandleListAurasCommand(), IsSaveToDbHolder(), Player::RemoveItemDependentAurasAndCasts(), Player::SendAuraDurationsForTarget(), and SetAuraMaxDuration().
IsPermanent()
bool SpellAuraHolder::IsPermanent () const inline
Definition at line 130 of file SpellAuras.h.
References m_permanent.
Referenced by Unit::_UpdateSpells(), and IsSaveToDbHolder().
IsPersistent()
bool SpellAuraHolder::IsPersistent () const
Definition at line 8591 of file SpellAuras.cpp.
References m_auras.
Referenced by _RemoveSpellAuraHolder(), and Unit::AddSpellAuraHolder().
IsPositive()
bool SpellAuraHolder::IsPositive () const
Definition at line 8609 of file SpellAuras.cpp.
References m_auras.
Referenced by _AddSpellAuraHolder(), Spell::DoSpellHitOnUnit(), Player::DuelComplete(), Spell::EffectStealBeneficialBuff(), UnitConditionMgr::getConditionValue(), PlayerbotClassAI::GetDispelTarget(), WorldSession::HandleCancelAuraOpcode(), Unit::HasNegativeAuraWithInterruptFlag(), IsDispellableByMask(), IsWeaponBuffCoexistableWith(), and SetAuraFlag().
IsProcReady()
bool SpellAuraHolder::IsProcReady (TimePoint const & now) const
Definition at line 8838 of file SpellAuras.cpp.
References m_procCooldown.
Referenced by Unit::HandleDummyAuraProc(), Unit::HandleProcTriggerDamageAuraProc(), CheatDeathRogue::OnAbsorb(), and Unit::TriggerProccedSpell().
IsReducedProcChancePast60()
bool SpellAuraHolder::IsReducedProcChancePast60 () inline
Definition at line 210 of file SpellAuras.h.
References m_reducedProcChancePast60.
Referenced by Unit::IsTriggeredAtSpellProcEvent().
IsRemovedOnShapeLost()
bool SpellAuraHolder::IsRemovedOnShapeLost () const inline
Definition at line 139 of file SpellAuras.h.
References m_isRemovedOnShapeLost.
IsSaveToDbHolder()
bool SpellAuraHolder::IsSaveToDbHolder () const
Definition at line 8626 of file SpellAuras.cpp.
References AURA_INTERRUPT_FLAG_LEAVE_WORLD, SpellEntry::AuraInterruptFlags, GetSpellProto(), GetTrackedAuraType(), SpellEntry::Id, IsChanneledSpell(), IsItemAura(), IsPassive(), IsPermanent(), m_spellProto, and TRACK_AURA_TYPE_SINGLE_TARGET.
Referenced by Pet::_SaveAuras(), and Player::_SaveAuras().
IsWeaponBuffCoexistableWith()
bool SpellAuraHolder::IsWeaponBuffCoexistableWith (SpellAuraHolder const * ref) const
Definition at line 8229 of file SpellAuras.cpp.
References EQUIPMENT_SLOT_MAINHAND, EQUIPMENT_SLOT_OFFHAND, GetCasterGuid(), GetCastItemGuid(), GetId(), Object::GetObjectGuid(), Item::GetSlot(), GetSpellProto(), Object::GetTypeId(), Item::IsEquipped(), IsPositive(), m_target, SPELLFAMILY_GENERIC, and TYPEID_PLAYER.
Referenced by Unit::AddSpellAuraHolder().
LoginAuraDuration()
void SpellAuraHolder::LoginAuraDuration ()
Definition at line 8780 of file SpellAuras.cpp.
References Object::GetObjectGuid(), m_casterGuid, m_target, SendAuraDuration(), and SendAuraDurationToCaster().
Referenced by Player::SendAuraDurationsOnLogin().
ModStackAmount()
bool SpellAuraHolder::ModStackAmount (int32 num, Unit * newCaster)
Definition at line 8132 of file SpellAuras.cpp.
References m_spellProto, m_stackAmount, SetStackAmount(), and SpellEntry::StackAmount.
Referenced by Unit::AddSpellAuraHolder(), Unit::HandlePeriodicAuraProc(), Unit::RemoveAuraHolderDueToSpellByDispel(), and Unit::RemoveAurasDueToSpellBySteal().
OnDispel()
void SpellAuraHolder::OnDispel (Unit * dispeller, uint32 dispellingSpellId, uint32 originalStacks)
Definition at line 8912 of file SpellAuras.cpp.
References GetAuraScript().
Referenced by Unit::RemoveAuraHolderDueToSpellByDispel().
OnHolderInit()
void SpellAuraHolder::OnHolderInit (WorldObject * caster)
Definition at line 8906 of file SpellAuras.cpp.
References GetAuraScript().
Referenced by SetStackAmount(), and SpellAuraHolder().
PresetAuraStacks()
void SpellAuraHolder::PresetAuraStacks (uint32 stacks) inline
Definition at line 219 of file SpellAuras.h.
References m_stackAmount.
Referenced by InhibitMagic::OnHolderInit().
RefreshHolder()
void SpellAuraHolder::RefreshHolder ()
Definition at line 8480 of file SpellAuras.cpp.
References GetAuraMaxDuration(), SetAuraDuration(), and UpdateAuraDuration().
Referenced by Devastate::OnEffectExecute(), and SetStackAmount().
RemoveAura()
void SpellAuraHolder::RemoveAura (SpellEffectIndex index)
Definition at line 7865 of file SpellAuras.cpp.
References m_auras.
Referenced by Unit::RemoveAura().
ResetSpellModCharges()
void SpellAuraHolder::ResetSpellModCharges ()
Definition at line 8534 of file SpellAuras.cpp.
References m_auras, m_procCharges, and MAX_EFFECT_INDEX.
SendAuraDuration()
void SpellAuraHolder::SendAuraDuration ()
Definition at line 8804 of file SpellAuras.cpp.
References GetAuraDuration(), GetAuraMaxDuration(), GetAuraSlot(), Object::IsPlayer(), m_target, and SMSG_UPDATE_AURA_DURATION.
Referenced by ForceUpdateAuraDuration(), LoginAuraDuration(), and UpdateAuraDuration().
SendAuraDurationToCaster()
void SpellAuraHolder::SendAuraDurationToCaster (Player * caster, uint32 slot = MAX_AURAS)
Definition at line 8815 of file SpellAuras.cpp.
References GetAuraDuration(), GetAuraMaxDuration(), GetAuraSlot(), GetId(), Object::GetPackGUID(), m_target, MAX_AURAS, Player::SendDirectMessage(), and SMSG_SET_EXTRA_AURA_INFO.
Referenced by LoginAuraDuration(), Player::SendAuraDurationsForTarget(), and UpdateAuraDuration().
SendAuraDurationToCasterNeedUpdate()
void SpellAuraHolder::SendAuraDurationToCasterNeedUpdate (Player * caster)
Definition at line 8827 of file SpellAuras.cpp.
References GetAuraDuration(), GetAuraMaxDuration(), GetAuraSlot(), GetId(), Object::GetPackGUID(), Player::GetSession(), m_target, WorldSession::SendPacket(), and SMSG_SET_EXTRA_AURA_INFO_NEED_UPDATE.
Referenced by ForceUpdateAuraDuration().
SetAura()
void SpellAuraHolder::SetAura (uint32 slot, bool remove) inline
Definition at line 199 of file SpellAuras.h.
References GetId(), m_target, Object::SetUInt32Value(), and UNIT_FIELD_AURA.
Referenced by _AddSpellAuraHolder(), and _RemoveSpellAuraHolder().
SetAuraCharges()
void SpellAuraHolder::SetAuraCharges (uint32 charges, bool update = true)
Definition at line 8498 of file SpellAuras.cpp.
References m_auras, m_procCharges, MAX_EFFECT_INDEX, and UpdateAuraApplication().
Referenced by Aura::HandleAddModifier(), Aura::HandleAuraProcTriggerSpell(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), and Unit::RemoveAurasDueToSpellBySteal().
SetAuraDuration()
void SpellAuraHolder::SetAuraDuration (int32 duration) inline
Definition at line 158 of file SpellAuras.h.
References m_duration.
Referenced by Unit::DelaySpellAuraHolder(), Spell::DoSpellHitOnUnit(), Spell::EffectDummy(), ForceOfNatureSummon::OnHolderInit(), Spell::PreCastCheck(), RefreshHolder(), Unit::RemoveAurasDueToSpellBySteal(), SetLoadedState(), AreaAura::Update(), and MaNGOS::DynamicObjectUpdater::VisitHelper().
SetAuraFlag()
void SpellAuraHolder::SetAuraFlag (uint32 slot, bool add)
Definition at line 8691 of file SpellAuras.cpp.
References AFLAG_CANCELABLE, AFLAG_MASK_ALL, AFLAG_NONE, AFLAG_NOT_CANCELABLE, Object::GetUInt32Value(), SpellEntry::HasAttribute(), IsPositive(), m_auras, m_spellProto, m_target, MAX_EFFECT_INDEX, Object::SetUInt32Value(), SPELL_ATTR_NO_AURA_CANCEL, and UNIT_FIELD_AURAFLAGS.
Referenced by _AddSpellAuraHolder(), and _RemoveSpellAuraHolder().
SetAuraLevel() [1/2]
void SpellAuraHolder::SetAuraLevel (uint32 slot, uint32 level)
Definition at line 8711 of file SpellAuras.cpp.
References Object::GetUInt32Value(), m_target, Object::SetUInt32Value(), and UNIT_FIELD_AURALEVELS.
SetAuraLevel() [2/2]
void SpellAuraHolder::SetAuraLevel (uint8 level) inline
Definition at line 165 of file SpellAuras.h.
References m_auraLevel.
Referenced by _AddSpellAuraHolder(), and _RemoveSpellAuraHolder().
SetAuraMaxDuration()
void SpellAuraHolder::SetAuraMaxDuration (int32 duration)
Definition at line 8486 of file SpellAuras.cpp.
References GetSpellProto(), IsPassive(), m_maxDuration, SetPermanent(), and SPELL_ATTR_EX5_DO_NOT_DISPLAY_DURATION.
Referenced by Spell::DoSpellHitOnUnit(), Spell::EffectDummy(), Unit::RemoveAurasDueToSpellBySteal(), and SetLoadedState().
SetAuraSlot()
void SpellAuraHolder::SetAuraSlot (uint8 slot) inline
Definition at line 163 of file SpellAuras.h.
References m_auraSlot.
Referenced by _AddSpellAuraHolder().
SetCasterGuid()
void SpellAuraHolder::SetCasterGuid (ObjectGuid guid) inline
Definition at line 124 of file SpellAuras.h.
References m_casterGuid.
SetCreationDelayFlag()
void SpellAuraHolder::SetCreationDelayFlag ()
Definition at line 8721 of file SpellAuras.cpp.
References m_skipUpdate.
Referenced by Unit::AddSpellAuraHolder().
SetDeleted()
void SpellAuraHolder::SetDeleted () inline
Definition at line 145 of file SpellAuras.h.
References m_deleted, m_spellAuraHolderState, and SPELLAURAHOLDER_STATE_REMOVING.
Referenced by Unit::RemoveSpellAuraHolder().
setDiminishGroup()
void SpellAuraHolder::setDiminishGroup (DiminishingGroup group) inline
Definition at line 108 of file SpellAuras.h.
References m_AuraDRGroup.
Referenced by Spell::DoSpellHitOnUnit().
SetHeartbeatResist()
void SpellAuraHolder::SetHeartbeatResist (uint32 chance, int32 originalDuration, uint32 drLevel)
Definition at line 8848 of file SpellAuras.cpp.
References m_heartbeatResistChance, m_heartbeatResistInterval, and m_heartbeatResistTimer.
Referenced by Spell::DoSpellHitOnUnit().
SetLoadedState()
void SpellAuraHolder::SetLoadedState (ObjectGuid const & casterGUID, ObjectGuid const & itemGUID, uint32 stackAmount, uint32 charges, int32 maxduration, int32 duration) inline
Definition at line 178 of file SpellAuras.h.
References m_casterGuid, m_castItemGuid, m_procCharges, m_stackAmount, SetAuraDuration(), and SetAuraMaxDuration().
Referenced by Player::_LoadAuras(), and Pet::_LoadAuras().
SetPermanent()
void SpellAuraHolder::SetPermanent (bool permanent) inline
Definition at line 131 of file SpellAuras.h.
References m_permanent.
Referenced by SetAuraMaxDuration().
SetProcCooldown()
void SpellAuraHolder::SetProcCooldown (std::chrono::milliseconds cooldown, TimePoint const & now)
Definition at line 8843 of file SpellAuras.cpp.
References m_procCooldown.
Referenced by Unit::HandleProcTriggerDamageAuraProc(), CheatDeathRogue::OnAuraDeathPrevention(), Unit::ProcDamageAndSpellFor(), and Unit::TriggerProccedSpell().
SetReducedProcChancePast60()
void SpellAuraHolder::SetReducedProcChancePast60 () inline
Definition at line 211 of file SpellAuras.h.
References m_reducedProcChancePast60.
Referenced by ReducedProcChancePast60::OnHolderInit().
SetRemoveMode()
void SpellAuraHolder::SetRemoveMode (AuraRemoveMode mode) inline
Definition at line 177 of file SpellAuras.h.
References m_removeMode.
Referenced by Unit::RemoveSpellAuraHolder().
SetStackAmount()
void SpellAuraHolder::SetStackAmount (uint32 stackAmount, Unit * newCaster)
Definition at line 8155 of file SpellAuras.cpp.
References AURA_REMOVE_BY_GAINED_STACK, ClearExtraAuraInfo(), GetCaster(), Object::GetObjectGuid(), GetSpellProto(), GetTarget(), SpellEntry::Id, IsAuraRemoveOnStacking(), m_auras, m_casterGuid, m_spellProto, m_stackAmount, m_target, OnHolderInit(), RefreshHolder(), and UpdateAuraApplication().
Referenced by ModStackAmount().
SetState()
void SpellAuraHolder::SetState (SpellAuraHolderState state) inline
Definition at line 121 of file SpellAuras.h.
References m_spellAuraHolderState.
Referenced by Player::_LoadAuras(), Pet::_LoadAuras(), Spell::DoAllEffectOnTarget(), ChatHandler::HandleAuraCommand(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), Unit::ProcDamageAndSpell(), Unit::RemoveAurasDueToSpellBySteal(), and AreaAura::Update().
SetTarget()
void SpellAuraHolder::SetTarget (Unit * target) inline
Definition at line 128 of file SpellAuras.h.
References m_target.
SetTrackedAuraType()
void SpellAuraHolder::SetTrackedAuraType (TrackedAuraType val) inline
Definition at line 152 of file SpellAuras.h.
References m_trackedAuraType.
Referenced by Player::_LoadAuras(), Pet::_LoadAuras(), and Unit::RemoveAurasDueToSpellBySteal().
UnregisterAndCleanupTrackedAuras()
void SpellAuraHolder::UnregisterAndCleanupTrackedAuras ()
Definition at line 8676 of file SpellAuras.cpp.
References GetCaster(), GetSpellProto(), GetTrackedAuraType(), m_trackedAuraType, TRACK_AURA_TYPE_NOT_TRACKED, and TRACK_AURA_TYPE_SINGLE_TARGET.
Referenced by Unit::RemoveSpellAuraHolder().
Update()
void SpellAuraHolder::Update (uint32 diff)
Definition at line 8424 of file SpellAuras.cpp.
References CURRENT_CHANNELED_SPELL, CURRENT_GENERIC_SPELL, Unit::FinishSpell(), GetCasterGuid(), GetId(), Unit::GetLevel(), GetSpellProto(), GetTarget(), IN_MILLISECONDS, IsDeleted(), m_applyMSTime, m_auras, m_duration, m_skipUpdate, m_timeCla, SpellEntry::manaPerSecond, SpellEntry::manaPerSecondPerLevel, Unit::ModifyHealth(), Unit::ModifyPower(), POWER_HEALTH, Unit::RemoveAurasDueToSpell(), SPELL_ATTR_EX2_NO_TARGET_PER_SECOND_COSTS, and UpdateHeartbeatResist().
Referenced by UpdateHolder().
UpdateAuraApplication()
void SpellAuraHolder::UpdateAuraApplication () private
Definition at line 8734 of file SpellAuras.cpp.
References Object::GetUInt32Value(), m_auraSlot, m_procCharges, m_stackAmount, m_target, MAX_AURAS, Object::SetUInt32Value(), and UNIT_FIELD_AURAAPPLICATIONS.
Referenced by _AddSpellAuraHolder(), _RemoveSpellAuraHolder(), DropAuraCharge(), SetAuraCharges(), and SetStackAmount().
UpdateAuraDuration()
void SpellAuraHolder::UpdateAuraDuration ()
Definition at line 8761 of file SpellAuras.cpp.
References GetAuraSlot(), GetCaster(), Player::GetSession(), GetSpellProto(), Object::IsPlayer(), m_target, MAX_AURAS, WorldSession::PlayerLoading(), SendAuraDuration(), SendAuraDurationToCaster(), and SPELL_ATTR_EX5_DO_NOT_DISPLAY_DURATION.
Referenced by _AddSpellAuraHolder(), Spell::EffectDummy(), RefreshHolder(), and MaNGOS::DynamicObjectUpdater::VisitHelper().
UpdateHeartbeatResist()
void SpellAuraHolder::UpdateHeartbeatResist (uint32 diff) private
Definition at line 8859 of file SpellAuras.cpp.
References AURA_REMOVE_BY_CANCEL, DEBUG_FILTER_LOG, GetTarget(), SpellEntry::Id, LOG_FILTER_COMBAT, m_heartbeatResistChance, m_heartbeatResistInterval, m_heartbeatResistTimer, m_spellProto, and roll_chance_f().
Referenced by Update().
UpdateHolder()
void SpellAuraHolder::UpdateHolder (uint32 diff) inline
Definition at line 147 of file SpellAuras.h.
References Update().
Referenced by Unit::_UpdateSpells().
Field Documentation
m_applyMSTime
uint32 SpellAuraHolder::m_applyMSTime private
Definition at line 231 of file SpellAuras.h.
Referenced by GetAuraApplyMSTime(), SpellAuraHolder(), and Update().
m_applyTime
time_t SpellAuraHolder::m_applyTime private
Definition at line 230 of file SpellAuras.h.
Referenced by GetAuraApplyTime(), and SpellAuraHolder().
m_AuraDRGroup
DiminishingGroup SpellAuraHolder::m_AuraDRGroup private
Definition at line 248 of file SpellAuras.h.
Referenced by getDiminishGroup(), and setDiminishGroup().
m_auraLevel
uint8 SpellAuraHolder::m_auraLevel private
Definition at line 236 of file SpellAuras.h.
Referenced by GetAuraLevel(), and SetAuraLevel().
m_auras
Aura* SpellAuraHolder::m_auras[MAX_EFFECT_INDEX]
Definition at line 98 of file SpellAuras.h.
Referenced by AddAura(), DynamicObject::Delay(), DropAuraCharge(), Spell::EffectEnchantHeldItem(), GetAuraByEffectIndex(), Aura::HandleAuraModShapeshift(), Unit::HandleRaidProcFromChargeAuraProc(), Unit::HandleRaidProcFromChargeWithValueAuraProc(), HasAuraType(), HasMechanic(), HasMechanicMask(), HasModifier(), Unit::Heartbeat(), IsAreaAura(), IsCharm(), IsEmptyHolder(), IsNeedVisibleSlot(), IsPersistent(), IsPositive(), Unit::IsTriggeredAtSpellProcEvent(), HuntersMark::OnAuraValueCalculate(), DirtyDeeds::OnDamageCalculate(), AQWhirlwind::OnEffectExecute(), RemoveAura(), Unit::RemoveSpellAuraHolder(), ResetSpellModCharges(), SetAuraCharges(), SetAuraFlag(), SetStackAmount(), SpellAuraHolder(), Aura::TriggerSpell(), Update(), and ~SpellAuraHolder().
m_auraScript
AuraScript* SpellAuraHolder::m_auraScript private
Definition at line 263 of file SpellAuras.h.
Referenced by GetAuraScript(), and SpellAuraHolder().
m_auraSlot
uint8 SpellAuraHolder::m_auraSlot private
Definition at line 235 of file SpellAuras.h.
Referenced by GetAuraSlot(), SetAuraSlot(), and UpdateAuraApplication().
m_casterGuid
ObjectGuid SpellAuraHolder::m_casterGuid private
Definition at line 228 of file SpellAuras.h.
Referenced by GetCaster(), GetCasterGuid(), LoginAuraDuration(), SetCasterGuid(), SetLoadedState(), SetStackAmount(), and SpellAuraHolder().
m_castItemGuid
ObjectGuid SpellAuraHolder::m_castItemGuid private
Definition at line 229 of file SpellAuras.h.
Referenced by GetCastItemGuid(), and SetLoadedState().
m_deleted
bool SpellAuraHolder::m_deleted private
Definition at line 255 of file SpellAuras.h.
Referenced by IsDeleted(), and SetDeleted().
m_duration
int32 SpellAuraHolder::m_duration private
Definition at line 240 of file SpellAuras.h.
Referenced by GetAuraDuration(), SetAuraDuration(), SpellAuraHolder(), and Update().
m_heartbeatResistChance
float SpellAuraHolder::m_heartbeatResistChance private
Definition at line 243 of file SpellAuras.h.
Referenced by SetHeartbeatResist(), and UpdateHeartbeatResist().
m_heartbeatResistInterval
int32 SpellAuraHolder::m_heartbeatResistInterval private
Definition at line 244 of file SpellAuras.h.
Referenced by SetHeartbeatResist(), and UpdateHeartbeatResist().
m_heartbeatResistTimer
int32 SpellAuraHolder::m_heartbeatResistTimer private
Definition at line 245 of file SpellAuras.h.
Referenced by SetHeartbeatResist(), and UpdateHeartbeatResist().
m_isDeathPersist
bool SpellAuraHolder::m_isDeathPersist private
Definition at line 253 of file SpellAuras.h.
Referenced by IsDeathPersistent(), and SpellAuraHolder().
m_isPassive
bool SpellAuraHolder::m_isPassive private
Definition at line 252 of file SpellAuras.h.
Referenced by IsNeedVisibleSlot(), IsPassive(), and SpellAuraHolder().
m_isRemovedOnShapeLost
bool SpellAuraHolder::m_isRemovedOnShapeLost private
Definition at line 254 of file SpellAuras.h.
Referenced by IsRemovedOnShapeLost(), and SpellAuraHolder().
m_maxDuration
int32 SpellAuraHolder::m_maxDuration private
Definition at line 239 of file SpellAuras.h.
Referenced by GetAuraMaxDuration(), SetAuraMaxDuration(), and SpellAuraHolder().
m_permanent
bool SpellAuraHolder::m_permanent private
Definition at line 251 of file SpellAuras.h.
Referenced by IsPermanent(), SetPermanent(), and SpellAuraHolder().
m_procCharges
uint32 SpellAuraHolder::m_procCharges private
Definition at line 237 of file SpellAuras.h.
Referenced by _RemoveSpellAuraHolder(), DropAuraCharge(), GetAuraCharges(), ResetSpellModCharges(), SetAuraCharges(), SetLoadedState(), SpellAuraHolder(), and UpdateAuraApplication().
m_procCooldown
TimePoint SpellAuraHolder::m_procCooldown private
Definition at line 258 of file SpellAuras.h.
Referenced by IsProcReady(), and SetProcCooldown().
m_reducedProcChancePast60
bool SpellAuraHolder::m_reducedProcChancePast60 private
Definition at line 260 of file SpellAuras.h.
Referenced by IsReducedProcChancePast60(), and SetReducedProcChancePast60().
m_removeMode
AuraRemoveMode SpellAuraHolder::m_removeMode private
Definition at line 247 of file SpellAuras.h.
Referenced by _RemoveSpellAuraHolder(), and SetRemoveMode().
m_skipUpdate
bool SpellAuraHolder::m_skipUpdate private
Definition at line 256 of file SpellAuras.h.
Referenced by SetCreationDelayFlag(), and Update().
m_spellAuraHolderState
SpellAuraHolderState SpellAuraHolder::m_spellAuraHolderState private
Definition at line 233 of file SpellAuras.h.
Referenced by GetState(), SetDeleted(), and SetState().
m_spellProto
SpellEntry const* SpellAuraHolder::m_spellProto private
Definition at line 225 of file SpellAuras.h.
Referenced by _AddSpellAuraHolder(), _RemoveSpellAuraHolder(), CleanupTriggeredSpells(), DropAuraCharge(), GetId(), GetSpellProto(), HasAuraType(), HasMechanic(), HasMechanicMask(), IsCharm(), IsNeedVisibleSlot(), IsSaveToDbHolder(), ModStackAmount(), SetAuraFlag(), SetStackAmount(), SpellAuraHolder(), and UpdateHeartbeatResist().
m_stackAmount
uint32 SpellAuraHolder::m_stackAmount private
Definition at line 238 of file SpellAuras.h.
Referenced by _RemoveSpellAuraHolder(), GetStackAmount(), ModStackAmount(), PresetAuraStacks(), SetLoadedState(), SetStackAmount(), SpellAuraHolder(), and UpdateAuraApplication().
m_target
Unit* SpellAuraHolder::m_target private
Definition at line 227 of file SpellAuras.h.
Referenced by _AddSpellAuraHolder(), _RemoveSpellAuraHolder(), CleanupTriggeredSpells(), ClearExtraAuraInfo(), DropAuraCharge(), GetCaster(), GetTarget(), HandleSpellSpecificBoosts(), IsNeedVisibleSlot(), IsWeaponBuffCoexistableWith(), LoginAuraDuration(), SendAuraDuration(), SendAuraDurationToCaster(), SendAuraDurationToCasterNeedUpdate(), SetAura(), SetAuraFlag(), SetAuraLevel(), SetStackAmount(), SetTarget(), UpdateAuraApplication(), and UpdateAuraDuration().
m_timeCla
int32 SpellAuraHolder::m_timeCla private
Definition at line 241 of file SpellAuras.h.
Referenced by Update().
m_trackedAuraType
TrackedAuraType SpellAuraHolder::m_trackedAuraType private
Definition at line 249 of file SpellAuras.h.
Referenced by GetTrackedAuraType(), SetTrackedAuraType(), SpellAuraHolder(), and UnregisterAndCleanupTrackedAuras().
m_triggeredBy
SpellEntry const* SpellAuraHolder::m_triggeredBy private
Definition at line 232 of file SpellAuras.h.
Referenced by GetTriggeredBy().
The documentation for this class was generated from the following files:
SpellAuras.h
SpellAuras.cpp