CMaNGOS_TBC: SQLStorage Class Reference
SQLStorage Class Reference
#include <SQLStorage.h>
Public Member Functions
SQLStorage (const char *fmt, const char *_entry_field, const char *sqlname)
SQLStorage (const char *src_fmt, const char *dst_fmt, const char *_entry_field, const char *sqlname)
~SQLStorage ()
template<class T >
T const * LookupEntry (uint32 id) const
void Load (bool error_at_empty=true)
void EraseEntry (uint32 id)
Public Member Functions inherited from SQLStorageBase
char const * GetTableName () const
char const * EntryFieldName () const
FieldFormat GetDstFormat (uint32 idx) const
const char * GetDstFormat () const
FieldFormat GetSrcFormat (uint32 idx) const
const char * GetSrcFormat () const
uint32 GetMaxEntry () const
uint32 GetRecordCount () const
template<typename T >
SQLSIterator< T > getDataBegin () const
template<typename T >
SQLSIterator< T > getDataEnd () const
Protected Member Functions
void prepareToLoad (uint32 maxRecordId, uint32 recordCount, uint32 recordSize) override
void JustCreatedRecord (uint32 recordId, char *record) override
void Free () override
Protected Member Functions inherited from SQLStorageBase
SQLStorageBase ()
virtual ~SQLStorageBase ()
void Initialize (const char *tableName, const char *entry_field, const char *src_format, const char *dst_format)
uint32 GetDstFieldCount () const
uint32 GetSrcFieldCount () const
uint32 GetRecordSize () const
Private Attributes
char ** m_Index
Friends
template<class DerivedLoader , class StorageClass >
class SQLStorageLoaderBase
Detailed Description
Definition at line 101 of file SQLStorage.h.
Constructor & Destructor Documentation
SQLStorage() [1/2]
SQLStorage::SQLStorage (const char * fmt, const char * _entry_field, const char * sqlname)
Definition at line 143 of file SQLStorage.cpp.
References SQLStorageBase::Initialize(), and m_Index.
SQLStorage() [2/2]
SQLStorage::SQLStorage (const char * src_fmt, const char * dst_fmt, const char * _entry_field, const char * sqlname)
Definition at line 149 of file SQLStorage.cpp.
References SQLStorageBase::Initialize(), and m_Index.
~SQLStorage()
SQLStorage::~SQLStorage () inline
Definition at line 110 of file SQLStorage.h.
References Free().
Member Function Documentation
EraseEntry()
void SQLStorage::EraseEntry (uint32 id)
Definition at line 125 of file SQLStorage.cpp.
References m_Index.
Referenced by ObjectMgr::LoadConditions(), ObjectMgr::LoadInstanceTemplate(), ObjectMgr::LoadSpellTemplate(), and ObjectMgr::LoadWorldTemplate().
Free()
void SQLStorage::Free () override protected virtual
Reimplemented from SQLStorageBase.
Definition at line 130 of file SQLStorage.cpp.
References SQLStorageBase::Free(), and m_Index.
Referenced by prepareToLoad(), and ~SQLStorage().
JustCreatedRecord()
void SQLStorage::JustCreatedRecord (uint32 recordId, char * record) inline override protected virtual
Implements SQLStorageBase.
Definition at line 126 of file SQLStorage.h.
References m_Index.
Load()
void SQLStorage::Load (bool error_at_empty = true)
Definition at line 137 of file SQLStorage.cpp.
References SQLStorageLoaderBase< DerivedLoader, StorageClass >::Load().
Referenced by ObjectMgr::LoadCreatureAddons(), ObjectMgr::LoadCreatureConditionalSpawn(), ObjectMgr::LoadCreatureModelInfo(), ObjectMgr::LoadDungeonEncounters(), ObjectMgr::LoadEquipmentTemplates(), ObjectMgr::LoadFactions(), ObjectMgr::LoadPageTexts(), ObjectMgr::LoadSpellTemplate(), and World::LoadWorldSafeLocs().
LookupEntry()
template<class T > T const* SQLStorage::LookupEntry (uint32 id) const inline
Definition at line 113 of file SQLStorage.h.
References SQLStorageBase::GetMaxEntry(), and m_Index.
Referenced by PlayerbotAI::_HandleCommandCraft(), PlayerbotAI::_HandleCommandEnchant(), PlayerbotAI::_HandleCommandPet(), PlayerbotAI::_HandleCommandProcess(), PlayerbotAI::_HandleCommandSkill(), PlayerbotAI::_HandleCommandSpells(), PlayerbotAI::_HandleCommandTalent(), Player::_LoadAuras(), Pet::_LoadAuras(), Pet::_LoadSpellCooldowns(), Player::_LoadSpellCooldowns(), Unit::AddGameObject(), UnitAI::AddInitialCooldowns(), AddItemsSetItem(), UnitAI::AddMainSpell(), PlayerAI::AddPlayerSpellAction(), Spell::AddPrecastSpell(), Player::AddQuest(), boss_high_botanist_freywinnAI::AddSeedlingCooldowns(), Pet::addSpell(), Player::addSpell(), Spell::AddTriggeredSpell(), Player::ApplyEquipCooldown(), Creature::ApplyGameEventSpells(), Player::ApplyItemEquipSpell(), Player::ApplySpellMod(), AreaTrigger_at_area_52(), Aura::Aura(), boss_selin_fireheartAI::boss_selin_fireheartAI(), PlayerbotAI::Buff(), Player::BuildEnumData(), WorldSession::BuildListAuctionItems(), Player::CalculateReputationGain(), Unit::CanAttackInCombat(), Unit::CanAttackSpell(), ConditionEntry::CanBeUsedWithoutPlayer(), PlayerbotAI::CanReachWithSpellAttack(), Unit::CastCustomSpell(), CastHighestStealthRank(), Player::CastItemCombatSpell(), Player::CastItemUseSpell(), PlayerbotAI::CastPetSpell(), PlayerbotAI::CastSpell(), GameObject::CastSpell(), Unit::CastSpell(), Player::CheckAreaExploreAndOutdoor(), Spell::CheckCast(), LootMgr::CheckDropStats(), ChatHandler::CheckEscapeSequences(), CheckGOSpellId(), ObjectMgr::CheckSpellCones(), SpellMgr::CheckUsedSpells(), UnitAI::ChooseTarget(), SpellAuraHolder::CleanupTriggeredSpells(), ScriptMgr::CollectPossibleEventIds(), ObjectMgr::ConvertCreatureAddonAuras(), DynamicObject::Create(), BattleGroundMgr::CreateInitialBattleGrounds(), Unit::DealSpellDamage(), npc_king_llaneAI::DoCastPrimarySpell(), npc_warchief_blackhandAI::DoCastPrimarySpell(), npc_human_conjurerAI::DoCastPrimarySpell(), npc_orc_warlockAI::DoCastPrimarySpell(), npc_human_footmanAI::DoCastPrimarySpell(), npc_orc_gruntAI::DoCastPrimarySpell(), npc_water_elementalAI::DoCastPrimarySpell(), npc_summoned_daemonAI::DoCastPrimarySpell(), npc_human_chargerAI::DoCastPrimarySpell(), npc_orc_wolfAI::DoCastPrimarySpell(), npc_human_clericAI::DoCastPrimarySpell(), npc_orc_necrolyteAI::DoCastPrimarySpell(), npc_king_llaneAI::DoCastSecondarySpell(), npc_warchief_blackhandAI::DoCastSecondarySpell(), npc_human_conjurerAI::DoCastSecondarySpell(), npc_orc_warlockAI::DoCastSecondarySpell(), npc_human_footmanAI::DoCastSecondarySpell(), npc_orc_gruntAI::DoCastSecondarySpell(), npc_water_elementalAI::DoCastSecondarySpell(), npc_summoned_daemonAI::DoCastSecondarySpell(), npc_human_chargerAI::DoCastSecondarySpell(), npc_orc_wolfAI::DoCastSecondarySpell(), npc_human_clericAI::DoCastSecondarySpell(), npc_orc_necrolyteAI::DoCastSecondarySpell(), UnitAI::DoCastSpellIfCan(), UnitAI::DoFindFriendlyEligibleDispel(), UnitAI::DoFindFriendlyMissingBuff(), PlayerbotHunterAI::DoNextCombatManeuverPVE(), Spell::EffectDestroyAllTotems(), Spell::EffectDummy(), Spell::EffectEnergize(), Spell::EffectForceCast(), Spell::EffectLearnPetSpell(), Spell::EffectReputation(), Spell::EffectSummonRafFriend(), Spell::EffectTriggerMissileSpell(), Spell::EffectTriggerRitualOfSummoning(), Spell::EffectTriggerSpell(), Spell::EffectTriggerSpellWithValue(), Player::EnchantmentFitsRequirements(), Player::EquipItem(), EquippedOk(), ConditionEntry::Evaluate(), boss_curatorAI::ExecuteAction(), ScriptAction::ExecuteDbscriptCommand(), FillSpellSummary(), PlayerbotAI::FindMount(), PlayerbotClassAI::FleeFromAoEIfCan(), PlayerbotClassAI::FleeFromNpcWithAuraIfCan(), Item::GemsFitSockets(), Item::GenerateItemRandomPropertyId(), GraveyardManager::GetClosestGraveyardHelper(), Spell::GetCone(), ObjectMgr::GetCreatureAddon(), ObjectMgr::GetCreatureConditionalSpawn(), ObjectMgr::GetCreatureModelInfo(), ObjectMgr::GetCreatureTemplate(), ObjectMgr::GetCreatureTemplateAddon(), GetCreatureTemplateStore(), ObjectMgr::GetEquipmentInfo(), ObjectMgr::GetEquipmentInfoRaw(), GetFactionReaction(), ObjectMgr::GetInstanceTemplate(), ObjectMgr::GetItemPrototype(), PlayerbotAI::getPetSpellId(), Unit::GetReactionTo(), ReputationMgr::GetReputation(), Player::GetReputationRank(), SpellMgr::GetSpellAffectMask(), GetSpellAuraMaxTicks(), PlayerbotAI::GetSpellCharges(), GameObject::GetSpellForLock(), PlayerbotAI::getSpellId(), GetSpellSpecific(), GetSpellStartDBScriptPriority(), Player::GetTrainerSpellState(), ObjectMgr::GetWorldTemplate(), WorldSession::HandleAcceptTradeOpcode(), ChatHandler::HandleAddItemSetCommand(), OutdoorPvPSI::HandleAreaTrigger(), ChatHandler::HandleAuraCommand(), Aura::HandleAuraModShapeshift(), Aura::HandleAuraModStun(), PlayerbotAI::HandleBotOutgoingPacket(), WorldSession::HandleCancelAuraOpcode(), ChatHandler::HandleCastBackCommand(), ChatHandler::HandleCastCommand(), ChatHandler::HandleCastDistCommand(), ChatHandler::HandleCastSelfCommand(), WorldSession::HandleCastSpellOpcode(), ChatHandler::HandleCastTargetCommand(), ChatHandler::HandleCharacterReputationCommand(), ChatHandler::HandleCooldownClearCommand(), ChatHandler::HandleDamageCommand(), ChatHandler::HandleDebugSpellCoefsCommand(), Unit::HandleDummyAuraProc(), ChatHandler::HandleGMVisibleCommand(), ChatHandler::HandleGoGraveyardCommand(), WorldSession::HandleItemQuerySingleOpcode(), ChatHandler::HandleLearnAllCommand(), ChatHandler::HandleLearnAllGMCommand(), ChatHandler::HandleLearnAllMySpellsCommand(), ChatHandler::HandleLearnAllMyTalentsCommand(), ChatHandler::HandleLearnCommand(), ChatHandler::HandleLearnSkillRecipesHelper(), ChatHandler::HandleLinkGraveCommand(), ChatHandler::HandleListTalentsCommand(), ChatHandler::HandleLookupCreatureCommand(), ChatHandler::HandleLookupFactionCommand(), ChatHandler::HandleLookupItemCommand(), ChatHandler::HandleLookupSpellCommand(), PlayerbotMgr::HandleMasterOutgoingPacket(), ChatHandler::HandleModifyRepCommand(), WorldSession::HandlePageTextQueryOpcode(), WorldSession::HandlePetAction(), WorldSession::HandlePetCancelAuraOpcode(), WorldSession::HandlePetCastSpellOpcode(), WorldSession::HandlePlayerLogin(), Unit::HandleProcTriggerSpellAuraProc(), ChatHandler::HandleQuestAddCommand(), ChatHandler::HandleQuestCompleteCommand(), WorldSession::HandleSelfResOpcode(), Aura::HandleShapeshiftBoosts(), SpellAuraHolder::HandleSpellSpecificBoosts(), WorldSession::HandleUseItemOpcode(), PlayerbotAI::HasSpellReagents(), Pet::IgnoresOwnersDeath(), PlayerbotAI::In_Range(), CharmInfo::InitCharmCreateSpells(), ReputationMgr::Initialize(), SpellTargetMgr::Initialize(), Pet::InitPetCreateSpells(), PlayerbotAI::initPetSpell(), CharmInfo::InitPossessCreateSpells(), PlayerbotAI::initSpell(), Player::IsActionButtonDataValid(), SpellModifier::isAffectedOnSpell(), ReputationMgr::IsAtWar(), IsAuraAddedBySpell(), IsAutocastable(), IsConditionSatisfied(), ObjectMgr::IsConditionSatisfied(), Unit::IsNeutralToAll(), IsPassiveSpell(), IsPositiveEffectTargetMode(), IsPositiveSpell(), IsPositiveSpellTargetMode(), IsPositiveSpellTargetModeForSpecificTarget(), SpellMgr::IsPrimaryProfessionSpell(), SpellMgr::IsProfessionOrRidingSpell(), SpellMgr::IsProfessionSpell(), IsQuestTameSpell(), WorldObject::IsSpellReady(), SpellMgr::IsSpellValid(), ConditionEntry::IsValid(), ObjectMgr::IsVendorItemValid(), Unit::JustKilledCreature(), guardAI::JustRespawned(), npc_corrupted_lightning_totemAI::JustRespawned(), Player::learnQuestRewardedSpells(), ObjectMgr::LoadAreaTriggerTeleports(), ObjectMgr::LoadConditions(), ObjectMgr::LoadCreatureAddons(), ObjectMgr::LoadCreatureConditionalSpawn(), ObjectMgr::LoadCreatureCooldowns(), CreatureEventAIMgr::LoadCreatureEventAI_Scripts(), ObjectMgr::LoadCreatureImmunities(), ObjectMgr::LoadCreatureModelInfo(), ObjectMgr::LoadCreatureModelRace(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadCreatureSpellLists(), ObjectMgr::LoadCreatureTemplates(), ObjectMgr::LoadCreatureTemplateSpells(), LoadDBCStores(), ObjectMgr::LoadEquipmentTemplates(), ObjectMgr::LoadFactions(), GameEventMgr::LoadFromDB(), ReputationMgr::LoadFromDB(), ObjectMgr::LoadGameobjectInfo(), ObjectMgr::LoadGossipMenu(), ObjectMgr::LoadGossipMenuItems(), World::LoadGraveyardZones(), ObjectMgr::LoadInstanceEncounters(), ObjectMgr::LoadItemPrototypes(), ObjectMgr::LoadItemRequiredTarget(), LootStore::LoadLootTable(), LoadLootTemplates_Creature(), LoadLootTemplates_Disenchant(), LoadLootTemplates_Item(), LoadLootTemplates_Pickpocketing(), LoadLootTemplates_Prospecting(), LoadLootTemplates_Skinning(), ObjectMgr::LoadPageTextLocales(), ObjectMgr::LoadPageTexts(), CharmInfo::LoadPetActionBar(), ObjectMgr::LoadPetCreateSpells(), Pet::LoadPetFromDB(), ObjectMgr::LoadPetLevelInfo(), ObjectMgr::LoadPlayerInfo(), ObjectMgr::LoadQuestgiverGreeting(), ObjectMgr::LoadQuestgiverGreetingLocales(), ObjectMgr::LoadQuests(), ObjectMgr::LoadReputationOnKill(), ObjectMgr::LoadReputationRewardRate(), ObjectMgr::LoadReputationSpilloverTemplate(), ScriptMgr::LoadScriptMap(), SpellScriptMgr::LoadScripts(), ScriptMgr::LoadScripts(), LoadSkillDiscoveryTable(), LoadSkillExtraItemTable(), ObjectMgr::LoadSpawnGroups(), SpellMgr::LoadSpellAffects(), SpellMgr::LoadSpellAreas(), SpellMgr::LoadSpellBonuses(), SpellMgr::LoadSpellChains(), SpellMgr::LoadSpellElixirs(), SpellMgr::LoadSpellLearnSkills(), SpellMgr::LoadSpellLearnSpells(), SpellMgr::LoadSpellPetAuras(), SpellMgr::LoadSpellProcItemEnchant(), SpellMgr::LoadSpellScriptTarget(), SpellMgr::LoadSpellTargetPositions(), ObjectMgr::LoadSpellTemplate(), ObjectMgr::LoadTrainerGreetingLocales(), ObjectMgr::LoadTrainerGreetings(), ObjectMgr::LoadTrainers(), ObjectMgr::LoadTrainerTemplates(), ObjectMgr::LoadVendorTemplates(), Player::LockOutSpells(), Unit::MeetsSelectAttackingRequirement(), Unit::ModifyAuraState(), DarknessOfSouls::OnApply(), CheatDeathRogue::OnAuraDeathPrevention(), PrayerOfMending::OnCheckCast(), SpellBurnBrutallus::OnCheckTarget(), PrayerOfMending::OnEffectExecute(), GuardianPeriodic::OnPeriodicTrigger(), PeriodicIceBolt::OnPeriodicTrigger(), DespawnBuffet::OnPeriodicTrigger(), EarthquakeGuardian::OnPeriodicTrigger(), PeriodicRotate::OnPeriodicTrigger(), PeriodicScarabTrigger::OnPeriodicTrigger(), SpoutTurning::OnPeriodicTrigger(), UnitAI::OnSpellInterrupt(), UpdateZoneDependentPetsHelper::operator()(), Loot::PrintLootList(), CreatureEventAI::ProcessAction(), Spell::ProcSpellAuraTriggers(), Creature::ReachWithSpellAttack(), Creature::ReachWithSpellCure(), SpellRankHelper< EntryType, WorkerType, StorageType >::RecordRank(), Unit::RemoveGameObject(), Unit::RemoveRankAurasDueToSpell(), Player::RemoveSomeCooldown(), Player::removeSpell(), WorldObject::RemoveSpellCooldown(), Player::RemoveSpellLockout(), Player::ReputationChanged(), Player::RewardQuest(), Player::RewardReputation(), BattleGround::RewardReputationToTeam(), BattleGround::RewardSpellCast(), Unit::SelectAttackingTarget(), Unit::SelectAttackingTargets(), SpellMgr::SelectAuraRankForLevel(), Spell::SelectMountByAreaAndSkill(), ScriptedAI::SelectSpell(), ReputationMgr::SetReputation(), Totem::SetTypeBySummonSpell(), ReputationMgr::SetVisible(), ChatHandler::ShowItemListHelper(), Spell::Spell(), SpellAuraHolder::SpellAuraHolder(), CharacterDatabaseCleaner::SpellCheck(), Unit::SpellNonMeleeDamageLog(), Creature::StartCooldown(), Unit::TriggerProccedSpell(), Aura::TriggerSpell(), Aura::TriggerSpellWithValue(), Pet::TryLoadFromDB(), Pet::Unsummon(), PetAI::UpdateAI(), TotemAI::UpdateAI(), npc_kyle_the_frenziedAI::UpdateAI(), PlayerbotAI::UpdateAI(), npc_dragonmaw_peonAI::UpdateAI(), Player::UpdateCraftSkill(), UnitAI::UpdateSpellLists(), GameObject::Use(), PlayerbotAI::UseItem(), and MaNGOS::DynamicObjectUpdater::VisitHelper().
prepareToLoad()
void SQLStorage::prepareToLoad (uint32 maxRecordId, uint32 recordCount, uint32 recordSize) override protected virtual
Reimplemented from SQLStorageBase.
Definition at line 155 of file SQLStorage.cpp.
References Free(), m_Index, and SQLStorageBase::prepareToLoad().
Friends And Related Function Documentation
SQLStorageLoaderBase
template<class DerivedLoader , class StorageClass > friend class SQLStorageLoaderBase friend
Definition at line 103 of file SQLStorage.h.
Field Documentation
m_Index
char** SQLStorage::m_Index private
Definition at line 135 of file SQLStorage.h.
Referenced by EraseEntry(), Free(), JustCreatedRecord(), LookupEntry(), prepareToLoad(), and SQLStorage().
The documentation for this class was generated from the following files:
SQLStorage.h
SQLStorage.cpp