CMaNGOS_TBC: AddonHandler Class Reference
AddonHandler Class Reference
#include <AddonHandler.h>
Public Member Functions
AddonHandler ()
~AddonHandler ()
bool BuildAddonPacket (WorldPacket &Source, WorldPacket &Target)
Detailed Description
Definition at line 26 of file AddonHandler.h.
Constructor & Destructor Documentation
AddonHandler()
AddonHandler::AddonHandler ()
Definition at line 29 of file Addons/AddonHandler.cpp.
~AddonHandler()
AddonHandler::~AddonHandler ()
Definition at line 33 of file Addons/AddonHandler.cpp.
Member Function Documentation
BuildAddonPacket()
bool AddonHandler::BuildAddonPacket (WorldPacket & Source, WorldPacket & Target)
Definition at line 37 of file Addons/AddonHandler.cpp.
References ByteBuffer::contents(), ByteBuffer::resize(), ByteBuffer::rpos(), ByteBuffer::size(), sLog, and SMSG_ADDON_INFO.
The documentation for this class was generated from the following files:
AddonHandler.h
Addons/AddonHandler.cpp