CMaNGOS_TBC: Movement::MoveSplineFlag Class Reference
Movement::MoveSplineFlag Class Reference
#include <MoveSplineFlag.h>
Public Types
enum eFlags : uint32 {
None = 0x00000000 , Done = 0x00000001 , Falling = 0x00000002 , Unknown3 = 0x00000004 ,
Unknown4 = 0x00000008 , Unknown5 = 0x00000010 , Unknown6 = 0x00000020 , Unknown7 = 0x00000040 ,
Unknown8 = 0x00000080 , Runmode = 0x00000100 , Flying = 0x00000200 , No_Spline = 0x00000400 ,
Unknown12 = 0x00000800 , Unknown13 = 0x00001000 , Unknown14 = 0x00002000 , Unknown15 = 0x00004000 ,
Unknown16 = 0x00008000 , Final_Point = 0x00010000 , Final_Target = 0x00020000 , Final_Angle = 0x00040000 ,
Unknown19 = 0x00080000 , Cyclic = 0x00100000 , Enter_Cycle = 0x00200000 , Frozen = 0x00400000 ,
Unknown23 = 0x00800000 , Unknown24 = 0x01000000 , Unknown25 = 0x02000000 , Unknown26 = 0x04000000 ,
Unknown27 = 0x08000000 , Unknown28 = 0x10000000 , Unknown29 = 0x20000000 , Unknown30 = 0x40000000 ,
Unknown31 = 0x80000000 , Mask_Final_Facing = Final_Point | Final_Target | Final_Angle , Mask_No_Monster_Move = Mask_Final_Facing | Done , Mask_CatmullRom = Flying
}
Public Member Functions
uint32 & raw ()
const uint32 & raw () const
MoveSplineFlag ()
MoveSplineFlag (uint32 f)
MoveSplineFlag (const MoveSplineFlag &f)
bool isSmooth () const
bool isFacing () const
bool hasAllFlags (uint32 f) const
uint32 operator& (uint32 f) const
uint32 operator| (uint32 f) const
std::string ToString () const
void operator&= (uint32 f)
void operator|= (uint32 f)
void EnableFacingPoint ()
void EnableFacingAngle ()
void EnableFacingTarget ()
Data Fields
bool done: 1
bool falling: 1
bool unknown3: 1
bool unknown4: 1
bool unknown5: 1
bool unknown6: 1
bool unknown7: 1
bool unknown8: 1
bool runmode: 1
bool flying: 1
bool no_spline: 1
bool unknown12: 1
bool unknown13: 1
bool unknown14: 1
bool unknown15: 1
bool unknown16: 1
bool final_point: 1
bool final_target: 1
bool final_angle: 1
bool unknown19: 1
bool cyclic: 1
bool enter_cycle: 1
bool frozen: 1
bool unknown23: 1
bool unknown24: 1
bool unknown25: 1
bool unknown26: 1
bool unknown27: 1
bool unknown28: 1
bool unknown29: 1
bool unknown30: 1
bool unknown31: 1
Detailed Description
Definition at line 31 of file MoveSplineFlag.h.
Member Enumeration Documentation
eFlags
enum Movement::MoveSplineFlag::eFlags : uint32
Enumerator
None
Done
Falling
Unknown3
Unknown4
Unknown5
Unknown6
Unknown7
Unknown8
Runmode
Flying
No_Spline
Unknown12
Unknown13
Unknown14
Unknown15
Unknown16
Final_Point
Final_Target
Final_Angle
Unknown19
Cyclic
Enter_Cycle
Frozen
Unknown23
Unknown24
Unknown25
Unknown26
Unknown27
Unknown28
Unknown29
Unknown30
Unknown31
Mask_Final_Facing
Mask_No_Monster_Move
Mask_CatmullRom
Definition at line 34 of file MoveSplineFlag.h.
Constructor & Destructor Documentation
MoveSplineFlag() [1/3]
Movement::MoveSplineFlag::MoveSplineFlag () inline
Definition at line 81 of file MoveSplineFlag.h.
References raw().
MoveSplineFlag() [2/3]
Movement::MoveSplineFlag::MoveSplineFlag (uint32 f) inline
Definition at line 82 of file MoveSplineFlag.h.
References raw().
MoveSplineFlag() [3/3]
Movement::MoveSplineFlag::MoveSplineFlag (const MoveSplineFlag & f) inline
Definition at line 83 of file MoveSplineFlag.h.
References raw().
Member Function Documentation
EnableFacingAngle()
void Movement::MoveSplineFlag::EnableFacingAngle () inline
Definition at line 101 of file MoveSplineFlag.h.
References Final_Angle, Mask_Final_Facing, and raw().
Referenced by Movement::MoveSplineInit::SetFacing().
EnableFacingPoint()
void Movement::MoveSplineFlag::EnableFacingPoint () inline
Definition at line 100 of file MoveSplineFlag.h.
References Final_Point, Mask_Final_Facing, and raw().
Referenced by Movement::MoveSplineInit::SetFacing().
EnableFacingTarget()
void Movement::MoveSplineFlag::EnableFacingTarget () inline
Definition at line 102 of file MoveSplineFlag.h.
References Final_Target, Mask_Final_Facing, and raw().
Referenced by Movement::MoveSplineInit::SetFacing().
hasAllFlags()
bool Movement::MoveSplineFlag::hasAllFlags (uint32 f) const inline
Definition at line 90 of file MoveSplineFlag.h.
References raw().
isFacing()
bool Movement::MoveSplineFlag::isFacing () const inline
Definition at line 88 of file MoveSplineFlag.h.
References Mask_Final_Facing, and raw().
Referenced by Movement::MoveSpline::ComputePosition(), and Movement::MoveSpline::isFacing().
isSmooth()
bool Movement::MoveSplineFlag::isSmooth () const inline
Definition at line 87 of file MoveSplineFlag.h.
References Mask_CatmullRom, and raw().
Referenced by Movement::MoveSpline::init_spline().
operator&()
uint32 Movement::MoveSplineFlag::operator& (uint32 f) const inline
Definition at line 91 of file MoveSplineFlag.h.
References raw().
operator&=()
void Movement::MoveSplineFlag::operator&= (uint32 f) inline
Definition at line 97 of file MoveSplineFlag.h.
References raw().
operator|()
uint32 Movement::MoveSplineFlag::operator| (uint32 f) const inline
Definition at line 92 of file MoveSplineFlag.h.
References raw().
operator|=()
void Movement::MoveSplineFlag::operator|= (uint32 f) inline
Definition at line 98 of file MoveSplineFlag.h.
References raw().
raw() [1/2]
uint32& Movement::MoveSplineFlag::raw () inline
Definition at line 78 of file MoveSplineFlag.h.
Referenced by EnableFacingAngle(), EnableFacingPoint(), EnableFacingTarget(), hasAllFlags(), isFacing(), isSmooth(), MoveSplineFlag(), operator&(), operator&=(), operator|(), operator|=(), ToString(), and Movement::PacketBuilder::WriteCreate().
raw() [2/2]
const uint32& Movement::MoveSplineFlag::raw () const inline
Definition at line 79 of file MoveSplineFlag.h.
ToString()
std::string Movement::MoveSplineFlag::ToString () const
Definition at line 201 of file util.cpp.
References Movement::g_SplineFlag_names, Movement::print_flags(), and raw().
Referenced by Movement::MoveSpline::ToString().
Field Documentation
cyclic
bool Movement::MoveSplineFlag::cyclic
Definition at line 124 of file MoveSplineFlag.h.
Referenced by Movement::MoveSpline::init_spline(), Movement::MoveSpline::isCyclic(), Movement::MoveSplineInit::Launch(), Movement::MoveSplineInit::SetCyclic(), and Movement::PacketBuilder::WriteMonsterMove().
done
bool Movement::MoveSplineFlag::done
Definition at line 104 of file MoveSplineFlag.h.
Referenced by Movement::MoveSpline::_Finalize(), Movement::MoveSpline::_Interrupt(), Movement::MoveSpline::ComputePosition(), Movement::MoveSpline::Finalized(), Movement::MoveSpline::Initialize(), and Movement::MoveSpline::MoveSpline().
enter_cycle
bool Movement::MoveSplineFlag::enter_cycle
Definition at line 125 of file MoveSplineFlag.h.
Referenced by Movement::MoveSpline::_updateState(), Movement::MoveSpline::init_spline(), and Movement::MoveSplineInit::Launch().
falling
bool Movement::MoveSplineFlag::falling
Definition at line 105 of file MoveSplineFlag.h.
Referenced by Movement::MoveSpline::ComputePosition(), Movement::MoveSpline::init_spline(), and Movement::MoveSplineInit::SetFall().
final_angle
bool Movement::MoveSplineFlag::final_angle
Definition at line 122 of file MoveSplineFlag.h.
Referenced by Movement::MoveSpline::ComputePosition(), Movement::MoveSpline::isFacingAngle(), Movement::MoveSpline::ToString(), and Movement::PacketBuilder::WriteCreate().
final_point
bool Movement::MoveSplineFlag::final_point
Definition at line 120 of file MoveSplineFlag.h.
Referenced by Movement::MoveSpline::ComputePosition(), Movement::MoveSpline::isFacingPoint(), Movement::MoveSpline::ToString(), and Movement::PacketBuilder::WriteCreate().
final_target
bool Movement::MoveSplineFlag::final_target
Definition at line 121 of file MoveSplineFlag.h.
Referenced by Movement::MoveSpline::isFacingTarget(), Movement::MoveSpline::ToString(), and Movement::PacketBuilder::WriteCreate().
flying
bool Movement::MoveSplineFlag::flying
Definition at line 113 of file MoveSplineFlag.h.
Referenced by Movement::MoveSplineInit::MoveSplineInit(), and Movement::MoveSplineInit::SetFly().
frozen
bool Movement::MoveSplineFlag::frozen
Definition at line 126 of file MoveSplineFlag.h.
no_spline
bool Movement::MoveSplineFlag::no_spline
Definition at line 114 of file MoveSplineFlag.h.
runmode
bool Movement::MoveSplineFlag::runmode
Definition at line 112 of file MoveSplineFlag.h.
Referenced by Movement::MoveSplineInit::Launch(), Movement::MoveSplineInit::MoveSplineInit(), and Movement::MoveSplineInit::SetWalk().
unknown12
bool Movement::MoveSplineFlag::unknown12
Definition at line 115 of file MoveSplineFlag.h.
unknown13
bool Movement::MoveSplineFlag::unknown13
Definition at line 116 of file MoveSplineFlag.h.
unknown14
bool Movement::MoveSplineFlag::unknown14
Definition at line 117 of file MoveSplineFlag.h.
unknown15
bool Movement::MoveSplineFlag::unknown15
Definition at line 118 of file MoveSplineFlag.h.
unknown16
bool Movement::MoveSplineFlag::unknown16
Definition at line 119 of file MoveSplineFlag.h.
unknown19
bool Movement::MoveSplineFlag::unknown19
Definition at line 123 of file MoveSplineFlag.h.
unknown23
bool Movement::MoveSplineFlag::unknown23
Definition at line 127 of file MoveSplineFlag.h.
unknown24
bool Movement::MoveSplineFlag::unknown24
Definition at line 128 of file MoveSplineFlag.h.
unknown25
bool Movement::MoveSplineFlag::unknown25
Definition at line 129 of file MoveSplineFlag.h.
unknown26
bool Movement::MoveSplineFlag::unknown26
Definition at line 130 of file MoveSplineFlag.h.
unknown27
bool Movement::MoveSplineFlag::unknown27
Definition at line 131 of file MoveSplineFlag.h.
unknown28
bool Movement::MoveSplineFlag::unknown28
Definition at line 132 of file MoveSplineFlag.h.
unknown29
bool Movement::MoveSplineFlag::unknown29
Definition at line 133 of file MoveSplineFlag.h.
unknown3
bool Movement::MoveSplineFlag::unknown3
Definition at line 106 of file MoveSplineFlag.h.
unknown30
bool Movement::MoveSplineFlag::unknown30
Definition at line 134 of file MoveSplineFlag.h.
unknown31
bool Movement::MoveSplineFlag::unknown31
Definition at line 135 of file MoveSplineFlag.h.
unknown4
bool Movement::MoveSplineFlag::unknown4
Definition at line 107 of file MoveSplineFlag.h.
unknown5
bool Movement::MoveSplineFlag::unknown5
Definition at line 108 of file MoveSplineFlag.h.
unknown6
bool Movement::MoveSplineFlag::unknown6
Definition at line 109 of file MoveSplineFlag.h.
unknown7
bool Movement::MoveSplineFlag::unknown7
Definition at line 110 of file MoveSplineFlag.h.
unknown8
bool Movement::MoveSplineFlag::unknown8
Definition at line 111 of file MoveSplineFlag.h.
The documentation for this class was generated from the following files:
MoveSplineFlag.h
util.cpp