CMaNGOS_TBC: MaNGOS::AnyPlayerInObjectRangeWithAuraCheck Class Reference
MaNGOS::AnyPlayerInObjectRangeWithAuraCheck Class Reference
#include <GridNotifiers.h>
Public Member Functions
AnyPlayerInObjectRangeWithAuraCheck (WorldObject const *obj, float range, uint32 spellId)
WorldObject const & GetFocusObject () const
bool operator() (Player *u)
Private Attributes
WorldObject const * i_obj
float i_range
uint32 i_spellId
Detailed Description
Definition at line 1385 of file GridNotifiers.h.
Constructor & Destructor Documentation
AnyPlayerInObjectRangeWithAuraCheck()
MaNGOS::AnyPlayerInObjectRangeWithAuraCheck::AnyPlayerInObjectRangeWithAuraCheck (WorldObject const * obj, float range, uint32 spellId) inline
Definition at line 1388 of file GridNotifiers.h.
Member Function Documentation
GetFocusObject()
WorldObject const& MaNGOS::AnyPlayerInObjectRangeWithAuraCheck::GetFocusObject () const inline
Definition at line 1390 of file GridNotifiers.h.
References i_obj.
operator()()
bool MaNGOS::AnyPlayerInObjectRangeWithAuraCheck::operator() (Player * u) inline
Definition at line 1391 of file GridNotifiers.h.
References Unit::HasAura(), i_obj, i_range, i_spellId, Unit::IsAlive(), and WorldObject::IsWithinDistInMap().
Field Documentation
i_obj
WorldObject const* MaNGOS::AnyPlayerInObjectRangeWithAuraCheck::i_obj private
Definition at line 1398 of file GridNotifiers.h.
Referenced by GetFocusObject(), and operator()().
i_range
float MaNGOS::AnyPlayerInObjectRangeWithAuraCheck::i_range private
Definition at line 1399 of file GridNotifiers.h.
Referenced by operator()().
i_spellId
uint32 MaNGOS::AnyPlayerInObjectRangeWithAuraCheck::i_spellId private
Definition at line 1400 of file GridNotifiers.h.
Referenced by operator()().
The documentation for this class was generated from the following file:
GridNotifiers.h