CMaNGOS_TBC: DungeonResetScheduler Class Reference
DungeonResetScheduler Class Reference
#include <MapPersistentStateMgr.h>
Public Member Functions
DungeonResetScheduler (MapPersistentStateManager &mgr)
void LoadResetTimes ()
time_t GetResetTimeFor (uint32 mapid)
void SetResetTimeFor (uint32 mapid, time_t t)
void ScheduleReset (bool add, time_t time, DungeonResetEvent event)
void Update ()
void ResetAllRaid ()
Static Public Member Functions
static uint32 GetMaxResetTimeFor (InstanceTemplate const *temp)
static time_t CalculateNextResetTime (InstanceTemplate const *temp, time_t prevResetTime)
Private Types
typedef std::vector< time_t > ResetTimeVector
typedef std::multimap< time_t, DungeonResetEvent > ResetTimeQueue
Private Attributes
MapPersistentStateManager & m_InstanceSaves
ResetTimeVector m_resetTimeByMapId
ResetTimeQueue m_resetTimeQueue
Detailed Description
Definition at line 291 of file MapPersistentStateMgr.h.
Member Typedef Documentation
ResetTimeQueue
typedef std::multimap< time_t , DungeonResetEvent > DungeonResetScheduler::ResetTimeQueue private
Definition at line 320 of file MapPersistentStateMgr.h.
ResetTimeVector
typedef std::vector< time_t > DungeonResetScheduler::ResetTimeVector private
Definition at line 317 of file MapPersistentStateMgr.h.
Constructor & Destructor Documentation
DungeonResetScheduler()
DungeonResetScheduler::DungeonResetScheduler (MapPersistentStateManager & mgr) inline explicit
Definition at line 294 of file MapPersistentStateMgr.h.
Member Function Documentation
CalculateNextResetTime()
time_t DungeonResetScheduler::CalculateNextResetTime (InstanceTemplate const * temp, time_t prevResetTime) static
Definition at line 355 of file MapPersistentStateMgr.cpp.
References CONFIG_UINT32_INSTANCE_RESET_TIME_HOUR, DAY, GetMaxResetTimeFor(), HOUR, MINUTE, and sWorld.
Referenced by MapPersistentStateManager::_ResetOrWarnAll(), and Update().
GetMaxResetTimeFor()
uint32 DungeonResetScheduler::GetMaxResetTimeFor (InstanceTemplate const * temp) static
Definition at line 347 of file MapPersistentStateMgr.cpp.
References DAY, and InstanceTemplate::reset_delay.
Referenced by CalculateNextResetTime(), Map::GetMaxResetDelay(), and LoadResetTimes().
GetResetTimeFor()
time_t DungeonResetScheduler::GetResetTimeFor (uint32 mapid) inline
Definition at line 298 of file MapPersistentStateMgr.h.
References m_resetTimeByMapId.
Referenced by MapPersistentStateManager::AddPersistentState(), LoadResetTimes(), and Update().
LoadResetTimes()
void DungeonResetScheduler::LoadResetTimes ()
Definition at line 362 of file MapPersistentStateMgr.cpp.
References MapPersistentStateManager::_CleanupExpiredInstancesAtTime(), CharacterDatabase, CONFIG_UINT32_ARENA_FIRST_RESET_DAY, CONFIG_UINT32_INSTANCE_RESET_TIME_HOUR, CONFIG_UINT32_QUEST_DAILY_RESET_HOUR, DAY, Database::DirectPExecute(), QueryResult::Fetch(), ObjectMgr::GetInstanceTemplate(), SQLStorageBase::GetMaxEntry(), GetMaxResetTimeFor(), GetResetTimeFor(), Field::GetUInt32(), Field::GetUInt64(), MapEntry::HasResetTime(), HOUR, MapEntry::IsDungeon(), m_InstanceSaves, m_resetTimeByMapId, InstanceTemplate::map, QueryResult::NextRow(), Database::Query(), RESET_EVENT_INFORM_1, RESET_EVENT_INFORM_LAST, RESET_EVENT_NORMAL_DUNGEON, resetEventTypeDelay, ScheduleReset(), SetResetTimeFor(), sInstanceTemplate, sLog, sMapPersistentStateMgr, sMapStore, sWorld, and UI64FMTD.
Referenced by MapPersistentStateManager::CleanupInstances().
ResetAllRaid()
void DungeonResetScheduler::ResetAllRaid ()
Definition at line 604 of file MapPersistentStateMgr.cpp.
References m_resetTimeQueue, RESET_EVENT_FORCED_INFORM_1, RESET_EVENT_NORMAL_DUNGEON, resetEventTypeDelay, SetResetTimeFor(), and DungeonResetEvent::type.
ScheduleReset()
void DungeonResetScheduler::ScheduleReset (bool add, time_t time, DungeonResetEvent event)
Definition at line 518 of file MapPersistentStateMgr.cpp.
References DungeonResetEvent::instanceId, m_resetTimeQueue, DungeonResetEvent::mapid, sLog, and DungeonResetEvent::type.
Referenced by MapPersistentStateManager::AddPersistentState(), LoadResetTimes(), and Update().
SetResetTimeFor()
void DungeonResetScheduler::SetResetTimeFor (uint32 mapid, time_t t) inline
Definition at line 303 of file MapPersistentStateMgr.h.
References m_resetTimeByMapId.
Referenced by LoadResetTimes(), ResetAllRaid(), and Update().
Update()
void DungeonResetScheduler::Update ()
Definition at line 553 of file MapPersistentStateMgr.cpp.
References MapPersistentStateManager::_ResetInstance(), MapPersistentStateManager::_ResetOrWarnAll(), CalculateNextResetTime(), CharacterDatabase, Database::DirectPExecute(), ObjectMgr::GetInstanceTemplate(), GetResetTimeFor(), m_InstanceSaves, m_resetTimeQueue, MANGOS_ASSERT, RESET_EVENT_FORCED_INFORM_LAST, RESET_EVENT_INFORM_1, RESET_EVENT_INFORM_LAST, RESET_EVENT_NORMAL_DUNGEON, resetEventTypeDelay, ScheduleReset(), SetResetTimeFor(), and UI64FMTD.
Referenced by MapPersistentStateManager::Update().
Field Documentation
m_InstanceSaves
MapPersistentStateManager& DungeonResetScheduler::m_InstanceSaves private
Definition at line 314 of file MapPersistentStateMgr.h.
Referenced by LoadResetTimes(), and Update().
m_resetTimeByMapId
ResetTimeVector DungeonResetScheduler::m_resetTimeByMapId private
Definition at line 318 of file MapPersistentStateMgr.h.
Referenced by GetResetTimeFor(), LoadResetTimes(), and SetResetTimeFor().
m_resetTimeQueue
ResetTimeQueue DungeonResetScheduler::m_resetTimeQueue private
Definition at line 321 of file MapPersistentStateMgr.h.
Referenced by ResetAllRaid(), ScheduleReset(), and Update().
The documentation for this class was generated from the following files:
MapPersistentStateMgr.h
MapPersistentStateMgr.cpp