CMaNGOS_TBC: IdGenerator< T > Class Template Reference
IdGenerator< T > Class Template Reference
#include <ObjectMgr.h>
Public Member Functions
IdGenerator (char const *_name)
void Set (T val)
T Generate ()
T GetNextAfterMaxUsed () const
Private Attributes
char const * m_name
T m_nextGuid
Detailed Description
template<typename T>
class IdGenerator< T >
Definition at line 423 of file ObjectMgr.h.
Constructor & Destructor Documentation
IdGenerator()
template<typename T > IdGenerator< T >::IdGenerator (char const * _name) inline explicit
Definition at line 426 of file ObjectMgr.h.
Member Function Documentation
Generate()
template<typename T > template uint64 IdGenerator< T >::Generate ()
Definition at line 122 of file ObjectMgr.cpp.
References ERROR_EXIT_CODE, sLog, and World::StopNow().
Referenced by ObjectMgr::GenerateArenaTeamId(), ObjectMgr::GenerateAuctionID(), ObjectMgr::GenerateGuildId(), ObjectMgr::GenerateItemTextID(), ObjectMgr::GenerateMailID(), and ObjectMgr::GeneratePetNumber().
GetNextAfterMaxUsed()
template<typename T > T IdGenerator< T >::GetNextAfterMaxUsed () const inline
Definition at line 433 of file ObjectMgr.h.
References IdGenerator< T >::m_nextGuid.
Referenced by ObjectMgr::LoadPetNumber().
Set()
template<typename T > void IdGenerator< T >::Set (T val) inline
Definition at line 429 of file ObjectMgr.h.
References IdGenerator< T >::m_nextGuid.
Referenced by ObjectMgr::LoadPetNumber(), and ObjectMgr::SetHighestGuids().
Field Documentation
m_name
template<typename T > char const* IdGenerator< T >::m_name private
Definition at line 436 of file ObjectMgr.h.
m_nextGuid
template<typename T > T IdGenerator< T >::m_nextGuid private
Definition at line 437 of file ObjectMgr.h.
Referenced by IdGenerator< T >::GetNextAfterMaxUsed(), and IdGenerator< T >::Set().
The documentation for this class was generated from the following files:
ObjectMgr.h
ObjectMgr.cpp