CMaNGOS_TBC: PlayerbotMageAI Class Reference
PlayerbotMageAI Class Reference
#include <PlayerbotMageAI.h>
Public Member Functions
PlayerbotMageAI (Player &master, Player &bot, PlayerbotAI &ai)
virtual ~PlayerbotMageAI ()
CombatManeuverReturns DoFirstCombatManeuver (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuver (Unit *pTarget) override
uint32 Neutralize (uint8 creatureType) override
void DoNonCombatActions () override
Private Member Functions
CombatManeuverReturns DoFirstCombatManeuverPVE (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuverPVE (Unit *pTarget) override
CombatManeuverReturns DoFirstCombatManeuverPVP (Unit *pTarget) override
CombatManeuverReturns DoNextCombatManeuverPVP (Unit *pTarget) override
Item * FindManaGem () const
CombatManeuverReturns CastSpell (uint32 nextAction, Unit *pTarget=nullptr)
CombatManeuverReturns DispelPlayer (Player *target) override
uint8 CheckFrostCooldowns ()
Private Member Functions inherited from PlayerbotClassAI
PlayerbotClassAI (Player &master, Player &bot, PlayerbotAI &ai)
virtual ~PlayerbotClassAI ()
virtual bool CanPull ()
virtual bool Pull ()
bool EatDrinkBandage (bool bMana=true, unsigned char foodPercent=50, unsigned char drinkPercent=50, unsigned char bandagePercent=70)
bool CastHoTOnTank ()
JOB_TYPE GetBotJob (Player *target)
JOB_TYPE GetTargetJob (Player *target)
time_t GetWaitUntil ()
void SetWait (uint8 t)
void ClearWait ()
CombatManeuverReturns CastSpellNoRanged (uint32 nextAction, Unit *pTarget)
CombatManeuverReturns CastSpellWand (uint32 nextAction, Unit *pTarget, uint32 SHOOT)
virtual CombatManeuverReturns HealPlayer (Player *target)
virtual CombatManeuverReturns ResurrectPlayer (Player *target)
CombatManeuverReturns Buff (bool(*BuffHelper)(PlayerbotAI *, uint32, Unit *), uint32 spellId, uint32 type=JOB_ALL, bool mustBeOOC=true)
Buff() return CombatManeuverReturns Returns RETURN_CONTINUE and buff unit target if it meets criteria to be buffed by bot with spell, else returns RETURN_NO_ACTION_OK.
bool FindTargetAndHeal ()
FindTargetAndHeal() return bool Returns true if a unit in need of healing was found and healed.
bool NeedGroupBuff (uint32 groupBuffSpellId, uint32 singleBuffSpellId)
NeedGroupBuff() return boolean Returns true if more than two targets in the bot's group need the group buff, else returns false.
Player * GetHealTarget (JOB_TYPE type=JOB_ALL, bool onlyPickFromSameGroup=false)
GetHealTarget() return Unit* Returns unit to be healed.
Player * GetDispelTarget (DispelType dispelType, JOB_TYPE type=JOB_ALL, bool bMustBeOOC=false)
GetDispelTarget() return Unit* Returns unit to be dispelled.
Player * GetResurrectionTarget (JOB_TYPE type=JOB_ALL, bool bMustBeOOC=true)
bool FleeFromAoEIfCan (uint32 spellId, Unit *pTarget)
FleeFromAoEIfCan() return boolean Check if the bot can move out of the hostile AoE spell then try to find a proper destination and move towards it The AoE is assumed to be centered on the current bot location (this is the case most of the time)
bool FleeFromTrapGOIfCan (uint32 goEntry, Unit *pTarget)
FleeFromTrapGOIfCan() return boolean Check if the bot can move from a hostile nearby trap, then try to find a proper destination and move towards it.
bool FleeFromNpcWithAuraIfCan (uint32 NpcEntry, uint32 spellId, Unit *pTarget)
FleeFromNpcWithAuraIfCan() return boolean Check if the bot can move from a creature having a specific aura, then try to find a proper destination and move towards it.
bool FleeFromPointIfCan (uint32 radius, Unit *pTarget, float x0, float y0, float z0, float forcedAngle=0.0f)
FleeFromPointIfCan() return boolean Check if the bot can move from a provided point (x, y, z) to given distance radius.
Static Private Member Functions
static bool BuffHelper (PlayerbotAI *ai, uint32 spellId, Unit *target)
Private Attributes
uint32 ARCANE_MISSILES
uint32 ARCANE_EXPLOSION
uint32 COUNTERSPELL
uint32 SLOW
uint32 ARCANE_BLAST
uint32 EVOCATION
uint32 POLYMORPH
uint32 PRESENCE_OF_MIND
uint32 ARCANE_POWER
uint32 SHOOT
uint32 FIREBALL
uint32 FIRE_BLAST
uint32 FLAMESTRIKE
uint32 SCORCH
uint32 FIRE_VULNERABILITY
uint32 IMPROVED_SCORCH
uint32 PYROBLAST
uint32 BLAST_WAVE
uint32 COMBUSTION
uint32 DRAGONS_BREATH
uint32 FIRE_WARD
uint32 FROSTBOLT
uint32 FROST_NOVA
uint32 BLIZZARD
uint32 ICY_VEINS
uint32 CONE_OF_COLD
uint32 ICE_BARRIER
uint32 SUMMON_WATER_ELEMENTAL
uint32 ICE_LANCE
uint32 FROST_WARD
uint32 ICE_BLOCK
uint32 COLD_SNAP
uint32 FROST_ARMOR
uint32 ICE_ARMOR
uint32 MAGE_ARMOR
uint32 MOLTEN_ARMOR
uint32 ARCANE_INTELLECT
uint32 ARCANE_BRILLIANCE
uint32 MANA_SHIELD
uint32 DAMPEN_MAGIC
uint32 AMPLIFY_MAGIC
uint32 MAGE_REMOVE_CURSE
uint32 ARCANE_TORRENT
uint32 GIFT_OF_THE_NAARU
uint32 STONEFORM
uint32 ESCAPE_ARTIST
uint32 PERCEPTION
uint32 SHADOWMELD
uint32 BLOOD_FURY
uint32 WAR_STOMP
uint32 BERSERKING
uint32 WILL_OF_THE_FORSAKEN
uint32 CONJURE_WATER
uint32 CONJURE_FOOD
uint32 CONJURE_MANA_GEM
Private Attributes inherited from PlayerbotClassAI
uint8 m_MinHealthPercentTank
uint8 m_MinHealthPercentHealer
uint8 m_MinHealthPercentDPS
uint8 m_MinHealthPercentMaster
time_t m_WaitUntil
Player & m_master
Player & m_bot
PlayerbotAI & m_ai
uint32 RECENTLY_BANDAGED
Detailed Description
Definition at line 106 of file PlayerbotMageAI.h.
Constructor & Destructor Documentation
PlayerbotMageAI()
PlayerbotMageAI::PlayerbotMageAI (Player & master, Player & bot, PlayerbotAI & ai)
Definition at line 23 of file PlayerbotMageAI.cpp.
References AMPLIFY_MAGIC, AMPLIFY_MAGIC_1, ARCANE_BLAST, ARCANE_BLAST_1, ARCANE_BRILLIANCE, ARCANE_BRILLIANCE_1, ARCANE_EXPLOSION, ARCANE_EXPLOSION_1, ARCANE_INTELLECT, ARCANE_INTELLECT_1, ARCANE_MISSILES, ARCANE_MISSILES_1, ARCANE_POWER, ARCANE_POWER_1, ARCANE_TORRENT, ARCANE_TORRENT_MANA_CLASSES, BERSERKING, BERSERKING_ALL, BLAST_WAVE, BLAST_WAVE_1, BLIZZARD, BLIZZARD_1, COLD_SNAP, COLD_SNAP_1, COMBUSTION, COMBUSTION_1, CONE_OF_COLD, CONE_OF_COLD_1, CONJURE_FOOD, CONJURE_FOOD_1, CONJURE_MANA_GEM, CONJURE_MANA_GEM_1, CONJURE_WATER, CONJURE_WATER_1, COUNTERSPELL, COUNTERSPELL_1, DAMPEN_MAGIC, DAMPEN_MAGIC_1, DRAGONS_BREATH, DRAGONS_BREATH_1, ESCAPE_ARTIST, ESCAPE_ARTIST_ALL, EVOCATION, EVOCATION_1, FIRE_BLAST, FIRE_BLAST_1, FIRE_VULNERABILITY, FIRE_WARD, FIRE_WARD_1, FIREBALL, FIREBALL_1, FLAMESTRIKE, FLAMESTRIKE_1, FROST_ARMOR, FROST_ARMOR_1, FROST_NOVA, FROST_NOVA_1, FROST_WARD, FROST_WARD_1, FROSTBOLT, FROSTBOLT_1, GIFT_OF_THE_NAARU, GIFT_OF_THE_NAARU_ALL, ICE_ARMOR, ICE_ARMOR_1, ICE_BARRIER, ICE_BARRIER_1, ICE_BLOCK, ICE_BLOCK_1, ICE_LANCE, ICE_LANCE_1, ICY_VEINS, ICY_VEINS_1, IMPROVED_SCORCH, PlayerbotAI::initSpell(), PlayerbotClassAI::m_ai, MAGE_ARMOR, MAGE_ARMOR_1, MAGE_REMOVE_CURSE, MANA_SHIELD, MANA_SHIELD_1, MOLTEN_ARMOR, MOLTEN_ARMOR_1, PERCEPTION, PERCEPTION_ALL, POLYMORPH, POLYMORPH_1, PRESENCE_OF_MIND, PRESENCE_OF_MIND_1, PYROBLAST, PYROBLAST_1, PlayerbotClassAI::RECENTLY_BANDAGED, REMOVE_CURSE_MAGE_1, SCORCH, SCORCH_1, SHOOT, SHOOT_2, SLOW, SLOW_1, SUMMON_WATER_ELEMENTAL, SUMMON_WATER_ELEMENTAL_1, uiImprovedScorch, WILL_OF_THE_FORSAKEN, and WILL_OF_THE_FORSAKEN_ALL.
~PlayerbotMageAI()
PlayerbotMageAI::~PlayerbotMageAI () virtual
Definition at line 91 of file PlayerbotMageAI.cpp.
Member Function Documentation
BuffHelper()
bool PlayerbotMageAI::BuffHelper (PlayerbotAI * ai, uint32 spellId, Unit * target) static private
Definition at line 499 of file PlayerbotMageAI.cpp.
References PlayerbotAI::Buff(), Unit::GetPet(), Unit::HasAuraType(), SPELL_AURA_MOD_UNATTACKABLE, and SPELL_CAST_OK.
Referenced by DoNonCombatActions().
CastSpell()
CombatManeuverReturns PlayerbotMageAI::CastSpell (uint32 nextAction, Unit * pTarget = nullptr) inline private
Definition at line 127 of file PlayerbotMageAI.h.
References PlayerbotClassAI::CastSpellWand(), and SHOOT.
Referenced by DispelPlayer(), and DoNextCombatManeuverPVE().
CheckFrostCooldowns()
uint8 PlayerbotMageAI::CheckFrostCooldowns () private
Definition at line 379 of file PlayerbotMageAI.cpp.
References CONE_OF_COLD, FROST_NOVA, FROST_WARD, ICE_BARRIER, ICE_BLOCK, WorldObject::IsSpellReady(), and PlayerbotClassAI::m_bot.
Referenced by DoNextCombatManeuverPVE().
DispelPlayer()
CombatManeuverReturns PlayerbotMageAI::DispelPlayer (Player * target) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 414 of file PlayerbotMageAI.cpp.
References CastSpell(), PlayerbotClassAI::DispelPlayer(), MAGE_REMOVE_CURSE, RETURN_CONTINUE, and RETURN_NO_ACTION_OK.
Referenced by DoNextCombatManeuverPVE(), and DoNonCombatActions().
DoFirstCombatManeuver()
CombatManeuverReturns PlayerbotMageAI::DoFirstCombatManeuver (Unit * pTarget) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 93 of file PlayerbotMageAI.cpp.
References PlayerbotAI::ClearGroupCombatOrder(), PlayerbotAI::CurrentTime(), DoFirstCombatManeuverPVE(), DoFirstCombatManeuverPVP(), PlayerbotAI::GetCombatOrder(), PlayerbotAI::GetScenarioType(), PlayerbotAI::GroupTankHoldsAggro(), PlayerbotAI::IsGroupReady(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_WaitUntil, PlayerbotAI::ORDERS_TEMP_WAIT_OOC, PlayerbotAI::ORDERS_TEMP_WAIT_TANKAGGRO, RETURN_NO_ACTION_OK, PlayerbotAI::SCENARIO_PVE, PlayerbotAI::SCENARIO_PVE_ELITE, PlayerbotAI::SCENARIO_PVE_RAID, PlayerbotAI::SCENARIO_PVP_ARENA, PlayerbotAI::SCENARIO_PVP_BG, PlayerbotAI::SCENARIO_PVP_DUEL, and PlayerbotAI::SCENARIO_PVP_OPENWORLD.
DoFirstCombatManeuverPVE()
CombatManeuverReturns PlayerbotMageAI::DoFirstCombatManeuverPVE (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 132 of file PlayerbotMageAI.cpp.
References RETURN_NO_ACTION_OK.
Referenced by DoFirstCombatManeuver().
DoFirstCombatManeuverPVP()
CombatManeuverReturns PlayerbotMageAI::DoFirstCombatManeuverPVP (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 137 of file PlayerbotMageAI.cpp.
References RETURN_NO_ACTION_OK.
Referenced by DoFirstCombatManeuver().
DoNextCombatManeuver()
CombatManeuverReturns PlayerbotMageAI::DoNextCombatManeuver (Unit * pTarget) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 142 of file PlayerbotMageAI.cpp.
References DoNextCombatManeuverPVE(), DoNextCombatManeuverPVP(), PlayerbotAI::FaceTarget(), PlayerbotAI::GetScenarioType(), PlayerbotClassAI::m_ai, PlayerbotAI::SCENARIO_PVE, PlayerbotAI::SCENARIO_PVE_ELITE, PlayerbotAI::SCENARIO_PVE_RAID, PlayerbotAI::SCENARIO_PVP_ARENA, PlayerbotAI::SCENARIO_PVP_BG, PlayerbotAI::SCENARIO_PVP_DUEL, and PlayerbotAI::SCENARIO_PVP_OPENWORLD.
DoNextCombatManeuverPVE()
CombatManeuverReturns PlayerbotMageAI::DoNextCombatManeuverPVE (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 162 of file PlayerbotMageAI.cpp.
References PlayerbotAI::AIT_HIGHESTTHREAT, PlayerbotAI::AIT_VICTIMSELF, ARCANE_BLAST, ARCANE_EXPLOSION, ARCANE_MISSILES, ARCANE_POWER, BLAST_WAVE, Unit::CanReachWithMeleeAttack(), PlayerbotAI::CastSpell(), CastSpell(), CheckFrostCooldowns(), CLEARCASTING_1, COLD_SNAP, PlayerbotAI::COMBAT_MELEE, PlayerbotAI::COMBAT_RANGED, COMBUSTION, CONE_OF_COLD, COUNTERSPELL, CREATURE_TYPE_BEAST, CREATURE_TYPE_HUMANOID, CreatureInfo::CreatureType, DISPEL_CURSE, DispelPlayer(), DRAGONS_BREATH, EFFECT_INDEX_0, EFFECT_INDEX_1, EVOCATION, PlayerbotAI::FaceTarget(), PlayerbotAI::FindAttacker(), FindManaGem(), FIRE_BLAST, FIRE_VULNERABILITY, FIRE_WARD, FIREBALL, FROST_NOVA, FROST_WARD, FROSTBOLT, PlayerbotAI::GetAttackerCount(), PlayerbotAI::GetCombatOrder(), PlayerbotAI::GetCombatStyle(), Creature::GetCreatureInfo(), PlayerbotClassAI::GetDispelTarget(), Unit::GetHealthPercent(), PlayerbotAI::GetHealthPercent(), PlayerbotAI::GetManaPercent(), Unit::GetSpellAuraHolder(), SpellAuraHolder::GetStackAmount(), Unit::GetVictim(), Player::GetWeaponForAttack(), Unit::HasAura(), PlayerbotAI::HasDispelOrder(), ICE_BARRIER, ICE_BLOCK, ICE_LANCE, ICY_VEINS, IMPROVED_SCORCH, PlayerbotAI::In_Reach(), PlayerbotAI::IsElite(), PlayerbotAI::IsImmuneToSchool(), PlayerbotAI::IsNeutralized(), Unit::IsNonMeleeSpellCasted(), WorldObject::IsSpellReady(), PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, MAGE_SPEC_ARCANE, MAGE_SPEC_FIRE, MAGE_SPEC_FROST, MANA_SHIELD, PlayerbotAI::ORDERS_RESIST_FIRE, PlayerbotAI::ORDERS_RESIST_FROST, POLYMORPH, PRESENCE_OF_MIND, PYROBLAST, RANGED_ATTACK, RETURN_CONTINUE, SCORCH, PlayerbotAI::SelfBuff(), PlayerbotAI::SetCombatStyle(), PlayerbotAI::SetIgnoreUpdateTime(), SHOOT, SLOW, SPELL_CAST_OK, SPELL_SCHOOL_MASK_ARCANE, SPELL_SCHOOL_MASK_FIRE, SPELL_SCHOOL_MASK_FROST, SUMMON_WATER_ELEMENTAL, and PlayerbotAI::UseItem().
Referenced by DoNextCombatManeuver(), and DoNextCombatManeuverPVP().
DoNextCombatManeuverPVP()
CombatManeuverReturns PlayerbotMageAI::DoNextCombatManeuverPVP (Unit * pTarget) override private virtual
Reimplemented from PlayerbotClassAI.
Definition at line 370 of file PlayerbotMageAI.cpp.
References PlayerbotAI::CastSpell(), DoNextCombatManeuverPVE(), FIREBALL, PlayerbotAI::In_Reach(), PlayerbotAI::IsImmuneToSchool(), PlayerbotClassAI::m_ai, RETURN_CONTINUE, SPELL_CAST_OK, and SPELL_SCHOOL_MASK_FIRE.
Referenced by DoNextCombatManeuver().
DoNonCombatActions()
void PlayerbotMageAI::DoNonCombatActions () override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 426 of file PlayerbotMageAI.cpp.
References ARCANE_BRILLIANCE, ARCANE_INTELLECT, PlayerbotClassAI::Buff(), BuffHelper(), PlayerbotAI::CanStore(), PlayerbotAI::CastSpell(), COMBUSTION, CONJURE_FOOD, CONJURE_MANA_GEM, CONJURE_WATER, DISPEL_CURSE, DispelPlayer(), PlayerbotClassAI::EatDrinkBandage(), PlayerbotAI::FindDrink(), PlayerbotAI::FindFood(), FindManaGem(), FROST_ARMOR, PlayerbotClassAI::GetDispelTarget(), PlayerbotAI::HasDispelOrder(), PlayerbotAI::HasSpellReagents(), ICE_ARMOR, WorldObject::IsSpellReady(), JOB_MANAONLY, PlayerbotClassAI::m_ai, PlayerbotClassAI::m_bot, MAGE_ARMOR, MOLTEN_ARMOR, PlayerbotClassAI::NeedGroupBuff(), RETURN_CONTINUE, PlayerbotAI::SelfBuff(), PlayerbotAI::SetIgnoreUpdateTime(), SPELL_CAST_OK, and PlayerbotAI::TellMaster().
FindManaGem()
Item * PlayerbotMageAI::FindManaGem () const private
Definition at line 402 of file PlayerbotMageAI.cpp.
References PlayerbotAI::FindConsumable(), PlayerbotClassAI::m_ai, and uPriorizedManaGemIds.
Referenced by DoNextCombatManeuverPVE(), and DoNonCombatActions().
Neutralize()
uint32 PlayerbotMageAI::Neutralize (uint8 creatureType) override virtual
Reimplemented from PlayerbotClassAI.
Definition at line 513 of file PlayerbotMageAI.cpp.
References CREATURE_TYPE_BEAST, CREATURE_TYPE_HUMANOID, PlayerbotClassAI::m_ai, POLYMORPH, and PlayerbotAI::TellMaster().
Field Documentation
AMPLIFY_MAGIC
uint32 PlayerbotMageAI::AMPLIFY_MAGIC private
Definition at line 184 of file PlayerbotMageAI.h.
Referenced by PlayerbotMageAI().
ARCANE_BLAST
uint32 PlayerbotMageAI::ARCANE_BLAST private
Definition at line 141 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
ARCANE_BRILLIANCE
uint32 PlayerbotMageAI::ARCANE_BRILLIANCE private
Definition at line 181 of file PlayerbotMageAI.h.
Referenced by DoNonCombatActions(), and PlayerbotMageAI().
ARCANE_EXPLOSION
uint32 PlayerbotMageAI::ARCANE_EXPLOSION private
Definition at line 138 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
ARCANE_INTELLECT
uint32 PlayerbotMageAI::ARCANE_INTELLECT private
Definition at line 180 of file PlayerbotMageAI.h.
Referenced by DoNonCombatActions(), and PlayerbotMageAI().
ARCANE_MISSILES
uint32 PlayerbotMageAI::ARCANE_MISSILES private
Definition at line 137 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
ARCANE_POWER
uint32 PlayerbotMageAI::ARCANE_POWER private
Definition at line 145 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
ARCANE_TORRENT
uint32 PlayerbotMageAI::ARCANE_TORRENT private
Definition at line 188 of file PlayerbotMageAI.h.
Referenced by PlayerbotMageAI().
BERSERKING
uint32 PlayerbotMageAI::BERSERKING private
Definition at line 196 of file PlayerbotMageAI.h.
Referenced by PlayerbotMageAI().
BLAST_WAVE
uint32 PlayerbotMageAI::BLAST_WAVE private
Definition at line 157 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
BLIZZARD
uint32 PlayerbotMageAI::BLIZZARD private
Definition at line 165 of file PlayerbotMageAI.h.
Referenced by PlayerbotMageAI().
BLOOD_FURY
uint32 PlayerbotMageAI::BLOOD_FURY private
Definition at line 194 of file PlayerbotMageAI.h.
COLD_SNAP
uint32 PlayerbotMageAI::COLD_SNAP private
Definition at line 173 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
COMBUSTION
uint32 PlayerbotMageAI::COMBUSTION private
Definition at line 158 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), DoNonCombatActions(), and PlayerbotMageAI().
CONE_OF_COLD
uint32 PlayerbotMageAI::CONE_OF_COLD private
Definition at line 167 of file PlayerbotMageAI.h.
Referenced by CheckFrostCooldowns(), DoNextCombatManeuverPVE(), and PlayerbotMageAI().
CONJURE_FOOD
uint32 PlayerbotMageAI::CONJURE_FOOD private
Definition at line 200 of file PlayerbotMageAI.h.
Referenced by DoNonCombatActions(), and PlayerbotMageAI().
CONJURE_MANA_GEM
uint32 PlayerbotMageAI::CONJURE_MANA_GEM private
Definition at line 201 of file PlayerbotMageAI.h.
Referenced by DoNonCombatActions(), and PlayerbotMageAI().
CONJURE_WATER
uint32 PlayerbotMageAI::CONJURE_WATER private
Definition at line 199 of file PlayerbotMageAI.h.
Referenced by DoNonCombatActions(), and PlayerbotMageAI().
COUNTERSPELL
uint32 PlayerbotMageAI::COUNTERSPELL private
Definition at line 139 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
DAMPEN_MAGIC
uint32 PlayerbotMageAI::DAMPEN_MAGIC private
Definition at line 183 of file PlayerbotMageAI.h.
Referenced by PlayerbotMageAI().
DRAGONS_BREATH
uint32 PlayerbotMageAI::DRAGONS_BREATH private
Definition at line 159 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
ESCAPE_ARTIST
uint32 PlayerbotMageAI::ESCAPE_ARTIST private
Definition at line 191 of file PlayerbotMageAI.h.
Referenced by PlayerbotMageAI().
EVOCATION
uint32 PlayerbotMageAI::EVOCATION private
Definition at line 142 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
FIRE_BLAST
uint32 PlayerbotMageAI::FIRE_BLAST private
Definition at line 151 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
FIRE_VULNERABILITY
uint32 PlayerbotMageAI::FIRE_VULNERABILITY private
Definition at line 154 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
FIRE_WARD
uint32 PlayerbotMageAI::FIRE_WARD private
Definition at line 160 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
FIREBALL
uint32 PlayerbotMageAI::FIREBALL private
Definition at line 150 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), DoNextCombatManeuverPVP(), and PlayerbotMageAI().
FLAMESTRIKE
uint32 PlayerbotMageAI::FLAMESTRIKE private
Definition at line 152 of file PlayerbotMageAI.h.
Referenced by PlayerbotMageAI().
FROST_ARMOR
uint32 PlayerbotMageAI::FROST_ARMOR private
Definition at line 176 of file PlayerbotMageAI.h.
Referenced by DoNonCombatActions(), and PlayerbotMageAI().
FROST_NOVA
uint32 PlayerbotMageAI::FROST_NOVA private
Definition at line 164 of file PlayerbotMageAI.h.
Referenced by CheckFrostCooldowns(), DoNextCombatManeuverPVE(), and PlayerbotMageAI().
FROST_WARD
uint32 PlayerbotMageAI::FROST_WARD private
Definition at line 171 of file PlayerbotMageAI.h.
Referenced by CheckFrostCooldowns(), DoNextCombatManeuverPVE(), and PlayerbotMageAI().
FROSTBOLT
uint32 PlayerbotMageAI::FROSTBOLT private
Definition at line 163 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
GIFT_OF_THE_NAARU
uint32 PlayerbotMageAI::GIFT_OF_THE_NAARU private
Definition at line 189 of file PlayerbotMageAI.h.
Referenced by PlayerbotMageAI().
ICE_ARMOR
uint32 PlayerbotMageAI::ICE_ARMOR private
Definition at line 177 of file PlayerbotMageAI.h.
Referenced by DoNonCombatActions(), and PlayerbotMageAI().
ICE_BARRIER
uint32 PlayerbotMageAI::ICE_BARRIER private
Definition at line 168 of file PlayerbotMageAI.h.
Referenced by CheckFrostCooldowns(), DoNextCombatManeuverPVE(), and PlayerbotMageAI().
ICE_BLOCK
uint32 PlayerbotMageAI::ICE_BLOCK private
Definition at line 172 of file PlayerbotMageAI.h.
Referenced by CheckFrostCooldowns(), DoNextCombatManeuverPVE(), and PlayerbotMageAI().
ICE_LANCE
uint32 PlayerbotMageAI::ICE_LANCE private
Definition at line 170 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
ICY_VEINS
uint32 PlayerbotMageAI::ICY_VEINS private
Definition at line 166 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
IMPROVED_SCORCH
uint32 PlayerbotMageAI::IMPROVED_SCORCH private
Definition at line 155 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
MAGE_ARMOR
uint32 PlayerbotMageAI::MAGE_ARMOR private
Definition at line 178 of file PlayerbotMageAI.h.
Referenced by DoNonCombatActions(), and PlayerbotMageAI().
MAGE_REMOVE_CURSE
uint32 PlayerbotMageAI::MAGE_REMOVE_CURSE private
Definition at line 185 of file PlayerbotMageAI.h.
Referenced by DispelPlayer(), and PlayerbotMageAI().
MANA_SHIELD
uint32 PlayerbotMageAI::MANA_SHIELD private
Definition at line 182 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
MOLTEN_ARMOR
uint32 PlayerbotMageAI::MOLTEN_ARMOR private
Definition at line 179 of file PlayerbotMageAI.h.
Referenced by DoNonCombatActions(), and PlayerbotMageAI().
PERCEPTION
uint32 PlayerbotMageAI::PERCEPTION private
Definition at line 192 of file PlayerbotMageAI.h.
Referenced by PlayerbotMageAI().
POLYMORPH
uint32 PlayerbotMageAI::POLYMORPH private
Definition at line 143 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), Neutralize(), and PlayerbotMageAI().
PRESENCE_OF_MIND
uint32 PlayerbotMageAI::PRESENCE_OF_MIND private
Definition at line 144 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
PYROBLAST
uint32 PlayerbotMageAI::PYROBLAST private
Definition at line 156 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
SCORCH
uint32 PlayerbotMageAI::SCORCH private
Definition at line 153 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
SHADOWMELD
uint32 PlayerbotMageAI::SHADOWMELD private
Definition at line 193 of file PlayerbotMageAI.h.
SHOOT
uint32 PlayerbotMageAI::SHOOT private
Definition at line 147 of file PlayerbotMageAI.h.
Referenced by CastSpell(), DoNextCombatManeuverPVE(), and PlayerbotMageAI().
SLOW
uint32 PlayerbotMageAI::SLOW private
Definition at line 140 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
STONEFORM
uint32 PlayerbotMageAI::STONEFORM private
Definition at line 190 of file PlayerbotMageAI.h.
SUMMON_WATER_ELEMENTAL
uint32 PlayerbotMageAI::SUMMON_WATER_ELEMENTAL private
Definition at line 169 of file PlayerbotMageAI.h.
Referenced by DoNextCombatManeuverPVE(), and PlayerbotMageAI().
WAR_STOMP
uint32 PlayerbotMageAI::WAR_STOMP private
Definition at line 195 of file PlayerbotMageAI.h.
WILL_OF_THE_FORSAKEN
uint32 PlayerbotMageAI::WILL_OF_THE_FORSAKEN private
Definition at line 197 of file PlayerbotMageAI.h.
Referenced by PlayerbotMageAI().
The documentation for this class was generated from the following files:
PlayerbotMageAI.h
PlayerbotMageAI.cpp