CMaNGOS_TBC: The mail system
The mail system
The mailing system in MaNGOS consists of mostly 4 files:
Files
file Mail.cpp
This file contains the code needed for MaNGOS to handle mails.
file Mail.h
This file contains the the headers needed for MaNGOS to handle mails.
file MailHandler.cpp
This file contains handlers for mail opcodes.
file MassMailMgr.cpp
This file contains the the code needed for MaNGOS to handle mass mails send in safe and perfomence not affecting way.
file MassMailMgr.h
This file contains the the headers needed for MaNGOS to handle mass mails send in safe and perfomence not affecting way.
Data Structures
class MailSender
A class to represent the sender of a mail.
class MailReceiver
A class to represent the receiver of a mail.
class MailDraft
The class to represent the draft of a mail.
struct MailItemInfo
Structure holding information about an item in the mail.
struct Mail
Structure that holds an actual mail.
struct MassMailerQueryHandler
class MassMailMgr
A class to represent the mail send factory to multiple (often all existing) characters.
Macros
#define MAIL_BODY_ITEM_TEMPLATE 8383
#define MAX_MAIL_ITEMS 12
The maximal amount of items a mail can contain.
#define MAX_INBOX_CLIENT_UI_CAPACITY 50
#define sMassMailMgr MaNGOS::Singleton<MassMailMgr>::Instance()
Typedefs
typedef std::vector< MailItemInfo > MailItemInfoVec
Enumerations
enum MailMessageType {
MAIL_NORMAL = 0 , MAIL_AUCTION = 2 , MAIL_CREATURE = 3 , MAIL_GAMEOBJECT = 4 ,
MAIL_ITEM = 5
}
The type of the mail.
enum MailCheckMask {
MAIL_CHECK_MASK_NONE = 0x00 , MAIL_CHECK_MASK_READ = 0x01 , MAIL_CHECK_MASK_RETURNED = 0x02 , MAIL_CHECK_MASK_COPIED = 0x04 ,
MAIL_CHECK_MASK_COD_PAYMENT = 0x08 , MAIL_CHECK_MASK_HAS_BODY = 0x10
}
A Mask representing the status of the mail.
enum MailStationery {
MAIL_STATIONERY_UNKNOWN = 1 , MAIL_STATIONERY_DEFAULT = 41 , MAIL_STATIONERY_GM = 61 , MAIL_STATIONERY_AUCTION = 62 ,
MAIL_STATIONERY_VAL = 64 , MAIL_STATIONERY_CHR = 65
}
The different types of Stationaries that exist for mails.
enum MailState { MAIL_STATE_UNCHANGED = 1 , MAIL_STATE_CHANGED = 2 , MAIL_STATE_DELETED = 3 }
Representation of the State of a mail.
enum MailAuctionAnswers {
AUCTION_OUTBIDDED = 0 , AUCTION_WON = 1 , AUCTION_SUCCESSFUL = 2 , AUCTION_EXPIRED = 3 ,
AUCTION_CANCELLED_TO_BIDDER = 4 , AUCTION_CANCELED = 5 , AUCTION_SALE_PENDING = 6
}
Answers contained in mails from auctionhouses.
Functions
INSTANTIATE_SINGLETON_1 (MassMailMgr)
MailSender::MailSender (Object *sender, MailStationery stationery=MAIL_STATIONERY_DEFAULT)
Creates a new MailSender object.
MailSender::MailSender (AuctionEntry *sender)
Creates a new MailSender object from an AuctionEntry.
MailReceiver::MailReceiver (Player *receiver)
Creates a new MailReceiver object.
MailReceiver::MailReceiver (Player *receiver, ObjectGuid receiver_guid)
Creates a new MailReceiver object with a specified GUID.
MailDraft::MailDraft (std::string subject, std::string text)
Creates a new MailDraft object using subject and contect texts.
MailDraft & MailDraft::SetSubjectAndBody (const std::string &subject, const std::string &text)
MailDraft & MailDraft::AddItem (Item *item)
Adds an item to the MailDraft.
bool MailDraft::prepareItems (Player *receiver)
called from SendMailTo for generate mailTemplateBase items
void MailDraft::deleteIncludedItems (bool inDB=false)
Deletes the items included in a MailDraft.
void MailDraft::CloneFrom (MailDraft const &draft)
Clone MailDraft from another MailDraft.
void MailDraft::SendReturnToSender (uint32 sender_acc, ObjectGuid sender_guid, ObjectGuid receiver_guid)
void MailDraft::SendMailTo (MailReceiver const &receiver, MailSender const &sender, MailCheckMask checked=MAIL_CHECK_MASK_NONE, uint32 deliver_delay=0)
Sends a mail.
void Mail::prepareTemplateItems (Player *receiver)
called from _LoadMails for generate mailTemplateBase items not generated for offline player
bool WorldSession::CheckMailBox (ObjectGuid guid) const
void WorldSession::HandleSendMail (WorldPacket &recv_data)
Handles the Packet sent by the client when sending a mail.
void WorldSession::HandleMailMarkAsRead (WorldPacket &recv_data)
Handles the Packet sent by the client when reading a mail.
void WorldSession::HandleMailDelete (WorldPacket &recv_data)
Handles the Packet sent by the client when deleting a mail.
void WorldSession::HandleMailReturnToSender (WorldPacket &recv_data)
Handles the Packet sent by the client when returning a mail to sender.
void WorldSession::HandleMailTakeItem (WorldPacket &recv_data)
Handles the packet sent by the client when taking an item from the mail.
void WorldSession::HandleMailTakeMoney (WorldPacket &recv_data)
Handles the packet sent by the client when taking money from the mail.
void WorldSession::HandleGetMailList (WorldPacket &recv_data)
Handles the packet sent by the client when requesting the current mail list.
void WorldSession::HandleItemTextQuery (WorldPacket &recv_data)
Handles the packet sent by the client when requesting information about the body of a mail.
void WorldSession::HandleMailCreateTextItem (WorldPacket &recv_data)
Handles the packet sent by the client when he copies the body a mail to his inventory.
void WorldSession::HandleQueryNextMailTime (WorldPacket &recv_data)
No idea when this is called.
void MassMailMgr::AddMassMailTask (MailDraft *mailProto, const MailSender &sender, uint32 raceMask)
And new mass mail task for raceMask filter applied to characters list.
void MassMailMgr::AddMassMailTask (MailDraft *mailProto, const MailSender &sender, char const *query)
And new mass mail task with SQL query text for fill receivers list.
void MassMailMgr::Update (bool sendall=false)
Next step in mass mail activity, send some amount mails from queued tasks.
void MassMailMgr::GetStatistic (uint32 &tasks, uint32 &mails, uint32 &needTime) const
Variables
struct MassMailerQueryHandler massMailerQueryHandler
Detailed Description
The mailing system in MaNGOS consists of mostly 4 files:
Mail.h
Mail.cpp
MassMailMgr.h
MassMailMgr.cpp
Macro Definition Documentation
MAIL_BODY_ITEM_TEMPLATE
#define MAIL_BODY_ITEM_TEMPLATE 8383
plain letter, A Dusty Unsent Letter: 889
Definition at line 47 of file Mail.h.
MAX_INBOX_CLIENT_UI_CAPACITY
#define MAX_INBOX_CLIENT_UI_CAPACITY 50
Definition at line 42 of file MailHandler.cpp.
MAX_MAIL_ITEMS
#define MAX_MAIL_ITEMS 12
The maximal amount of items a mail can contain.
Definition at line 49 of file Mail.h.
sMassMailMgr
#define sMassMailMgr MaNGOS::Singleton<MassMailMgr>::Instance()
Definition at line 119 of file MassMailMgr.h.
Typedef Documentation
MailItemInfoVec
typedef std::vector<MailItemInfo> MailItemInfoVec
Definition at line 287 of file Mail.h.
Enumeration Type Documentation
MailAuctionAnswers
enum MailAuctionAnswers
Answers contained in mails from auctionhouses.
Enumerator
AUCTION_OUTBIDDED
AUCTION_WON
AUCTION_SUCCESSFUL
AUCTION_EXPIRED
AUCTION_CANCELLED_TO_BIDDER
AUCTION_CANCELED
AUCTION_SALE_PENDING
Definition at line 100 of file Mail.h.
MailCheckMask
enum MailCheckMask
A Mask representing the status of the mail.
Enumerator
MAIL_CHECK_MASK_NONE
MAIL_CHECK_MASK_READ
Nothing.
MAIL_CHECK_MASK_RETURNED
This mail was read.
MAIL_CHECK_MASK_COPIED
This mail was returned. No allow return mail.
MAIL_CHECK_MASK_COD_PAYMENT
This mail was copied. No allow make item copy from mail text.
MAIL_CHECK_MASK_HAS_BODY
This mail is payable on delivery.
Definition at line 65 of file Mail.h.
MailMessageType
enum MailMessageType
The type of the mail.
A mail can have 5 Different Types.
Enumerator
MAIL_NORMAL
MAIL_AUCTION
MAIL_CREATURE
MAIL_GAMEOBJECT
client send CMSG_CREATURE_QUERY on this mailmessagetype
MAIL_ITEM
client send CMSG_GAMEOBJECT_QUERY on this mailmessagetype
Definition at line 54 of file Mail.h.
MailState
enum MailState
Representation of the State of a mail.
Enumerator
MAIL_STATE_UNCHANGED
MAIL_STATE_CHANGED
MAIL_STATE_DELETED
Definition at line 91 of file Mail.h.
MailStationery
enum MailStationery
The different types of Stationaries that exist for mails.
They have been gathered from Stationery.dbc
Enumerator
MAIL_STATIONERY_UNKNOWN
MAIL_STATIONERY_DEFAULT
MAIL_STATIONERY_GM
MAIL_STATIONERY_AUCTION
MAIL_STATIONERY_VAL
MAIL_STATIONERY_CHR
Definition at line 79 of file Mail.h.
Function Documentation
AddItem()
MailDraft & MailDraft::AddItem (Item * item)
Adds an item to the MailDraft.
Parameters
item The item to be added to the MailDraft.
Returns
the MailDraft the item was added to.
Definition at line 128 of file Mail.cpp.
References Object::GetGUIDLow(), and MailDraft::m_items.
Referenced by Player::_LoadInventory(), Player::AutoUnequipOffhandIfNeed(), MailDraft::CloneFrom(), Player::DeleteFromDB(), WorldSession::HandleAuctionRemoveItem(), WorldSession::HandleMailReturnToSender(), ChatHandler::HandleSendItemsHelper(), WorldSession::HandleSendMail(), AuctionHouseMgr::LoadAuctions(), MailDraft::prepareItems(), PlayerbotAI::RemoveAuction(), BattleGroundMgr::RewardArenaSeason(), AuctionHouseMgr::SendAuctionExpiredMail(), AuctionHouseMgr::SendAuctionWonMail(), and BattleGround::SendRewardMarkByMail().
AddMassMailTask() [1/2]
void MassMailMgr::AddMassMailTask (MailDraft * mailProto, const MailSender & sender, char const * query)
And new mass mail task with SQL query text for fill receivers list.
Parameters
mailProto prepared mail for clone and send to characters, will deleted in result call
queryStr SQL query for get guid list of receivers, first field in query result must be uint32 low guids list.
Note: this function safe to be called from Map::Update content/etc, real data add will executed in next tick after query results ready
Definition at line 69 of file MassMailMgr.cpp.
References Database::AsyncPQuery(), CharacterDatabase, MassMailerQueryHandler::HandleQueryCallback(), and massMailerQueryHandler.
AddMassMailTask() [2/2]
void MassMailMgr::AddMassMailTask (MailDraft * mailProto, const MailSender & sender, uint32 raceMask)
And new mass mail task for raceMask filter applied to characters list.
Parameters
mailProto prepared mail for clone and send to characters, will deleted in result call.
raceMask mask of races that must receive mail.
Note: this function safe to be called from Map::Update content/etc, real data add will executed in next tick after query results ready
Definition at line 38 of file MassMailMgr.cpp.
References RACEMASK_ALL_PLAYABLE.
CheckMailBox()
bool WorldSession::CheckMailBox (ObjectGuid guid) const
Definition at line 44 of file MailHandler.cpp.
References DEBUG_LOG, GAMEOBJECT_TYPE_MAILBOX, WorldSession::GetPlayer(), and ObjectGuid::GetString().
Referenced by WorldSession::HandleGetMailList(), WorldSession::HandleMailCreateTextItem(), WorldSession::HandleMailDelete(), WorldSession::HandleMailMarkAsRead(), WorldSession::HandleMailReturnToSender(), WorldSession::HandleMailTakeItem(), WorldSession::HandleMailTakeMoney(), and WorldSession::HandleSendMail().
CloneFrom()
void MailDraft::CloneFrom (MailDraft const & draft)
Clone MailDraft from another MailDraft.
Parameters
draft Point to source for draft cloning.
Definition at line 187 of file Mail.cpp.
References MailDraft::AddItem(), Item::CloneItem(), MailDraft::GetBodyId(), MailDraft::GetCOD(), Item::GetCount(), MailDraft::GetMailTemplateId(), MailDraft::GetMoney(), MailDraft::GetSubject(), MailDraft::m_bodyId, MailDraft::m_COD, MailDraft::m_items, MailDraft::m_mailTemplateId, MailDraft::m_mailTemplateItemsNeed, MailDraft::m_money, MailDraft::m_subject, MANGOS_ASSERT, Item::SaveToDB(), and sObjectMgr.
Referenced by MassMailMgr::Update().
deleteIncludedItems()
void MailDraft::deleteIncludedItems (bool inDB = false) private
Deletes the items included in a MailDraft.
Parameters
inDB A boolean specifying whether the change should be saved to the database or not.
Parameters
inDB = false
Definition at line 168 of file Mail.cpp.
References CharacterDatabase, Object::GetGUIDLow(), MailDraft::m_items, and Database::PExecute().
Referenced by MailDraft::SendMailTo(), and MailDraft::SendReturnToSender().
GetStatistic()
void MassMailMgr::GetStatistic (uint32 & tasks, uint32 & mails, uint32 & needTime) const
Definition at line 121 of file MassMailMgr.cpp.
References CONFIG_UINT32_MASS_MAILER_SEND_PER_TICK, IN_MILLISECONDS, MassMailMgr::m_massMails, and sWorld.
HandleGetMailList()
void WorldSession::HandleGetMailList (WorldPacket & recv_data)
Handles the packet sent by the client when requesting the current mail list.
It will send a list of all available mails in the players mailbox to the client.
Definition at line 576 of file MailHandler.cpp.
References WorldSession::_player, WorldSession::CheckMailBox(), DAY, Item::GetCount(), Item::GetEnchantmentCharges(), Item::GetEnchantmentDuration(), Item::GetEnchantmentId(), Object::GetEntry(), Object::GetGUIDLow(), Item::GetItemRandomPropertyId(), Item::GetItemSuffixFactor(), Player::GetMailBegin(), Player::GetMailEnd(), Player::GetMItem(), Item::GetSpellCharges(), Object::GetUInt32Value(), HIGHGUID_PLAYER, ITEM_FIELD_DURABILITY, ITEM_FIELD_MAXDURABILITY, MAIL_AUCTION, MAIL_CREATURE, MAIL_GAMEOBJECT, MAIL_ITEM, MAIL_NORMAL, MAIL_STATE_DELETED, MAX_INBOX_CLIENT_UI_CAPACITY, MAX_INSPECTED_ENCHANTMENT_SLOT, MAX_NETCLIENT_PACKET_SIZE, ByteBuffer::put(), WorldSession::SendPacket(), SMSG_MAIL_LIST_RESULT, Player::UpdateNextMailTimeAndUnreads(), and ByteBuffer::wpos().
HandleItemTextQuery()
void WorldSession::HandleItemTextQuery (WorldPacket & recv_data)
Handles the packet sent by the client when requesting information about the body of a mail.
This function is called when client needs mail message body, or when player clicks on item which has some flag set
TODO: some check needed, if player has item with guid mailId, or has mail with id mailId
Definition at line 686 of file MailHandler.cpp.
References DEBUG_LOG, WorldSession::SendPacket(), SMSG_ITEM_TEXT_QUERY_RESPONSE, and sObjectMgr.
HandleMailCreateTextItem()
void WorldSession::HandleMailCreateTextItem (WorldPacket & recv_data)
Handles the packet sent by the client when he copies the body a mail to his inventory.
When a player copies the body of a mail to his inventory this method is called. It will create a new item with the text of the mail and store it in the players inventory (if possible).
Definition at line 711 of file MailHandler.cpp.
References WorldSession::_player, Player::CanStoreItem(), Mail::checked, WorldSession::CheckMailBox(), MailTemplateEntry::content, Item::Create(), Mail::deliver_time, DETAIL_LOG, EQUIP_ERR_OK, Player::GetMail(), WorldSession::GetSessionDbcLocale(), HIGHGUID_PLAYER, ITEM_FIELD_CREATOR, ITEM_FIELD_ITEM_TEXT_ID, Mail::itemTextId, Player::m_mailsUpdated, MAIL_BODY_ITEM_TEMPLATE, MAIL_CHECK_MASK_COPIED, MAIL_ERR_EQUIP_ERROR, MAIL_ERR_INTERNAL_ERROR, MAIL_MADE_PERMANENT, MAIL_OK, MAIL_STATE_CHANGED, MAIL_STATE_DELETED, Mail::mailTemplateId, NULL_BAG, NULL_SLOT, ByteBuffer::read_skip(), Mail::sender, Player::SendMailResult(), Object::SetGuidValue(), Object::SetUInt32Value(), sMailTemplateStore, sObjectMgr, Mail::state, and Player::StoreItem().
HandleMailDelete()
void WorldSession::HandleMailDelete (WorldPacket & recv_data)
Handles the Packet sent by the client when deleting a mail.
This method is called when a client deletes a mail in his mailbox.
Parameters
recv_data The packet containing information about the mail being deleted.
Definition at line 347 of file MailHandler.cpp.
References WorldSession::_player, WorldSession::CheckMailBox(), Player::GetMail(), Player::m_mailsUpdated, MAIL_DELETED, MAIL_ERR_INTERNAL_ERROR, MAIL_OK, MAIL_STATE_DELETED, ByteBuffer::read_skip(), and Player::SendMailResult().
HandleMailMarkAsRead()
void WorldSession::HandleMailMarkAsRead (WorldPacket & recv_data)
Handles the Packet sent by the client when reading a mail.
This method is called when a client reads a mail that was previously unread. It will add the MAIL_CHECK_MASK_READ flag to the mail being read.
See also
MailCheckMask
Parameters
recv_data the packet containing information about the mail the player read.
Definition at line 317 of file MailHandler.cpp.
References WorldSession::_player, WorldSession::CheckMailBox(), Player::GetMail(), Player::m_mailsUpdated, MAIL_CHECK_MASK_READ, MAIL_STATE_CHANGED, and Player::unReadMails.
HandleMailReturnToSender()
void WorldSession::HandleMailReturnToSender (WorldPacket & recv_data)
Handles the Packet sent by the client when returning a mail to sender.
This method is called when a player chooses to return a mail to its sender. It will create a new MailDraft and add the items, money, etc. associated with the mail and then send the mail to the original sender.
Parameters
recv_data The packet containing information about the mail being returned.
Definition at line 383 of file MailHandler.cpp.
References WorldSession::_player, MailDraft::AddItem(), Database::BeginTransaction(), CharacterDatabase, WorldSession::CheckMailBox(), Database::CommitTransaction(), Mail::deliver_time, WorldSession::GetAccountId(), Player::GetMail(), Player::GetMItem(), Mail::HasItems(), HIGHGUID_PLAYER, Mail::items, Mail::itemTextId, MAIL_ERR_INTERNAL_ERROR, MAIL_NORMAL, MAIL_OK, MAIL_RETURNED_TO_SENDER, MAIL_STATE_DELETED, Mail::mailTemplateId, Mail::messageType, Mail::money, Database::PExecute(), ByteBuffer::read_skip(), Mail::receiverGuid, Player::RemoveMail(), Player::RemoveMItem(), Mail::sender, Player::SendMailResult(), MailDraft::SendReturnToSender(), MailDraft::SetMailTemplate(), MailDraft::SetMoney(), MailDraft::SetSubjectAndBodyId(), Mail::state, and Mail::subject.
HandleMailTakeItem()
void WorldSession::HandleMailTakeItem (WorldPacket & recv_data)
Handles the packet sent by the client when taking an item from the mail.
Definition at line 441 of file MailHandler.cpp.
References WorldSession::_player, Player::_SaveMail(), Database::BeginTransaction(), Player::CanStoreItem(), CharacterDatabase, WorldSession::CheckMailBox(), Mail::COD, Database::CommitTransaction(), CONFIG_BOOL_GM_LOG_TRADE, Mail::deliver_time, EQUIP_ERR_OK, WorldSession::GetAccountId(), Item::GetCount(), Object::GetEntry(), Object::GetGUIDLow(), Player::GetMail(), Player::GetMItem(), Player::GetMoney(), WorldObject::GetName(), WorldSession::GetPlayerName(), Item::GetProto(), WorldSession::GetSecurity(), Player::GetSession(), HIGHGUID_PLAYER, LANG_UNKNOWN, Player::m_mailsUpdated, MAIL_CHECK_MASK_COD_PAYMENT, MAIL_ERR_EQUIP_ERROR, MAIL_ERR_INTERNAL_ERROR, MAIL_ERR_NOT_ENOUGH_MONEY, MAIL_ITEM_TAKEN, MAIL_OK, MAIL_STATE_CHANGED, MAIL_STATE_DELETED, Player::ModifyMoney(), Player::MoveItemToInventory(), ItemPrototype::Name1, NULL_BAG, NULL_SLOT, Mail::removedItems, Mail::RemoveItem(), Player::RemoveMItem(), Player::SaveInventoryAndGoldToDB(), SEC_PLAYER, Mail::sender, Player::SendMailResult(), MailDraft::SendMailTo(), MailDraft::SetMoney(), sLog, sObjectMgr, Mail::state, Mail::subject, and sWorld.
HandleMailTakeMoney()
void WorldSession::HandleMailTakeMoney (WorldPacket & recv_data)
Handles the packet sent by the client when taking money from the mail.
Definition at line 539 of file MailHandler.cpp.
References WorldSession::_player, Player::_SaveMail(), Database::BeginTransaction(), CharacterDatabase, WorldSession::CheckMailBox(), Database::CommitTransaction(), Mail::deliver_time, Player::GetMail(), Player::m_mailsUpdated, MAIL_ERR_INTERNAL_ERROR, MAIL_MONEY_TAKEN, MAIL_OK, MAIL_STATE_CHANGED, MAIL_STATE_DELETED, Player::ModifyMoney(), Mail::money, Player::SaveGoldToDB(), Player::SendMailResult(), and Mail::state.
HandleQueryNextMailTime()
void WorldSession::HandleQueryNextMailTime (WorldPacket & recv_data)
No idea when this is called.
Parameters
recv_data recv_data
Definition at line 780 of file MailHandler.cpp.
References WorldSession::_player, Mail::checked, Player::GetMailBegin(), Player::GetMailEnd(), HIGHGUID_PLAYER, MAIL_AUCTION, MAIL_CHECK_MASK_READ, Mail::messageType, MSG_QUERY_NEXT_MAIL_TIME, ByteBuffer::put(), Mail::sender, WorldSession::SendPacket(), Mail::stationery, and Player::unReadMails.
HandleSendMail()
void WorldSession::HandleSendMail (WorldPacket & recv_data)
Handles the Packet sent by the client when sending a mail.
This methods takes the packet sent by the client and performs the following actions:
Checks whether the mail is valid: i.e. can he send the selected items, does he have enough money, etc.
Creates a MailDraft and adds the needed items, money, cost data.
Sends the mail.
Depending on the outcome of the checks performed the player will recieve a different MailResponseResult.
See also
MailResponseResult
SendMailResult()
Parameters
recv_data the WorldPacket containing the data sent by the client.
Definition at line 72 of file MailHandler.cpp.
References WorldSession::_player, MailDraft::AddItem(), Database::BeginTransaction(), Item::CanBeTraded(), CharacterDatabase, WorldSession::CheckMailBox(), Database::CommitTransaction(), CONFIG_BOOL_ALLOW_TWO_SIDE_INTERACTION_MAIL, CONFIG_BOOL_GM_LOG_TRADE, CONFIG_UINT32_MAIL_DELIVERY_DELAY, Item::DeleteFromInventoryDB(), DETAIL_LOG, EQUIP_ERR_MAIL_BOUND_ITEM, ItemPrototype::Flags, WorldSession::GetAccountId(), WorldSession::GetAnticheat(), Item::GetCount(), ObjectGuid::GetCounter(), Object::GetEntry(), Object::GetGUIDLow(), Object::GetGuidStr(), Player::GetItemByGuid(), Player::GetMailSize(), Player::GetMoney(), Object::GetObjectGuid(), WorldSession::GetPlayer(), WorldSession::GetPlayerName(), Item::GetProto(), WorldSession::GetSecurity(), Player::GetSession(), Item::GetSlot(), ObjectGuid::GetString(), Player::GetTeam(), Field::GetUInt32(), Object::GetUInt32Value(), Object::HasFlag(), ITEM_DYNFLAG_WRAPPED, ITEM_FIELD_DURATION, ITEM_FIELD_FLAGS, ITEM_FLAG_CONJURED, WorldSession::m_anticheat, MAIL_CHECK_MASK_COPIED, MAIL_CHECK_MASK_HAS_BODY, MAIL_ERR_CANNOT_SEND_TO_SELF, MAIL_ERR_CANT_SEND_WRAPPED_COD, MAIL_ERR_EQUIP_ERROR, MAIL_ERR_INTERNAL_ERROR, MAIL_ERR_MAIL_ATTACHMENT_INVALID, MAIL_ERR_NOT_ENOUGH_MONEY, MAIL_ERR_NOT_YOUR_TEAM, MAIL_ERR_RECIPIENT_CAP_REACHED, MAIL_ERR_RECIPIENT_NOT_FOUND, MAIL_ERR_TOO_MANY_ATTACHMENTS, MAIL_OK, MAIL_SEND, MAX_MAIL_ITEMS, Player::ModifyMoney(), Player::MoveItemFromInventory(), ItemPrototype::Name1, normalizePlayerName(), Database::PExecute(), Database::PQuery(), ByteBuffer::read_skip(), ByteBuffer::rpos(), Player::SaveInventoryAndGoldToDB(), Item::SaveToDB(), SEC_PLAYER, Player::SendMailResult(), MailDraft::SendMailTo(), MailDraft::SetCOD(), MailDraft::SetMoney(), sLog, sObjectMgr, sWorld, and ByteBuffer::wpos().
INSTANTIATE_SINGLETON_1()
INSTANTIATE_SINGLETON_1 (MassMailMgr)
MailDraft()
MailDraft::MailDraft (std::string subject, std::string text)
Creates a new MailDraft object using subject and contect texts.
Parameters
subject The subject of the mail.
itemText The text of the body of the mail.
Definition at line 107 of file Mail.cpp.
MailReceiver() [1/2]
MailReceiver::MailReceiver (Player * receiver)
Creates a new MailReceiver object.
Parameters
receiver The player receiving the mail.
Definition at line 87 of file Mail.cpp.
MailReceiver() [2/2]
MailReceiver::MailReceiver (Player * receiver, ObjectGuid receiver_guid)
Creates a new MailReceiver object with a specified GUID.
Parameters
receiver The player receiving the mail.
receiver_lowguid The GUID to use instead of the receivers.
Definition at line 96 of file Mail.cpp.
References Object::GetObjectGuid(), and MANGOS_ASSERT.
MailSender() [1/2]
MailSender::MailSender (AuctionEntry * sender)
Creates a new MailSender object from an AuctionEntry.
Parameters
sender the AuctionEntry from which this mail is generated.
Definition at line 77 of file Mail.cpp.
MailSender() [2/2]
MailSender::MailSender (Object * sender, MailStationery stationery = MAIL_STATIONERY_DEFAULT)
Creates a new MailSender object.
Parameters
sender The object/player sending this mail.
stationery The stationary associated with this sender.
Definition at line 44 of file Mail.cpp.
References Object::GetEntry(), Object::GetGUIDLow(), Object::GetTypeId(), MailSender::m_messageType, MailSender::m_senderId, MAIL_CREATURE, MAIL_GAMEOBJECT, MAIL_ITEM, MAIL_NORMAL, sLog, TYPEID_CONTAINER, TYPEID_GAMEOBJECT, TYPEID_ITEM, TYPEID_PLAYER, and TYPEID_UNIT.
prepareItems()
bool MailDraft::prepareItems (Player * receiver) private
called from SendMailTo for generate mailTemplateBase items
Prepares the items in a MailDraft.
Definition at line 136 of file Mail.cpp.
References MailDraft::AddItem(), LootItem::count, Item::CreateItem(), Loot::GetLootItemsListFor(), LootItem::itemId, LOOT_MAIL, MailDraft::m_items, MailDraft::m_mailTemplateId, MailDraft::m_mailTemplateItemsNeed, and MAX_MAIL_ITEMS.
Referenced by MailDraft::SendMailTo().
prepareTemplateItems()
void Mail::prepareTemplateItems (Player * receiver)
called from _LoadMails for generate mailTemplateBase items not generated for offline player
Generate items from template at mails loading (this happens when mail with mail template items send in time when receiver has been offline)
Parameters
receiver reciver of mail
Definition at line 374 of file Mail.cpp.
References Mail::AddItem(), Player::AddMItem(), Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), LootItem::count, Item::CreateItem(), Object::GetGUIDLow(), Loot::GetLootItemsListFor(), Mail::has_items, LootItem::itemId, Mail::items, LOOT_MAIL, Mail::mailTemplateId, MAX_MAIL_ITEMS, Mail::messageID, and Database::PExecute().
Referenced by Player::_LoadMails().
SendMailTo()
void MailDraft::SendMailTo (MailReceiver const & receiver, MailSender const & sender, MailCheckMask checked = MAIL_CHECK_MASK_NONE, uint32 deliver_delay = 0)
Sends a mail.
Parameters
receiver The MailReceiver to which this mail is sent.
sender The MailSender from which this mail is originated.
checked The mask used to specify the mail.
deliver_delay The delay after which the mail is delivered in seconds
Definition at line 270 of file Mail.cpp.
References Mail::AddItem(), Player::AddMail(), Player::AddMItem(), Player::AddNewMailDeliverTime(), BATTLEGROUND_TYPE_NONE, Database::BeginTransaction(), CharacterDatabase, Mail::checked, Mail::COD, Database::CommitTransaction(), DAY, MailDraft::deleteIncludedItems(), Mail::deliver_time, Database::escape_string(), Mail::expire_time, MailDraft::GetBodyId(), MailDraft::GetCOD(), ObjectGuid::GetCounter(), Object::GetEntry(), Object::GetGUIDLow(), MailSender::GetMailMessageType(), MailDraft::GetMailTemplateId(), MailDraft::GetMoney(), MailReceiver::GetPlayer(), MailReceiver::GetPlayerGuid(), MailSender::GetSenderId(), MailSender::GetStationery(), MailDraft::GetSubject(), HOUR, Mail::itemTextId, MailDraft::m_COD, MailDraft::m_items, MailDraft::m_money, MAIL_AUCTION, MAIL_CREATURE, MAIL_STATE_UNCHANGED, Mail::mailTemplateId, Mail::messageID, Mail::messageType, Mail::money, Database::PExecute(), MailDraft::prepareItems(), Mail::receiverGuid, sBattleGroundMgr, Mail::sender, sObjectMgr, Mail::state, Mail::stationery, Mail::subject, and UI64FMTD.
Referenced by PlayerbotAI::_HandleCommandMail(), Player::_LoadInventory(), Player::AutoUnequipOffhandIfNeed(), GMTicketMgr::Close(), ScriptAction::ExecuteDbscriptCommand(), Player::GiveLevel(), WorldSession::HandleAuctionRemoveItem(), WorldSession::HandleMailTakeItem(), ChatHandler::HandleSendItemsCommand(), WorldSession::HandleSendMail(), ChatHandler::HandleSendMailCommand(), ChatHandler::HandleSendMoneyCommand(), AuctionHouseMgr::LoadAuctions(), PlayerbotAI::RemoveAuction(), BattleGroundMgr::RewardArenaSeason(), Player::RewardQuest(), WorldSession::SendAuctionCancelledToBidderMail(), AuctionHouseMgr::SendAuctionExpiredMail(), WorldSession::SendAuctionOutbiddedMail(), AuctionHouseMgr::SendAuctionSalePendingMail(), AuctionHouseMgr::SendAuctionSuccessfulMail(), AuctionHouseMgr::SendAuctionWonMail(), MailDraft::SendReturnToSender(), BattleGround::SendRewardMarkByMail(), and MassMailMgr::Update().
SendReturnToSender()
void MailDraft::SendReturnToSender (uint32 sender_acc, ObjectGuid sender_guid, ObjectGuid receiver_guid)
Definition at line 222 of file Mail.cpp.
References Database::BeginTransaction(), CharacterDatabase, Database::CommitTransaction(), CONFIG_UINT32_MAIL_DELIVERY_DELAY, MailDraft::deleteIncludedItems(), ObjectGuid::GetCounter(), Object::GetGUIDLow(), MailDraft::m_items, MAIL_CHECK_MASK_RETURNED, MAIL_NORMAL, Database::PExecute(), Item::SaveToDB(), MailDraft::SendMailTo(), sObjectMgr, and sWorld.
Referenced by Player::DeleteFromDB(), and WorldSession::HandleMailReturnToSender().
SetSubjectAndBody()
MailDraft & MailDraft::SetSubjectAndBody (const std::string & subject, const std::string & text)
Definition at line 112 of file Mail.cpp.
References MailDraft::m_bodyId, MailDraft::m_subject, MANGOS_ASSERT, and sObjectMgr.
Referenced by ChatHandler::HandleSendItemsHelper(), ChatHandler::HandleSendMailHelper(), ChatHandler::HandleSendMoneyHelper(), and BattleGroundMgr::RewardArenaSeason().
Update()
void MassMailMgr::Update (bool sendall = false)
Next step in mass mail activity, send some amount mails from queued tasks.
Definition at line 74 of file MassMailMgr.cpp.
References MailDraft::CloneFrom(), CONFIG_UINT32_MASS_MAILER_SEND_PER_TICK, HIGHGUID_PLAYER, MassMailMgr::m_massMails, MassMailMgr::MassMail::m_protoMail, MassMailMgr::MassMail::m_receivers, MassMailMgr::MassMail::m_sender, MAIL_CHECK_MASK_RETURNED, MailDraft::SendMailTo(), sObjectMgr, and sWorld.
Variable Documentation
massMailerQueryHandler
struct MassMailerQueryHandler massMailerQueryHandler
Referenced by MassMailMgr::AddMassMailTask().