CMaNGOS_TBC: to provide abstract support for transported entities
to provide abstract support for transported entities
The Transport System in MaNGOS consists of these files:
Files
file TransportSystem.cpp
This file contains the code needed for MaNGOS to provide abstract support for transported entities Currently implemented.
file TransportSystem.h
This file contains the headers for base clases needed for MaNGOS to handle passengers on transports.
Data Structures
class TransportBase
A class to provide basic support for each transporter.
class TransportInfo
A class to provide basic information for each transported passenger.
Typedefs
typedef std::unordered_map< WorldObject *, TransportInfo * > PassengerMap
Functions
TransportBase::TransportBase (WorldObject *owner)
virtual TransportBase::~TransportBase ()
void TransportBase::Update (uint32 diff)
void TransportBase::UpdateGlobalPositions ()
void TransportBase::UpdateGlobalPositionOf (WorldObject *passenger, float lx, float ly, float lz, float lo) const
void TransportBase::RotateLocalPosition (float lx, float ly, float &rx, float &ry) const
void TransportBase::NormalizeRotatedPosition (float rx, float ry, float &lx, float &ly) const
void TransportBase::CalculatePassengerPosition (float &x, float &y, float &z, float *o=nullptr) const
void TransportBase::CalculatePassengerOffset (float &x, float &y, float &z, float *o=nullptr) const
This method transforms supplied global coordinates into local offsets.
void TransportBase::BoardPassenger (WorldObject *passenger, float lx, float ly, float lz, float lo)
void TransportBase::UnBoardPassenger (WorldObject *passenger)
TransportInfo::TransportInfo (WorldObject *owner, TransportBase *transport, float lx, float ly, float lz, float lo)
void TransportInfo::SetLocalPosition (float lx, float ly, float lz, float lo)
Detailed Description
The Transport System in MaNGOS consists of these files:
TransportSystem.h to provide the basic classes TransportBase and TransportInfo
TransportSystem.cpp which implements these classes
Transports.h to implement the MOTransporter (subclas of gameobject) - Remains TODO as well of
impacts to various files
Typedef Documentation
PassengerMap
typedef std::unordered_map<WorldObject* , TransportInfo* > PassengerMap
Definition at line 43 of file TransportSystem.h.
Function Documentation
BoardPassenger()
void TransportBase::BoardPassenger (WorldObject * passenger, float lx, float ly, float lz, float lo) protected
Definition at line 134 of file TransportSystem.cpp.
References TransportBase::m_passengers, and WorldObject::SetTransportInfo().
CalculatePassengerOffset()
void TransportBase::CalculatePassengerOffset (float & x, float & y, float & z, float * o = nullptr) const
This method transforms supplied global coordinates into local offsets.
Definition at line 129 of file TransportSystem.cpp.
References GenericTransport::CalculatePassengerOffset(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), and TransportBase::m_owner.
Referenced by TransportInfo::CalculatePassengerOffset().
CalculatePassengerPosition()
void TransportBase::CalculatePassengerPosition (float & x, float & y, float & z, float * o = nullptr) const
Definition at line 124 of file TransportSystem.cpp.
References GenericTransport::CalculatePassengerPosition(), WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), and TransportBase::m_owner.
Referenced by TransportInfo::CalculatePassengerPosition().
NormalizeRotatedPosition()
void TransportBase::NormalizeRotatedPosition (float rx, float ry, float & lx, float & ly) const
Definition at line 118 of file TransportSystem.cpp.
References TransportBase::m_cosO, and TransportBase::m_sinO.
RotateLocalPosition()
void TransportBase::RotateLocalPosition (float lx, float ly, float & rx, float & ry) const
Definition at line 111 of file TransportSystem.cpp.
References TransportBase::m_cosO, and TransportBase::m_sinO.
SetLocalPosition()
void TransportInfo::SetLocalPosition (float lx, float ly, float lz, float lo)
Definition at line 172 of file TransportSystem.cpp.
References TransportInfo::m_localPosition, TransportInfo::m_owner, TransportInfo::m_transport, Position::o, TransportBase::UpdateGlobalPositionOf(), Position::x, Position::y, and Position::z.
TransportBase()
TransportBase::TransportBase (WorldObject * owner) explicit
Definition at line 37 of file TransportSystem.cpp.
References TransportBase::m_owner, and MANGOS_ASSERT.
TransportInfo()
TransportInfo::TransportInfo (WorldObject * owner, TransportBase * transport, float lx, float ly, float lz, float lo) explicit
Definition at line 164 of file TransportSystem.cpp.
References TransportInfo::m_transport, and MANGOS_ASSERT.
UnBoardPassenger()
void TransportBase::UnBoardPassenger (WorldObject * passenger) protected
Definition at line 145 of file TransportSystem.cpp.
References TransportBase::m_passengers, and WorldObject::SetTransportInfo().
Update()
void TransportBase::Update (uint32 diff)
Definition at line 54 of file TransportSystem.cpp.
References WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), TransportBase::m_lastPosition, TransportBase::m_owner, TransportBase::m_updatePositionsTimer, MapManager::NormalizeOrientation(), Position::o, TransportBase::UpdateGlobalPositions(), Position::x, Position::y, and Position::z.
UpdateGlobalPositionOf()
void TransportBase::UpdateGlobalPositionOf (WorldObject * passenger, float lx, float ly, float lz, float lo) const
Definition at line 92 of file TransportSystem.cpp.
References GenericTransport::CalculatePassengerPosition(), Map::CreatureRelocation(), WorldObject::GetMap(), WorldObject::GetPosition(), Object::GetTypeId(), TransportBase::m_owner, Position::o, Map::PlayerRelocation(), TYPEID_PLAYER, TYPEID_UNIT, Position::x, Position::y, and Position::z.
Referenced by TransportInfo::SetLocalPosition(), and TransportBase::UpdateGlobalPositions().
UpdateGlobalPositions()
void TransportBase::UpdateGlobalPositions ()
Definition at line 71 of file TransportSystem.cpp.
References WorldObject::GetOrientation(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), TransportBase::m_cosO, TransportBase::m_lastPosition, TransportBase::m_owner, TransportBase::m_passengers, TransportBase::m_sinO, MapManager::NormalizeOrientation(), Position::o, and TransportBase::UpdateGlobalPositionOf().
Referenced by TransportBase::Update().
~TransportBase()
TransportBase::~TransportBase () virtual
Definition at line 47 of file TransportSystem.cpp.
References TransportBase::m_passengers, and MANGOS_ASSERT.