CMaNGOS_TBC: guards.cpp File Reference
guards.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/guard_ai.h"
#include "GameEvents/GameEventMgr.h"
Data Structures
struct guard_hallows_end_helperAI
struct guard_shattrath_aldorAI
struct guard_shattrath_scryerAI
struct guardAI_stormwind
struct SpawnGuard
Enumerations
enum { SPELL_WINDSOR_INSPIRATION_EFFECT = 20275 , MAX_GUARD_SALUTES = 7 }
Functions
bool GossipHello_guard_hallows_end_helper (Player *player, Creature *creature)
void AddSC_guards ()
Variables
static const int32 aGuardSalute [MAX_GUARD_SALUTES] = { -1000842, -1000843, -1000844, -1000845, -1000846, -1000847, -1000848}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_WINDSOR_INSPIRATION_EFFECT
MAX_GUARD_SALUTES
Definition at line 345 of file guards.cpp.
Function Documentation
AddSC_guards()
void AddSC_guards ()
Definition at line 501 of file guards.cpp.
References Script::GetAI, GossipHello_guard_hallows_end_helper(), Script::Name, Script::pGossipHello, and Script::RegisterSelf().
Referenced by AddScripts().
GossipHello_guard_hallows_end_helper()
bool GossipHello_guard_hallows_end_helper (Player * player, Creature * creature)
Definition at line 185 of file guards.cpp.
References Object::GetDbGuid(), Player::GetDefaultGossipMenuForSource(), Object::GetEntry(), Object::GetObjectGuid(), NPC_AZUREMYST_PEACEKEEPER, NPC_DEATHGUARD_FLORENCE, NPC_IRONFORGE_MOUNTAINEER, NPC_RAZOR_HILL_GRUNT, NPC_SILVERMOON_GUARDIAN, NPC_STORMWIND_GUARD, Player::PrepareGossipMenu(), Player::SendPreparedGossip(), sGameEventMgr, TEXT_ID_AZUREMYST_PEACEKEEPER, TEXT_ID_DEATHGUARD_FLORENCE, TEXT_ID_IRONFORGE_MOUNTAINEER, TEXT_ID_RAZOR_HILL_GRUNT, TEXT_ID_SILVERMOON_GUARDIAN, and TEXT_ID_STORMWIND_GUARD.
Referenced by AddSC_guards().
Variable Documentation
aGuardSalute
const int32 aGuardSalute[MAX_GUARD_SALUTES] = { -1000842, -1000843, -1000844, -1000845, -1000846, -1000847, -1000848} static
Definition at line 351 of file guards.cpp.
Referenced by guardAI_stormwind::SpellHit().