CMaNGOS_TBC: LFGHandler.cpp File Reference
LFGHandler.cpp File Reference
#include "Server/WorldSession.h"
#include "Log.h"
#include "Globals/ObjectMgr.h"
#include "World/World.h"
Functions
static void LookingForGroupMakeMeetingStoneQueueLeftFor (WorldPacket &data, uint32 entry)
static void LookingForGroupMakeMeetingStoneQueueJoinedFor (WorldPacket &data, uint32 entry)
static void LookingForGroupMakeMeetingStoneQueueMatchedFor (WorldPacket &data, uint32 entry, bool asLeader=false)
static void LookingForGroupMakeMeetingStoneMemberAdded (WorldPacket &data, ObjectGuid guid)
static const Player * LookingForGroupGetCurrentLeader (Player *_this)
static void LookingForGroupUpdateChannelStatus (Player *_this)
static bool LookingForGroupUpdateQueueStatus (Player *_this, WorldSession *_session)
static void LookingForGroupUpdateUI (Player *_this, WorldSession *_session, bool completed=false)
static void LookingForGroupUpdate (Player *_this, WorldSession *_session, bool completed=false)
static void LookingForGroupClearLFG (Player *_this, WorldSession *_session)
static void LookingForGroupClearLFM (Player *_this, WorldSession *_session)
static void LookingForGroupClear (Player *_this, WorldSession *_session, bool completed=false)
static bool LookingForGroupAddMemberFor (Player *_this, WorldSession *_session, Player *member, uint32 entry, Group *&_group)
static void LookingForGroupTryJoin (Player *_player, bool initial=false)
static void LookingForGroupTryFill (Player *_player, bool initial=false)
static void LookingForGroupSetAutoJoin (Player *_player, WorldSession *_session, bool enabled)
static void LookingForGroupSetAutoFill (Player *_player, WorldSession *_session, bool enabled)
Function Documentation
LookingForGroupAddMemberFor()
static bool LookingForGroupAddMemberFor (Player * _this, WorldSession * _session, Player * member, uint32 entry, Group *& _group) inline static
Definition at line 195 of file LFGHandler.cpp.
References Group::AddMember(), Group::BroadcastPacket(), Group::Create(), WorldObject::GetName(), Object::GetObjectGuid(), Player::GetSession(), Group::IsFull(), LookingForGroupClear(), LookingForGroupMakeMeetingStoneMemberAdded(), LookingForGroupMakeMeetingStoneQueueMatchedFor(), WorldSession::SendPacket(), and sObjectMgr.
Referenced by LookingForGroupTryFill(), and LookingForGroupTryJoin().
LookingForGroupClear()
static void LookingForGroupClear (Player * _this, WorldSession * _session, bool completed = false) inline static
Definition at line 188 of file LFGHandler.cpp.
References LookingForGroupInfo::clear(), LookingForGroupUpdate(), and Player::m_lookingForGroup.
Referenced by LookingForGroupAddMemberFor(), LookingForGroupTryFill(), and LookingForGroupTryJoin().
LookingForGroupClearLFG()
static void LookingForGroupClearLFG (Player * _this, WorldSession * _session) inline static
Definition at line 165 of file LFGHandler.cpp.
References LookingForGroupInfo::Slot::clear(), LookingForGroupInfo::group, LookingForGroupInfo::isLFG(), LookingForGroupUpdate(), Player::m_lookingForGroup, and MAX_LOOKING_FOR_GROUP_SLOT.
Referenced by WorldSession::HandleLfgClearOpcode(), WorldSession::HandleSetLfmOpcode(), LookingForGroupTryFill(), and LookingForGroupTryJoin().
LookingForGroupClearLFM()
static void LookingForGroupClearLFM (Player * _this, WorldSession * _session) inline static
Definition at line 177 of file LFGHandler.cpp.
References LookingForGroupInfo::Slot::clear(), LookingForGroupInfo::isLFM(), LookingForGroupUpdate(), Player::m_lookingForGroup, and LookingForGroupInfo::more.
Referenced by WorldSession::HandleLfmClearOpcode(), and WorldSession::HandleSetLfgOpcode().
LookingForGroupGetCurrentLeader()
static const Player* LookingForGroupGetCurrentLeader (Player * _this) inline static
Definition at line 53 of file LFGHandler.cpp.
References Player::GetGroup(), Object::GetObjectGuid(), and GroupReference::next().
Referenced by WorldSession::HandleSetLfgOpcode(), LookingForGroupUpdateChannelStatus(), LookingForGroupUpdateQueueStatus(), and WorldSession::SendLFGUpdate().
LookingForGroupMakeMeetingStoneMemberAdded()
static void LookingForGroupMakeMeetingStoneMemberAdded (WorldPacket & data, ObjectGuid guid) inline static
Definition at line 47 of file LFGHandler.cpp.
References WorldPacket::Initialize(), and SMSG_MEETINGSTONE_SETQUEUE.
Referenced by LookingForGroupAddMemberFor().
LookingForGroupMakeMeetingStoneQueueJoinedFor()
static void LookingForGroupMakeMeetingStoneQueueJoinedFor (WorldPacket & data, uint32 entry) inline static
Definition at line 32 of file LFGHandler.cpp.
References WorldPacket::Initialize(), and SMSG_MEETINGSTONE_SETQUEUE.
Referenced by LookingForGroupUpdateQueueStatus().
LookingForGroupMakeMeetingStoneQueueLeftFor()
static void LookingForGroupMakeMeetingStoneQueueLeftFor (WorldPacket & data, uint32 entry) inline static
Definition at line 25 of file LFGHandler.cpp.
References WorldPacket::Initialize(), and SMSG_MEETINGSTONE_SETQUEUE.
Referenced by LookingForGroupUpdateQueueStatus().
LookingForGroupMakeMeetingStoneQueueMatchedFor()
static void LookingForGroupMakeMeetingStoneQueueMatchedFor (WorldPacket & data, uint32 entry, bool asLeader = false) inline static
Definition at line 39 of file LFGHandler.cpp.
References WorldPacket::Initialize(), and SMSG_MEETINGSTONE_SETQUEUE.
Referenced by LookingForGroupAddMemberFor().
LookingForGroupSetAutoFill()
static void LookingForGroupSetAutoFill (Player * _player, WorldSession * _session, bool enabled) inline static
Definition at line 404 of file LFGHandler.cpp.
References Player::GetGroup(), Object::GetObjectGuid(), LookingForGroupTryFill(), LookingForGroupUpdateQueueStatus(), WorldSession::SendPacket(), and SMSG_MEETINGSTONE_JOINFAILED.
Referenced by WorldSession::HandleLfmClearAutoFillOpcode(), and WorldSession::HandleLfmSetAutoFillOpcode().
LookingForGroupSetAutoJoin()
static void LookingForGroupSetAutoJoin (Player * _player, WorldSession * _session, bool enabled) inline static
Definition at line 385 of file LFGHandler.cpp.
References LookingForGroupTryJoin(), LookingForGroupUpdateQueueStatus(), WorldSession::SendPacket(), and SMSG_MEETINGSTONE_JOINFAILED.
Referenced by WorldSession::HandleLfgClearAutoJoinOpcode(), and WorldSession::HandleLfgSetAutoJoinOpcode().
LookingForGroupTryFill()
static void LookingForGroupTryFill (Player * _player, bool initial = false) static
Definition at line 314 of file LFGHandler.cpp.
References LookingForGroupInfo::Slot::empty(), LookingForGroupInfo::Slot::entry, Player::GetGroup(), Object::GetObjectGuid(), Player::GetSession(), Player::GetTeam(), Group::IsBattleGroup(), Group::IsFull(), Object::IsInWorld(), Group::IsLeader(), LookingForGroupInfo::isLFG(), WorldSession::IsOffline(), WorldSession::LookingForGroup_queue, LookingForGroupAddMemberFor(), LookingForGroupClear(), LookingForGroupClearLFG(), LookingForGroupUpdateQueueStatus(), Player::m_lookingForGroup, LookingForGroupInfo::more, WorldSession::SendMeetingStoneInProgress(), and sObjectAccessor.
Referenced by WorldSession::HandleLFGListQuery(), WorldSession::HandleSetLfmOpcode(), and LookingForGroupSetAutoFill().
LookingForGroupTryJoin()
static void LookingForGroupTryJoin (Player * _player, bool initial = false) static
Definition at line 245 of file LFGHandler.cpp.
References LookingForGroupInfo::Slot::empty(), LookingForGroupInfo::Slot::entry, Player::GetGroup(), Object::GetObjectGuid(), Player::GetSession(), Player::GetTeam(), Group::IsBattleGroup(), Group::IsFull(), Object::IsInWorld(), Group::IsLeader(), LookingForGroupInfo::isLFG(), WorldSession::IsOffline(), WorldSession::LookingForGroup_queue, LookingForGroupAddMemberFor(), LookingForGroupClear(), LookingForGroupClearLFG(), LookingForGroupUpdateQueueStatus(), Player::m_lookingForGroup, LookingForGroupInfo::more, WorldSession::SendMeetingStoneInProgress(), and sObjectAccessor.
Referenced by WorldSession::HandleLFGListQuery(), WorldSession::HandleSetLfgOpcode(), and LookingForGroupSetAutoJoin().
LookingForGroupUpdate()
static void LookingForGroupUpdate (Player * _this, WorldSession * _session, bool completed = false) inline static
Definition at line 159 of file LFGHandler.cpp.
References LookingForGroupUpdateQueueStatus(), and LookingForGroupUpdateUI().
Referenced by LookingForGroupClear(), LookingForGroupClearLFG(), and LookingForGroupClearLFM().
LookingForGroupUpdateChannelStatus()
static void LookingForGroupUpdateChannelStatus (Player * _this) inline static
Definition at line 72 of file LFGHandler.cpp.
References CONFIG_BOOL_CHANNEL_RESTRICTED_LFG, WorldSession::GetSecurity(), Player::GetSession(), LookingForGroupInfo::isEmpty(), Player::LeaveLFGChannel(), LookingForGroupGetCurrentLeader(), Player::m_lookingForGroup, SEC_PLAYER, and sWorld.
Referenced by LookingForGroupUpdateUI().
LookingForGroupUpdateQueueStatus()
static bool LookingForGroupUpdateQueueStatus (Player * _this, WorldSession * _session) inline static
Definition at line 83 of file LFGHandler.cpp.
References Group::BroadcastPacket(), Player::GetGroup(), Object::GetObjectGuid(), Player::GetSession(), LookingForGroupInfo::isAutoFill(), LookingForGroupInfo::isAutoJoin(), Group::IsLeader(), Group::IsRaidGroup(), WorldSession::LookingForGroup_auto_add, WorldSession::LookingForGroup_auto_join, WorldSession::LookingForGroup_queue, LookingForGroupGetCurrentLeader(), LookingForGroupMakeMeetingStoneQueueJoinedFor(), LookingForGroupMakeMeetingStoneQueueLeftFor(), Player::m_lookingForGroup, WorldSession::SendPacket(), and SMSG_LFG_UPDATE_QUEUED.
Referenced by WorldSession::HandleSetLfgOpcode(), WorldSession::HandleSetLfmOpcode(), LookingForGroupSetAutoFill(), LookingForGroupSetAutoJoin(), LookingForGroupTryFill(), LookingForGroupTryJoin(), and LookingForGroupUpdate().
LookingForGroupUpdateUI()
static void LookingForGroupUpdateUI (Player * _this, WorldSession * _session, bool completed = false) inline static
Definition at line 130 of file LFGHandler.cpp.
References Group::GetFirstMember(), Player::GetGroup(), Object::GetObjectGuid(), Group::IsLeader(), LookingForGroupUpdateChannelStatus(), GroupReference::next(), WorldSession::SendLFGUpdate(), and WorldSession::SendMeetingStoneComplete().
Referenced by WorldSession::HandleSetLfmOpcode(), and LookingForGroupUpdate().