CMaNGOS_TBC: nagrand.cpp File Reference
nagrand.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "AI/ScriptDevAI/base/escort_ai.h"
#include "AI/ScriptDevAI/scripts/outland/world_outland.h"
#include "Spells/Scripts/SpellScript.h"
Data Structures
struct mob_lumpAI
struct npc_nagrand_captiveAI
struct npc_creditmarker_visit_with_ancestorsAI
struct npc_rethhedronAI
struct SparrowhawkNet
Enumerations
enum {
SAY_LUMP_AGGRO_1 = -1000190 , SAY_LUMP_AGGRO_2 = -1000191 , SAY_LUMP_DEFEAT = -1000192 , SPELL_VISUAL_SLEEP = 16093 ,
SPELL_SPEAR_THROW = 32248 , FACTION_FRIENDLY = 35
}
enum {
SAY_MAG_START = -1000482 , SAY_MAG_MORE = -1000484 , SAY_MAG_LIGHTNING = -1000486 , SAY_MAG_SHOCK = -1000487 ,
SAY_MAG_COMPLETE = -1000488 , SAY_KUR_START = -1001001 , SAY_KUR_AMBUSH_1 = -1001002 , SAY_KUR_AMBUSH_2 = -1001003 ,
SAY_KUR_UP_AHEAD = -1001004 , SAY_KUR_COMPLETE = -1001005 , SAY_MURK_BRUTE_NO_ESCAPE = -1000483 , SAY_MURK_BRUTE_WHERE = -1000485 ,
SPELL_CHAIN_LIGHTNING = 16006 , SPELL_EARTHBIND_TOTEM = 15786 , SPELL_FROST_SHOCK = 12548 , SPELL_HEALING_WAVE = 12491 ,
QUEST_TOTEM_KARDASH_H = 9868 , QUEST_TOTEM_KARDASH_A = 9879 , NPC_KURENAI_CAPTIVE = 18209 , NPC_MAGHAR_CAPTIVE = 18210 ,
NPC_MURK_RAIDER = 18203 , NPC_MURK_BRUTE = 18211 , NPC_MURK_SCAVENGER = 18207 , NPC_MURK_PUTRIFIER = 18202 ,
FACTION_TROLL_FROSTMANE = 33 , FACTION_UNKWN = 10
}
enum {
QUEST_VISIT_WITH_ANCESTORS = 10085 , WHISPER_VISIT_WITH_ANCESTORS_1 = -1001319 , WHISPER_VISIT_WITH_ANCESTORS_2 = -1001320 , WHISPER_VISIT_WITH_ANCESTORS_3 = -1001321 ,
WHISPER_VISIT_WITH_ANCESTORS_4 = -1001322 , WHISPER_VISIT_WITH_ANCESTORS_5 = -1001323 , NPC_VISION_OF_THE_FORGOTTEN = 18904
}
enum {
SAY_LOW_HP = -1000966 , SAY_EVENT_END = -1000967 , SPELL_CRIPPLE = 41281 , SPELL_SHADOW_BOLT = 41280 ,
SPELL_ABYSSAL_TOSS = 41283 , SPELL_ABYSSAL_IMPACT = 41284 , SPELL_COSMETIC_LEGION_RING = 41339 , SPELL_QUEST_COMPLETE = 41340 ,
NPC_SPELLBINDER = 22342 , NPC_RETHHEDRONS_TARGET = 23416 , PATH_ID_OUTRO = 1 , POINT_ID_PORTAL_YELL = 1 ,
POINT_ID_PORTAL_FRONT = 2 , POINT_ID_PORTAL_FINAL = 3 , SOUND_ID_ABYSSAL_TOSS = 10667
}
enum { GOSSIP_IN_BATTLE = 7700 , QUEST_RING_OF_BLOOD_FINAL_CHALLENGE = 9977 }
enum { NPC_WILD_SPARROWHAWK = 22979 , SPELL_CAPTURED_SPARROWHAWK = 39812 }
Functions
UnitAI * GetAI_mob_lump (Creature *pCreature)
bool QuestAccept_npc_nagrand_captive (Player *pPlayer, Creature *pCreature, const Quest *pQuest)
UnitAI * GetAI_npc_nagrand_captive (Creature *pCreature)
UnitAI * GetAI_npc_creditmarker_visit_with_ancestors (Creature *pCreature)
bool QuestAccept_npc_gurthock (Player *, Creature *creature, const Quest *quest)
bool GossipHello_npc_gurthock (Player *player, Creature *creature)
void AddSC_nagrand ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_LUMP_AGGRO_1
SAY_LUMP_AGGRO_2
SAY_LUMP_DEFEAT
SPELL_VISUAL_SLEEP
SPELL_SPEAR_THROW
FACTION_FRIENDLY
Definition at line 40 of file nagrand.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_MAG_START
SAY_MAG_MORE
SAY_MAG_LIGHTNING
SAY_MAG_SHOCK
SAY_MAG_COMPLETE
SAY_KUR_START
SAY_KUR_AMBUSH_1
SAY_KUR_AMBUSH_2
SAY_KUR_UP_AHEAD
SAY_KUR_COMPLETE
SAY_MURK_BRUTE_NO_ESCAPE
SAY_MURK_BRUTE_WHERE
SPELL_CHAIN_LIGHTNING
SPELL_EARTHBIND_TOTEM
SPELL_FROST_SHOCK
SPELL_HEALING_WAVE
QUEST_TOTEM_KARDASH_H
QUEST_TOTEM_KARDASH_A
NPC_KURENAI_CAPTIVE
NPC_MAGHAR_CAPTIVE
NPC_MURK_RAIDER
NPC_MURK_BRUTE
NPC_MURK_SCAVENGER
NPC_MURK_PUTRIFIER
FACTION_TROLL_FROSTMANE
FACTION_UNKWN
Definition at line 151 of file nagrand.cpp.
anonymous enum
anonymous enum
Enumerator
QUEST_VISIT_WITH_ANCESTORS
WHISPER_VISIT_WITH_ANCESTORS_1
WHISPER_VISIT_WITH_ANCESTORS_2
WHISPER_VISIT_WITH_ANCESTORS_3
WHISPER_VISIT_WITH_ANCESTORS_4
WHISPER_VISIT_WITH_ANCESTORS_5
NPC_VISION_OF_THE_FORGOTTEN
Definition at line 410 of file nagrand.cpp.
anonymous enum
anonymous enum
Enumerator
SAY_LOW_HP
SAY_EVENT_END
SPELL_CRIPPLE
SPELL_SHADOW_BOLT
SPELL_ABYSSAL_TOSS
SPELL_ABYSSAL_IMPACT
SPELL_COSMETIC_LEGION_RING
SPELL_QUEST_COMPLETE
NPC_SPELLBINDER
NPC_RETHHEDRONS_TARGET
PATH_ID_OUTRO
POINT_ID_PORTAL_YELL
POINT_ID_PORTAL_FRONT
POINT_ID_PORTAL_FINAL
SOUND_ID_ABYSSAL_TOSS
Definition at line 465 of file nagrand.cpp.
anonymous enum
anonymous enum
Enumerator
GOSSIP_IN_BATTLE
QUEST_RING_OF_BLOOD_FINAL_CHALLENGE
Definition at line 622 of file nagrand.cpp.
anonymous enum
anonymous enum
Enumerator
NPC_WILD_SPARROWHAWK
SPELL_CAPTURED_SPARROWHAWK
Definition at line 650 of file nagrand.cpp.
Function Documentation
AddSC_nagrand()
void AddSC_nagrand ()
Definition at line 675 of file nagrand.cpp.
References Script::GetAI, GetAI_mob_lump(), GetAI_npc_creditmarker_visit_with_ancestors(), GetAI_npc_nagrand_captive(), GossipHello_npc_gurthock(), Script::Name, Script::pGossipHello, Script::pQuestAcceptNPC, QuestAccept_npc_gurthock(), QuestAccept_npc_nagrand_captive(), and Script::RegisterSelf().
Referenced by AddScripts().
GetAI_mob_lump()
UnitAI* GetAI_mob_lump (Creature * pCreature)
Definition at line 142 of file nagrand.cpp.
Referenced by AddSC_nagrand().
GetAI_npc_creditmarker_visit_with_ancestors()
UnitAI* GetAI_npc_creditmarker_visit_with_ancestors (Creature * pCreature)
Definition at line 456 of file nagrand.cpp.
Referenced by AddSC_nagrand().
GetAI_npc_nagrand_captive()
UnitAI* GetAI_npc_nagrand_captive (Creature * pCreature)
Definition at line 401 of file nagrand.cpp.
Referenced by AddSC_nagrand().
GossipHello_npc_gurthock()
bool GossipHello_npc_gurthock (Player * player, Creature * creature)
Definition at line 641 of file nagrand.cpp.
References GOSSIP_IN_BATTLE, Object::HasFlag(), Player::PrepareGossipMenu(), Player::SendPreparedGossip(), UNIT_NPC_FLAG_QUESTGIVER, and UNIT_NPC_FLAGS.
Referenced by AddSC_nagrand().
QuestAccept_npc_gurthock()
bool QuestAccept_npc_gurthock (Player * , Creature * creature, const Quest * quest)
Definition at line 629 of file nagrand.cpp.
References WorldObject::GetInstanceData(), Quest::GetQuestId(), QUEST_RING_OF_BLOOD_FINAL_CHALLENGE, Object::RemoveFlag(), TYPE_MOGOR, UNIT_NPC_FLAG_QUESTGIVER, and UNIT_NPC_FLAGS.
Referenced by AddSC_nagrand().
QuestAccept_npc_nagrand_captive()
bool QuestAccept_npc_nagrand_captive (Player * pPlayer, Creature * pCreature, const Quest * pQuest)
Definition at line 384 of file nagrand.cpp.
References Creature::AI(), AI_EVENT_START_ESCORT, Quest::GetQuestId(), QUEST_TOTEM_KARDASH_A, QUEST_TOTEM_KARDASH_H, Object::RemoveFlag(), UnitAI::SendAIEvent(), Unit::SetStandState(), UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_NPC, UNIT_FLAG_IMMUNE_TO_PLAYER, UNIT_NPC_FLAG_QUESTGIVER, UNIT_NPC_FLAGS, and UNIT_STAND_STATE_STAND.
Referenced by AddSC_nagrand().