CMaNGOS_TBC: naxxramas.cpp File Reference
naxxramas.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "naxxramas.h"
Data Structures
struct Location3DPoint
struct npc_stoneskin_gargoyleAI
struct npc_living_poisonAI
Enumerations
enum {
SAY_GARGOYLE_NOISE = -1533160 , SPELL_STONEFORM = 29154 , SPELL_STEALTH_DETECTION = 18950 , SPELL_STONESKIN = 28995 ,
SPELL_ACID_VOLLEY = 29325
}
Functions
InstanceData * GetInstanceData_instance_naxxramas (Map *pMap)
bool AreaTrigger_at_naxxramas (Player *player, AreaTriggerEntry const *areaTrigger)
bool ProcessEventId_naxxramas (uint32 eventId, Object *source, Object *, bool)
void AddSC_instance_naxxramas ()
Variables
static const DialogueEntry naxxDialogue []
static const Location3DPoint gargoyleResetCoords = {2963.f, -3476.f, 297.6f}
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SAY_GARGOYLE_NOISE
SPELL_STONEFORM
SPELL_STEALTH_DETECTION
SPELL_STONESKIN
SPELL_ACID_VOLLEY
Definition at line 1071 of file naxxramas.cpp.
Function Documentation
AddSC_instance_naxxramas()
void AddSC_instance_naxxramas ()
Definition at line 1264 of file naxxramas.cpp.
References AreaTrigger_at_naxxramas(), Script::GetAI, Script::GetInstanceData, GetInstanceData_instance_naxxramas(), Script::Name, Script::pAreaTrigger, Script::pProcessEventId, ProcessEventId_naxxramas(), and Script::RegisterSelf().
Referenced by AddScripts().
AreaTrigger_at_naxxramas()
bool AreaTrigger_at_naxxramas (Player * player, AreaTriggerEntry const * areaTrigger)
Definition at line 1245 of file naxxramas.cpp.
References WorldObject::GetInstanceData(), Unit::IsAlive(), and Player::IsGameMaster().
Referenced by AddSC_instance_naxxramas().
GetInstanceData_instance_naxxramas()
InstanceData* GetInstanceData_instance_naxxramas (Map * pMap)
Definition at line 1059 of file naxxramas.cpp.
Referenced by AddSC_instance_naxxramas().
ProcessEventId_naxxramas()
bool ProcessEventId_naxxramas (uint32 eventId, Object * source, Object * , bool)
Definition at line 1256 of file naxxramas.cpp.
Referenced by AddSC_instance_naxxramas().
Variable Documentation
gargoyleResetCoords
const Location3DPoint gargoyleResetCoords = {2963.f, -3476.f, 297.6f} static
Definition at line 1069 of file naxxramas.cpp.
Referenced by npc_stoneskin_gargoyleAI::Aggro(), and npc_stoneskin_gargoyleAI::npc_stoneskin_gargoyleAI().
naxxDialogue
const DialogueEntry naxxDialogue[] static
Initial value:
=
{
    {NPC_KELTHUZAD,         0,                10000},
    {SAY_SAPP_DIALOG1,      NPC_KELTHUZAD,    5000},
    {SAY_SAPP_DIALOG2_LICH, NPC_THE_LICHKING, 17000},
    {SAY_SAPP_DIALOG3,      NPC_KELTHUZAD,    6000},
    {SAY_SAPP_DIALOG4_LICH, NPC_THE_LICHKING, 8000},
    {SAY_SAPP_DIALOG5,      NPC_KELTHUZAD,    0},
    {NPC_THANE,             0,                10000},
    {SAY_KORT_TAUNT1,       NPC_THANE,        5000},
    {SAY_ZELI_TAUNT1,       NPC_ZELIEK,       6000},
    {SAY_BLAU_TAUNT1,       NPC_BLAUMEUX,     6000},
    {SAY_MORG_TAUNT1,       NPC_MOGRAINE,     7000},
    {SAY_BLAU_TAUNT2,       NPC_BLAUMEUX,     6000},
    {SAY_ZELI_TAUNT2,       NPC_ZELIEK,       5000},
    {SAY_KORT_TAUNT2,       NPC_THANE,        7000},
    {SAY_MORG_TAUNT2,       NPC_MOGRAINE,     0},
    {SAY_FAERLINA_INTRO,    NPC_FAERLINA,     10000},
    {FOLLOWERS_STAND,       0,                3000},
    {FOLLOWERS_AURA,        0,                30000},
    {FOLLOWERS_KNEEL,       0,                0},
    {0,                     0,                0}
}
Definition at line 27 of file naxxramas.cpp.