CMaNGOS_TBC: PlayerDump.cpp File Reference
PlayerDump.cpp File Reference
#include "Common.h"
#include "Tools/PlayerDump.h"
#include "Database/DatabaseEnv.h"
#include "Server/SQLStorages.h"
#include "Entities/UpdateFields.h"
#include "Globals/ObjectMgr.h"
#include "Accounts/AccountMgr.h"
Data Structures
struct DumpTable
Macros
#define ROLLBACK(DR) {CharacterDatabase.RollbackTransaction(); fclose(fin); return (DR);}
Functions
static bool findtoknth (std::string &str, int n, std::string::size_type &s, std::string::size_type &e)
std::string gettoknth (std::string &str, int n)
bool findnth (std::string &str, int n, std::string::size_type &s, std::string::size_type &e)
std::string gettablename (std::string &str)
bool changenth (std::string &str, int n, const char *with, bool insert=false, bool nonzero=false)
std::string getnth (std::string &str, int n)
bool changetoknth (std::string &str, int n, const char *with, bool insert=false, bool nonzero=false)
uint32 registerNewGuid (uint32 oldGuid, std::map< uint32, uint32 > &guidMap, uint32 hiGuid)
bool changeGuid (std::string &str, int n, std::map< uint32, uint32 > &guidMap, uint32 hiGuid, bool nonzero=false)
bool changetokGuid (std::string &str, int n, std::map< uint32, uint32 > &guidMap, uint32 hiGuid, bool nonzero=false)
std::string CreateDumpString (char const *tableName, QueryResult *result)
void StoreGUID (QueryResult *result, uint32 field, std::set< uint32 > &guids)
void StoreGUID (QueryResult *result, uint32 data, uint32 field, std::set< uint32 > &guids)
Variables
static DumpTable dumpTables []
Macro Definition Documentation
ROLLBACK
#define ROLLBACK (DR) {CharacterDatabase.RollbackTransaction(); fclose(fin); return (DR);}
Definition at line 405 of file PlayerDump.cpp.
Function Documentation
changeGuid()
bool changeGuid (std::string & str, int n, std::map< uint32, uint32 > & guidMap, uint32 hiGuid, bool nonzero = false)
Definition at line 176 of file PlayerDump.cpp.
References changenth(), getnth(), and registerNewGuid().
Referenced by PlayerDumpReader::LoadDump().
changenth()
bool changenth (std::string & str, int n, const char * with, bool insert = false, bool nonzero = false)
Definition at line 125 of file PlayerDump.cpp.
References findnth().
Referenced by changeGuid(), and PlayerDumpReader::LoadDump().
changetokGuid()
bool changetokGuid (std::string & str, int n, std::map< uint32, uint32 > & guidMap, uint32 hiGuid, bool nonzero = false)
Definition at line 189 of file PlayerDump.cpp.
References changetoknth(), gettoknth(), and registerNewGuid().
changetoknth()
bool changetoknth (std::string & str, int n, const char * with, bool insert = false, bool nonzero = false)
Definition at line 150 of file PlayerDump.cpp.
References findtoknth().
Referenced by changetokGuid().
CreateDumpString()
std::string CreateDumpString (char const * tableName, QueryResult * result)
Definition at line 202 of file PlayerDump.cpp.
References _TABLE_SIM_, CharacterDatabase, Database::escape_string(), QueryResult::Fetch(), Field::GetCppString(), and QueryResult::GetFieldCount().
Referenced by PlayerDumpWriter::DumpTableContent().
findnth()
bool findnth (std::string & str, int n, std::string::size_type & s, std::string::size_type & e)
Definition at line 87 of file PlayerDump.cpp.
Referenced by changenth(), and getnth().
findtoknth()
static bool findtoknth (std::string & str, int n, std::string::size_type & s, std::string::size_type & e) static
Definition at line 65 of file PlayerDump.cpp.
Referenced by changetoknth(), and gettoknth().
getnth()
std::string getnth (std::string & str, int n)
Definition at line 141 of file PlayerDump.cpp.
References findnth().
Referenced by changeGuid(), and PlayerDumpReader::LoadDump().
gettablename()
std::string gettablename (std::string & str)
Definition at line 115 of file PlayerDump.cpp.
References _TABLE_SIM_.
Referenced by PlayerDumpReader::LoadDump().
gettoknth()
std::string gettoknth (std::string & str, int n)
Definition at line 78 of file PlayerDump.cpp.
References findtoknth().
Referenced by changetokGuid(), and StoreGUID().
registerNewGuid()
uint32 registerNewGuid (uint32 oldGuid, std::map< uint32, uint32 > & guidMap, uint32 hiGuid)
Definition at line 165 of file PlayerDump.cpp.
Referenced by changeGuid(), and changetokGuid().
StoreGUID() [1/2]
void StoreGUID (QueryResult * result, uint32 data, uint32 field, std::set< uint32 > & guids)
Definition at line 266 of file PlayerDump.cpp.
References QueryResult::Fetch(), Field::GetCppString(), and gettoknth().
StoreGUID() [2/2]
void StoreGUID (QueryResult * result, uint32 field, std::set< uint32 > & guids)
Definition at line 258 of file PlayerDump.cpp.
References QueryResult::Fetch(), and Field::GetUInt32().
Referenced by PlayerDumpWriter::DumpTableContent().
Variable Documentation
dumpTables
DumpTable dumpTables[] static
Initial value:
=
{
    { "characters",                       DTT_CHARACTER  },
    { "character_action",                 DTT_CHAR_TABLE },
    { "character_aura",                   DTT_CHAR_TABLE },
    { "character_declinedname",           DTT_CHAR_NAME_TABLE },
    { "character_homebind",               DTT_CHAR_TABLE },
    { "character_inventory",              DTT_INVENTORY  },
    { "character_queststatus",            DTT_CHAR_TABLE },
    { "character_pet",                    DTT_PET        },
    { "character_pet_declinedname",       DTT_PET_DECL   },
    { "character_reputation",             DTT_CHAR_TABLE },
    { "character_skills",                 DTT_CHAR_TABLE },
    { "character_spell",                  DTT_CHAR_TABLE },
    { "character_spell_cooldown",         DTT_CHAR_TABLE },
    { "mail",                             DTT_MAIL       },
    { "mail_items",                       DTT_MAIL_ITEM  },
    { "pet_aura",                         DTT_PET_TABLE  },
    { "pet_spell",                        DTT_PET_TABLE  },
    { "pet_spell_cooldown",               DTT_PET_TABLE  },
    { "character_gifts",                  DTT_ITEM_GIFT  },
    { "item_instance",                    DTT_ITEM       },
    { "item_loot",                        DTT_ITEM_LOOT  },
    { "item_text",                        DTT_ITEM_TEXT  },
    { nullptr,                            DTT_CHAR_TABLE },
}
Definition at line 37 of file PlayerDump.cpp.
Referenced by PlayerDumpWriter::GetDump(), and PlayerDumpReader::LoadDump().