var ScalingAuras_8cpp =
[
    [ "HunterPetScaling1", "structHunterPetScaling1.html", "structHunterPetScaling1" ],
    [ "HunterPetScaling2", "structHunterPetScaling2.html", "structHunterPetScaling2" ],
    [ "HunterPetScaling3", "structHunterPetScaling3.html", "structHunterPetScaling3" ],
    [ "WarlockPetScaling1", "structWarlockPetScaling1.html", "structWarlockPetScaling1" ],
    [ "WarlockPetScaling2", "structWarlockPetScaling2.html", "structWarlockPetScaling2" ],
    [ "WarlockPetScaling3", "structWarlockPetScaling3.html", "structWarlockPetScaling3" ],
    [ "WarlockPetScaling4", "structWarlockPetScaling4.html", "structWarlockPetScaling4" ],
    [ "MagePetScaling1", "structMagePetScaling1.html", "structMagePetScaling1" ],
    [ "MagePetScaling2", "structMagePetScaling2.html", "structMagePetScaling2" ],
    [ "MagePetScaling3", "structMagePetScaling3.html", "structMagePetScaling3" ],
    [ "MagePetScaling4", "structMagePetScaling4.html", "structMagePetScaling4" ],
    [ "PriestPetScaling1", "structPriestPetScaling1.html", "structPriestPetScaling1" ],
    [ "PriestPetScaling2", "structPriestPetScaling2.html", "structPriestPetScaling2" ],
    [ "PriestPetScaling3", "structPriestPetScaling3.html", "structPriestPetScaling3" ],
    [ "PriestPetScaling4", "structPriestPetScaling4.html", "structPriestPetScaling4" ],
    [ "ElementalPetScaling1", "structElementalPetScaling1.html", "structElementalPetScaling1" ],
    [ "ElementalPetScaling2", "structElementalPetScaling2.html", "structElementalPetScaling2" ],
    [ "ElementalPetScaling3", "structElementalPetScaling3.html", "structElementalPetScaling3" ],
    [ "ElementalPetScaling4", "structElementalPetScaling4.html", "structElementalPetScaling4" ],
    [ "DruidPetScaling1", "structDruidPetScaling1.html", "structDruidPetScaling1" ],
    [ "DruidPetScaling2", "structDruidPetScaling2.html", "structDruidPetScaling2" ],
    [ "DruidPetScaling3", "structDruidPetScaling3.html", "structDruidPetScaling3" ],
    [ "DruidPetScaling4", "structDruidPetScaling4.html", "structDruidPetScaling4" ],
    [ "EnhancementPetScaling1", "structEnhancementPetScaling1.html", "structEnhancementPetScaling1" ],
    [ "EnhancementPetScaling2", "structEnhancementPetScaling2.html", "structEnhancementPetScaling2" ],
    [ "EnhancementPetScaling3", "structEnhancementPetScaling3.html", "structEnhancementPetScaling3" ],
    [ "InfernalPetScaling1", "structInfernalPetScaling1.html", "structInfernalPetScaling1" ],
    [ "InfernalPetScaling2", "structInfernalPetScaling2.html", "structInfernalPetScaling2" ],
    [ "InfernalPetScaling3", "structInfernalPetScaling3.html", "structInfernalPetScaling3" ],
    [ "InfernalPetScaling4", "structInfernalPetScaling4.html", "structInfernalPetScaling4" ],
    [ "LoadScalingScripts", "ScalingAuras_8cpp.html#ad47fa60d71c3c98ad6ad58db9aff646e", null ]
];