CMaNGOS_TBC: spell_scripts.cpp File Reference
spell_scripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "Spells/Scripts/SpellScript.h"
#include "Grids/Cell.h"
#include "Grids/CellImpl.h"
#include "Grids/GridNotifiers.h"
#include "Grids/GridNotifiersImpl.h"
Data Structures
struct GreaterInvisibilityMob
struct InebriateRemoval
struct AstralBite
struct FelInfusion
struct AuchenaiPossess
struct GettingSleepyAura
struct AllergiesAura
struct RaiseDead
struct UseCorpse
struct SplitDamage
struct TKDive
struct CurseOfPain
struct spell_seed_of_corruption_npc
struct WondervoltTrap
struct ArcaneCloaking
struct FoodAnimation
struct DrinkAnimation
struct Drink
struct spell_effect_summon_no_follow_movement
struct SpellHasteHealerTrinket
struct IncreasedHealingDoneDummy
struct spell_scourge_strike
struct TribalDeath
struct RetaliationCreature
struct HateToHalf
struct HateToZero
struct PreventSpellIfSameAuraOnCaster
struct InstillLordValthalaksSpirit
struct Stoned
struct BirthNoVisualInstantSpawn
struct SleepVisualFlavor
struct CallOfTheFalcon
struct MaximizePetLoyalty
struct ForgetArmorsmith
struct ForgetWeaponsmith
struct ForgetSwordsmith
struct ForgetAxesmith
struct ForgetHammersmith
struct GameobjectCallForHelpOnUsage
struct Submerged
struct Stand
Enumerations
enum { SPELL_CAST_FISHING_NET = 29866 , GO_RED_SNAPPER = 181616 , NPC_ANGRY_MURLOC = 17102 , ITEM_RED_SNAPPER = 23614 }
enum {
SPELL_TAG_MURLOC = 30877 , SPELL_TAG_MURLOC_PROC = 30875 , NPC_BLACKSILT_MURLOC = 17326 , NPC_TAGGED_MURLOC = 17654 ,
SPELL_HEALING_SALVE = 29314 , SPELL_HEALING_SALVE_DUMMY = 29319 , NPC_MAGHAR_GRUNT = 16846 , SPELL_RECHARGING_BATTERY = 34219 ,
NPC_DRAINED_PHASE_HUNTER = 19595 , SPELL_ADMINISTER_ANTIDOTE = 34665 , NPC_HELBOAR = 16880 , NPC_DREADTUSK = 16992 ,
SPELL_FEL_SIPHON_DUMMY = 44936 , NPC_FELBLOOD_INITIATE = 24918 , NPC_EMACIATED_FELBLOOD = 24955 , SPELL_INOCULATE_OWLKIN = 29528 ,
NPC_OWLKIN = 16518 , NPC_OWLKIN_INOC = 16534 , SPELL_ORB_OF_MURLOC_CONTROL = 45109 , SPELL_GREENGILL_SLAVE_FREED = 45110 ,
SPELL_ENRAGE = 45111 , NPC_FREED_GREENGILL_SLAVE = 25085 , NPC_DARKSPINE_MYRMIDON = 25060 , NPC_DARKSPINE_SIREN = 25073 ,
SPELL_THROW_GORDAWG_BOULDER = 32001 , NPC_MINION_OF_GUROK = 18181 , SPELL_SHROUD_OF_DEATH = 10848 , SPELL_SPIRIT_PARTICLES = 17327 ,
NPC_FRANCLORN_FORGEWRIGHT = 8888 , NPC_GAERIYAN = 9299 , SPELL_PROTOVOLTAIC_MAGNETO_COLLECTOR = 37136 , NPC_ENCASED_ELECTROMENTAL = 21731 ,
SPELL_MELODIOUS_RAPTURE = 21050 , SPELL_MELODIOUS_RAPTURE_VISUAL = 21051 , NPC_DEEPRUN_RAT = 13016 , NPC_ENTHRALLED_DEEPRUN_RAT = 13017
}
enum { SPELL_POSSESS = 32830 , SPELL_POSSESS_BUFF = 32831 , SPELL_POSSESS_INVIS = 32832 , SPELL_KNOCKDOWN = 13360 }
enum { SPELL_USE_CORPSE = 33985 }
enum SeedOfCorruptionNpc { SPELL_SEED_OF_CORRUPTION_PROC_DEFAULT = 32865 , SPELL_SEED_OF_CORRUPTION_NPC_24558 = 44141 , SPELL_SEED_OF_CORRUPTION_PROC_NPC_24558 = 43991 }
enum SpellVisualKitFoodOrDrink { SPELL_VISUAL_KIT_FOOD = 406 , SPELL_VISUAL_KIT_DRINK = 438 }
enum {
SPELL_THISTLEFUR_DEATH = 8603 , SPELL_RIVERPAW_DEATH = 8655 , SPELL_STROMGARDE_DEATH = 8894 , SPELL_CRUSHRIDGE_DEATH = 9144 ,
SAY_RAGE_FALLEN = 1151
}
enum spell_call_of_the_falcon { YELL_KILL_FALCONER = 17624 , NPC_BLOODWARDER_FALCONER = 17994 , NPC_BLOODFALCON = 18155 , SPELL_CALL_OF_THE_FALCON = 34853 }
Functions
bool EffectDummyGameObj_spell_dummy_go (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, GameObject *pGOTarget, ObjectGuid)
bool EffectAuraDummy_spell_aura_dummy_npc (const Aura *pAura, bool bApply)
bool EffectDummyCreature_spell_dummy_npc (Unit *pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature *pCreatureTarget, ObjectGuid)
void AddSC_spell_scripts ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_CAST_FISHING_NET
GO_RED_SNAPPER
NPC_ANGRY_MURLOC
ITEM_RED_SNAPPER
Definition at line 50 of file spell_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_TAG_MURLOC
SPELL_TAG_MURLOC_PROC
NPC_BLACKSILT_MURLOC
NPC_TAGGED_MURLOC
SPELL_HEALING_SALVE
SPELL_HEALING_SALVE_DUMMY
NPC_MAGHAR_GRUNT
SPELL_RECHARGING_BATTERY
NPC_DRAINED_PHASE_HUNTER
SPELL_ADMINISTER_ANTIDOTE
NPC_HELBOAR
NPC_DREADTUSK
SPELL_FEL_SIPHON_DUMMY
NPC_FELBLOOD_INITIATE
NPC_EMACIATED_FELBLOOD
SPELL_INOCULATE_OWLKIN
NPC_OWLKIN
NPC_OWLKIN_INOC
SPELL_ORB_OF_MURLOC_CONTROL
SPELL_GREENGILL_SLAVE_FREED
SPELL_ENRAGE
NPC_FREED_GREENGILL_SLAVE
NPC_DARKSPINE_MYRMIDON
NPC_DARKSPINE_SIREN
SPELL_THROW_GORDAWG_BOULDER
NPC_MINION_OF_GUROK
SPELL_SHROUD_OF_DEATH
SPELL_SPIRIT_PARTICLES
NPC_FRANCLORN_FORGEWRIGHT
NPC_GAERIYAN
SPELL_PROTOVOLTAIC_MAGNETO_COLLECTOR
NPC_ENCASED_ELECTROMENTAL
SPELL_MELODIOUS_RAPTURE
SPELL_MELODIOUS_RAPTURE_VISUAL
NPC_DEEPRUN_RAT
NPC_ENTHRALLED_DEEPRUN_RAT
Definition at line 92 of file spell_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_POSSESS
SPELL_POSSESS_BUFF
SPELL_POSSESS_INVIS
SPELL_KNOCKDOWN
Definition at line 456 of file spell_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_USE_CORPSE
Definition at line 517 of file spell_scripts.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_THISTLEFUR_DEATH
SPELL_RIVERPAW_DEATH
SPELL_STROMGARDE_DEATH
SPELL_CRUSHRIDGE_DEATH
SAY_RAGE_FALLEN
Definition at line 791 of file spell_scripts.cpp.
SeedOfCorruptionNpc
enum SeedOfCorruptionNpc
Enumerator
SPELL_SEED_OF_CORRUPTION_PROC_DEFAULT
SPELL_SEED_OF_CORRUPTION_NPC_24558
SPELL_SEED_OF_CORRUPTION_PROC_NPC_24558
Definition at line 588 of file spell_scripts.cpp.
spell_call_of_the_falcon
enum spell_call_of_the_falcon
Enumerator
YELL_KILL_FALCONER
NPC_BLOODWARDER_FALCONER
NPC_BLOODFALCON
SPELL_CALL_OF_THE_FALCON
Definition at line 942 of file spell_scripts.cpp.
SpellVisualKitFoodOrDrink
enum SpellVisualKitFoodOrDrink
Enumerator
SPELL_VISUAL_KIT_FOOD
SPELL_VISUAL_KIT_DRINK
Definition at line 684 of file spell_scripts.cpp.
Function Documentation
AddSC_spell_scripts()
void AddSC_spell_scripts ()
Definition at line 1153 of file spell_scripts.cpp.
References EffectAuraDummy_spell_aura_dummy_npc(), EffectDummyCreature_spell_dummy_npc(), EffectDummyGameObj_spell_dummy_go(), Script::Name, Script::pEffectAuraDummy, Script::pEffectDummyGO, Script::pEffectDummyNPC, and Script::RegisterSelf().
Referenced by AddScripts().
EffectAuraDummy_spell_aura_dummy_npc()
bool EffectAuraDummy_spell_aura_dummy_npc (const Aura * pAura, bool bApply)
Definition at line 153 of file spell_scripts.cpp.
References Creature::AI(), UnitAI::AttackStart(), AURA_STATE_HEALTHLESS_35_PERCENT, Unit::CastSpell(), EFFECT_INDEX_0, Creature::ForcedDespawn(), Aura::GetCaster(), GetClosestCreatureWithEntry(), Aura::GetEffIndex(), Object::GetEntry(), Aura::GetId(), Unit::getStandState(), Aura::GetTarget(), Object::GetTypeId(), Unit::HasAuraState(), IN_MILLISECONDS, Unit::m_AuraFlags, NPC_BLACKSILT_MURLOC, NPC_DARKSPINE_MYRMIDON, NPC_DARKSPINE_SIREN, NPC_DRAINED_PHASE_HUNTER, NPC_ENCASED_ELECTROMENTAL, NPC_FRANCLORN_FORGEWRIGHT, NPC_GAERIYAN, NPC_MAGHAR_GRUNT, NPC_TAGGED_MURLOC, Unit::SetStandState(), SPELL_ENRAGE, SPELL_HEALING_SALVE, SPELL_HEALING_SALVE_DUMMY, SPELL_PROTOVOLTAIC_MAGNETO_COLLECTOR, SPELL_RECHARGING_BATTERY, SPELL_SHROUD_OF_DEATH, SPELL_SPIRIT_PARTICLES, SPELL_TAG_MURLOC, SPELL_TAG_MURLOC_PROC, TRIGGERED_OLD_TRIGGERED, TYPEID_UNIT, UNIT_AURAFLAG_ALIVE_INVISIBLE, UNIT_STAND_STATE_KNEEL, UNIT_STAND_STATE_STAND, and Creature::UpdateEntry().
Referenced by AddSC_spell_scripts().
EffectDummyCreature_spell_dummy_npc()
bool EffectDummyCreature_spell_dummy_npc (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, Creature * pCreatureTarget, ObjectGuid)
Definition at line 276 of file spell_scripts.cpp.
References Creature::AIM_Initialize(), Unit::CastSpell(), EFFECT_INDEX_0, Creature::ForcedDespawn(), frand(), Object::GetEntry(), Unit::GetMotionMaster(), Object::GetTypeId(), irand(), M_PI_F, MotionMaster::MoveFollow(), NPC_BLACKSILT_MURLOC, NPC_DEEPRUN_RAT, NPC_DREADTUSK, NPC_EMACIATED_FELBLOOD, NPC_ENTHRALLED_DEEPRUN_RAT, NPC_FELBLOOD_INITIATE, NPC_FREED_GREENGILL_SLAVE, NPC_HELBOAR, NPC_MINION_OF_GUROK, NPC_OWLKIN, NPC_OWLKIN_INOC, NPC_TAGGED_MURLOC, SPELL_ADMINISTER_ANTIDOTE, SPELL_ENRAGE, SPELL_FEL_SIPHON_DUMMY, SPELL_GREENGILL_SLAVE_FREED, SPELL_INOCULATE_OWLKIN, SPELL_MELODIOUS_RAPTURE, SPELL_MELODIOUS_RAPTURE_VISUAL, SPELL_ORB_OF_MURLOC_CONTROL, SPELL_TAG_MURLOC_PROC, SPELL_THROW_GORDAWG_BOULDER, WorldObject::SummonCreature(), TEMPSPAWN_CORPSE_DESPAWN, TRIGGERED_NONE, TRIGGERED_OLD_TRIGGERED, TYPEID_PLAYER, and Creature::UpdateEntry().
Referenced by AddSC_spell_scripts().
EffectDummyGameObj_spell_dummy_go()
bool EffectDummyGameObj_spell_dummy_go (Unit * pCaster, uint32 uiSpellId, SpellEffectIndex uiEffIndex, GameObject * pGOTarget, ObjectGuid)
Definition at line 60 of file spell_scripts.cpp.
References EFFECT_INDEX_0, Object::GetEntry(), WorldObject::GetPositionX(), WorldObject::GetPositionY(), WorldObject::GetPositionZ(), GameObject::GetRespawnTime(), Object::GetTypeId(), GO_JUST_DEACTIVATED, GO_RED_SNAPPER, ITEM_RED_SNAPPER, NPC_ANGRY_MURLOC, GameObject::SetLootState(), SPELL_CAST_FISHING_NET, WorldObject::SummonCreature(), TEMPSPAWN_TIMED_OOC_DESPAWN, TYPEID_PLAYER, and urand().
Referenced by AddSC_spell_scripts().