CMaNGOS_TBC: ClassFamilyMask Struct Reference
ClassFamilyMask Struct Reference
#include <DBCStructure.h>
Public Member Functions
ClassFamilyMask ()
ClassFamilyMask (uint64 familyFlags)
bool Empty () const
bool operator! () const
operator void const * () const
bool operator== (const ClassFamilyMask &another) const
bool IsFitToFamilyMask (uint64 familyFlags) const
bool IsFitToFamilyMask (ClassFamilyMask const &mask) const
uint64 operator& (uint64 mask) const
ClassFamilyMask & operator|= (ClassFamilyMask const &mask)
Data Fields
uint64 Flags
Detailed Description
Definition at line 856 of file DBCStructure.h.
Constructor & Destructor Documentation
ClassFamilyMask() [1/2]
ClassFamilyMask::ClassFamilyMask () inline
Definition at line 860 of file DBCStructure.h.
ClassFamilyMask() [2/2]
ClassFamilyMask::ClassFamilyMask (uint64 familyFlags) inline explicit
Definition at line 861 of file DBCStructure.h.
Member Function Documentation
Empty()
bool ClassFamilyMask::Empty () const inline
Definition at line 863 of file DBCStructure.h.
References Flags.
Referenced by SpellMgr::IsSingleTargetSpells(), IsStackableAuraEffect(), operator void const *(), and operator!().
IsFitToFamilyMask() [1/2]
bool ClassFamilyMask::IsFitToFamilyMask (ClassFamilyMask const & mask) const inline
Definition at line 869 of file DBCStructure.h.
References Flags.
IsFitToFamilyMask() [2/2]
bool ClassFamilyMask::IsFitToFamilyMask (uint64 familyFlags) const inline
Definition at line 868 of file DBCStructure.h.
References Flags.
Referenced by Player::AddSpellMod(), Aura::CanProcFrom(), and SpellEntry::IsFitToFamilyMask().
operator void const *()
ClassFamilyMask::operator void const * () const inline
Definition at line 865 of file DBCStructure.h.
References Empty().
operator!()
bool ClassFamilyMask::operator! () const inline
Definition at line 864 of file DBCStructure.h.
References Empty().
operator&()
uint64 ClassFamilyMask::operator& (uint64 mask) const inline
Definition at line 872 of file DBCStructure.h.
References Flags.
operator==()
bool ClassFamilyMask::operator== (const ClassFamilyMask & another) const inline
Definition at line 866 of file DBCStructure.h.
References Flags.
operator|=()
ClassFamilyMask& ClassFamilyMask::operator|= (ClassFamilyMask const & mask) inline
Definition at line 874 of file DBCStructure.h.
References Flags.
Field Documentation
Flags
uint64 ClassFamilyMask::Flags
Definition at line 858 of file DBCStructure.h.
Referenced by Empty(), IsFitToFamilyMask(), operator&(), operator==(), and operator|=().
The documentation for this struct was generated from the following file:
DBCStructure.h