CMaNGOS_TBC: DynamicTreeIntersectionCallback Struct Reference
DynamicTreeIntersectionCallback Struct Reference
Public Member Functions
DynamicTreeIntersectionCallback ()
bool operator() (const G3D::Ray &r, const GameObjectModel &obj, float &distance, bool stopAtFirst, bool ignoreM2Model)
bool didHit () const
Data Fields
bool did_hit
Detailed Description
Definition at line 141 of file DynamicTree.cpp.
Constructor & Destructor Documentation
DynamicTreeIntersectionCallback()
DynamicTreeIntersectionCallback::DynamicTreeIntersectionCallback () inline
Definition at line 144 of file DynamicTree.cpp.
Member Function Documentation
didHit()
bool DynamicTreeIntersectionCallback::didHit () const inline
Definition at line 150 of file DynamicTree.cpp.
References did_hit.
Referenced by DynamicMapTree::getHeight(), and DynamicMapTree::getIntersectionTime().
operator()()
bool DynamicTreeIntersectionCallback::operator() (const G3D::Ray & r, const GameObjectModel & obj, float & distance, bool stopAtFirst, bool ignoreM2Model) inline
Definition at line 145 of file DynamicTree.cpp.
References did_hit, and GameObjectModel::intersectRay().
Field Documentation
did_hit
bool DynamicTreeIntersectionCallback::did_hit
Definition at line 143 of file DynamicTree.cpp.
Referenced by didHit(), DynamicMapTree::isInLineOfSight(), and operator()().
The documentation for this struct was generated from the following file:
DynamicTree.cpp