CMaNGOS_TBC: MapEntry Struct Reference
MapEntry Struct Reference
#include <DBCStructure.h>
Public Member Functions
uint32 Expansion () const
bool IsDungeon () const
bool IsNonRaidDungeon () const
bool Instanceable () const
bool IsRaid () const
bool IsBattleGround () const
bool IsBattleArena () const
bool IsBattleGroundOrArena () const
bool SupportsHeroicMode () const
bool HasResetTime () const
bool IsContinent () const
Data Fields
uint32 MapID
uint32 map_type
char * name [16]
uint32 linked_zone
uint32 multimap_id
int32 ghost_entrance_map
float ghost_entrance_x
float ghost_entrance_y
uint32 resetTimeRaid
uint32 resetTimeHeroic
uint32 addon
Detailed Description
Definition at line 714 of file DBCStructure.h.
Member Function Documentation
Expansion()
uint32 MapEntry::Expansion () const inline
Definition at line 748 of file DBCStructure.h.
References addon.
Referenced by Player::_LoadHomeBind(), Player::GetAreaTriggerLockStatus(), GetContentLevelsForMapAndZone(), WorldSession::HandlePlayerLogin(), and Player::LoadFromDB().
HasResetTime()
bool MapEntry::HasResetTime () const inline
Definition at line 758 of file DBCStructure.h.
References resetTimeHeroic, and resetTimeRaid.
Referenced by ObjectMgr::LoadInstanceTemplate(), and DungeonResetScheduler::LoadResetTimes().
Instanceable()
bool MapEntry::Instanceable () const inline
Definition at line 752 of file DBCStructure.h.
References MAP_ARENA, MAP_BATTLEGROUND, MAP_INSTANCE, MAP_RAID, and map_type.
Referenced by Player::_LoadHomeBind(), MapManager::CreateMap(), MapPersistentStateManager::DoForAllStatesWithMapId(), ObjectMgr::GetMapEntranceTrigger(), ChatHandler::HandleGoZoneXYCommand(), ChatHandler::HandlePoolListCommand(), ChatHandler::HandlePoolSpawnsCommand(), Map::Instanceable(), MapPersistentStateManager::LoadCreatureRespawnTimes(), MapPersistentStateManager::LoadGameobjectRespawnTimes(), ObjectMgr::LoadInstanceTemplate(), and ObjectMgr::LoadWorldTemplate().
IsBattleArena()
bool MapEntry::IsBattleArena () const inline
Definition at line 755 of file DBCStructure.h.
References MAP_ARENA, and map_type.
Referenced by Map::IsBattleArena().
IsBattleGround()
bool MapEntry::IsBattleGround () const inline
Definition at line 754 of file DBCStructure.h.
References MAP_BATTLEGROUND, and map_type.
Referenced by SpellMgr::GetSpellAllowedInLocationError(), Map::IsBattleGround(), ObjectMgr::LoadCreatures(), and ObjectMgr::LoadGameObjects().
IsBattleGroundOrArena()
bool MapEntry::IsBattleGroundOrArena () const inline
Definition at line 756 of file DBCStructure.h.
References MAP_ARENA, MAP_BATTLEGROUND, and map_type.
Referenced by MapPersistentStateManager::AddPersistentState(), MapManager::CreateInstance(), ChatHandler::HandleGoXYZCommand(), WorldSession::HandleMoveWorldportAckOpcode(), Map::IsBattleGroundOrArena(), Player::LoadFromDB(), and Player::TeleportTo().
IsContinent()
bool MapEntry::IsContinent () const inline
Definition at line 760 of file DBCStructure.h.
Referenced by SpellMgr::GetSpellAllowedInLocationError(), Map::IsContinent(), ObjectMgr::LoadCreatures(), ObjectMgr::LoadGameObjects(), ObjectMgr::LoadInstanceTemplate(), and Player::SendTransferAbortedByLockStatus().
IsDungeon()
bool MapEntry::IsDungeon () const inline
Definition at line 750 of file DBCStructure.h.
References MAP_INSTANCE, MAP_RAID, and map_type.
Referenced by Player::_LoadBoundInstances(), MapPersistentStateManager::_ResetOrWarnAll(), MapPersistentStateManager::AddPersistentState(), Spell::CheckCast(), DungeonMap::DungeonMap(), Spell::EffectTeleportUnits(), Player::GetAreaTriggerLockStatus(), WorldSession::HandleAreaTriggerOpcode(), Map::IsDungeon(), MapManager::IsValidMAP(), MapPersistentStateManager::LoadCreatureRespawnTimes(), ObjectMgr::LoadCreatures(), MapPersistentStateManager::LoadGameobjectRespawnTimes(), ObjectMgr::LoadGameObjects(), ObjectMgr::LoadGroups(), DungeonResetScheduler::LoadResetTimes(), and Group::ResetInstances().
IsNonRaidDungeon()
bool MapEntry::IsNonRaidDungeon () const inline
Definition at line 751 of file DBCStructure.h.
References MAP_INSTANCE, and map_type.
Referenced by DungeonMap::Add(), Player::GetAreaTriggerLockStatus(), and Map::IsNoRaid().
IsRaid()
bool MapEntry::IsRaid () const inline
Definition at line 753 of file DBCStructure.h.
References MAP_RAID, and map_type.
Referenced by Player::GetAreaTriggerLockStatus(), SpellMgr::GetSpellAllowedInLocationError(), WorldSession::HandleMoveWorldportAckOpcode(), and Map::IsRaid().
SupportsHeroicMode()
bool MapEntry::SupportsHeroicMode () const inline
Definition at line 757 of file DBCStructure.h.
References resetTimeHeroic, and resetTimeRaid.
Referenced by MapManager::CreateDungeonMap(), Group::GetBoundInstance(), Player::GetBoundInstance(), and ObjectMgr::LoadInstanceTemplate().
Field Documentation
addon
uint32 MapEntry::addon
Definition at line 745 of file DBCStructure.h.
Referenced by Expansion(), and SpellMgr::GetSpellAllowedInLocationError().
ghost_entrance_map
int32 MapEntry::ghost_entrance_map
Definition at line 738 of file DBCStructure.h.
Referenced by GraveyardManager::GetClosestGraveyardHelper(), ObjectMgr::GetGoBackTrigger(), and LoadDBCStores().
ghost_entrance_x
float MapEntry::ghost_entrance_x
Definition at line 739 of file DBCStructure.h.
Referenced by GraveyardManager::GetClosestGraveyardHelper().
ghost_entrance_y
float MapEntry::ghost_entrance_y
Definition at line 740 of file DBCStructure.h.
Referenced by GraveyardManager::GetClosestGraveyardHelper().
linked_zone
uint32 MapEntry::linked_zone
Definition at line 724 of file DBCStructure.h.
map_type
uint32 MapEntry::map_type
Definition at line 718 of file DBCStructure.h.
Referenced by MapPersistentStateManager::AddPersistentState(), DungeonPersistentState::GetResetTimeForDB(), Instanceable(), IsBattleArena(), IsBattleGround(), IsBattleGroundOrArena(), IsDungeon(), IsNonRaidDungeon(), IsRaid(), ObjectMgr::LoadInstanceTemplate(), Player::ResetInstances(), Group::ResetInstances(), and Pet::SetDeathState().
MapID
uint32 MapEntry::MapID
Definition at line 716 of file DBCStructure.h.
Referenced by MapPersistentStateManager::AddPersistentState(), PoolMapChecker::CheckAndRemember(), Player::CheckAndRevivePlayerOnDungeonEnter(), PoolManager::DespawnPoolInMaps(), ChatHandler::HandleGoZoneXYCommand(), WorldSession::HandleMoveWorldportAckOpcode(), ObjectMgr::LoadInstanceTemplate(), MapManager::LoadTransports(), Player::SendTransferAbortedByLockStatus(), PoolManager::SpawnPoolInMaps(), and PoolManager::UpdatePoolInMaps().
multimap_id
uint32 MapEntry::multimap_id
Definition at line 729 of file DBCStructure.h.
name
char* MapEntry::name[16]
Definition at line 720 of file DBCStructure.h.
Referenced by Player::CheckAndRevivePlayerOnDungeonEnter(), NamreebAnticheat::Movement::CheckTeleport(), Map::GetMapName(), ChatHandler::HandleGoZoneXYCommand(), ChatHandler::HandleGPSCommand(), ChatHandler::HandlePoolListCommand(), ChatHandler::HandlePoolSpawnsCommand(), and TerrainInfo::LoadMapAndVMap().
resetTimeHeroic
uint32 MapEntry::resetTimeHeroic
Definition at line 742 of file DBCStructure.h.
Referenced by HasResetTime(), ObjectMgr::LoadInstanceTemplate(), and SupportsHeroicMode().
resetTimeRaid
uint32 MapEntry::resetTimeRaid
Definition at line 741 of file DBCStructure.h.
Referenced by HasResetTime(), ObjectMgr::LoadInstanceTemplate(), and SupportsHeroicMode().
The documentation for this struct was generated from the following file:
DBCStructure.h