CMaNGOS_TBC: LookingForGroupInfo Struct Reference
LookingForGroupInfo Struct Reference
#include <Player.h>
Data Structures
struct Slot
Public Member Functions
void clear ()
bool isAutoFill () const
bool isAutoJoin () const
bool isEmpty () const
bool isLFG () const
bool isLFG (uint32 entry, uint32 type, bool autoOnly) const
bool isLFG (LookingForGroupInfo const &info, bool autoOnly) const
bool isLFM () const
bool isLFM (uint32 entry, uint32 type) const
Data Fields
Slot group [MAX_LOOKING_FOR_GROUP_SLOT]
Slot more
std::string comment
Detailed Description
Definition at line 307 of file Player.h.
Member Function Documentation
clear()
void LookingForGroupInfo::clear () inline
Definition at line 321 of file Player.h.
References LookingForGroupInfo::Slot::clear(), group, and more.
Referenced by LookingForGroupClear().
isAutoFill()
bool LookingForGroupInfo::isAutoFill () const inline
Definition at line 327 of file Player.h.
References LookingForGroupInfo::Slot::isAuto(), and more.
Referenced by LookingForGroupUpdateQueueStatus().
isAutoJoin()
bool LookingForGroupInfo::isAutoJoin () const inline
Definition at line 328 of file Player.h.
References group.
Referenced by LookingForGroupUpdateQueueStatus().
isEmpty()
bool LookingForGroupInfo::isEmpty () const inline
Definition at line 335 of file Player.h.
References isLFG(), and isLFM().
Referenced by Channel::Join(), and LookingForGroupUpdateChannelStatus().
isLFG() [1/3]
bool LookingForGroupInfo::isLFG () const inline
Definition at line 336 of file Player.h.
References group.
Referenced by isEmpty(), LookingForGroupClearLFG(), LookingForGroupTryFill(), LookingForGroupTryJoin(), and WorldSession::SendLFGListQueryResponse().
isLFG() [2/3]
bool LookingForGroupInfo::isLFG (LookingForGroupInfo const & info, bool autoOnly) const inline
Definition at line 350 of file Player.h.
References LookingForGroupInfo::Slot::entry, isLFG(), more, and LookingForGroupInfo::Slot::type.
Referenced by isLFG().
isLFG() [3/3]
bool LookingForGroupInfo::isLFG (uint32 entry, uint32 type, bool autoOnly) const inline
Definition at line 343 of file Player.h.
References group.
isLFM() [1/2]
bool LookingForGroupInfo::isLFM () const inline
Definition at line 351 of file Player.h.
References LookingForGroupInfo::Slot::empty(), and more.
Referenced by WorldSession::HandleSetLfgOpcode(), isEmpty(), LookingForGroupClearLFM(), WorldSession::SendLFGListQueryResponse(), and WorldSession::SendLFGUpdateLFM().
isLFM() [2/2]
bool LookingForGroupInfo::isLFM (uint32 entry, uint32 type) const inline
Definition at line 352 of file Player.h.
References LookingForGroupInfo::Slot::is(), and more.
Field Documentation
comment
std::string LookingForGroupInfo::comment
Definition at line 357 of file Player.h.
Referenced by WorldSession::HandleSetLfgCommentOpcode(), and WorldSession::SendLFGListQueryResponse().
group
Slot LookingForGroupInfo::group[MAX_LOOKING_FOR_GROUP_SLOT]
Definition at line 355 of file Player.h.
Referenced by clear(), WorldSession::HandleSetLfgOpcode(), isAutoJoin(), isLFG(), LookingForGroupClearLFG(), WorldSession::SendLFGListQueryResponse(), and WorldSession::SendLFGUpdateLFG().
more
Slot LookingForGroupInfo::more
Definition at line 356 of file Player.h.
Referenced by clear(), WorldSession::HandleSetLfmOpcode(), isAutoFill(), isLFG(), isLFM(), LookingForGroupClearLFM(), LookingForGroupTryFill(), LookingForGroupTryJoin(), WorldSession::SendLFGListQueryResponse(), and WorldSession::SendLFGUpdateLFM().
The documentation for this struct was generated from the following file:
Player.h