CMaNGOS_TBC: LookingForGroupInfo::Slot Struct Reference
LookingForGroupInfo::Slot Struct Reference
#include <Player.h>
Public Member Functions
bool empty () const
void clear ()
bool set (uint16 _entry, uint16 _type)
bool is (uint16 _entry, uint16 _type) const
bool isAuto () const
Data Fields
uint16 entry = 0
uint16 type = LFG_TYPE_DUNGEON
Detailed Description
Definition at line 309 of file Player.h.
Member Function Documentation
clear()
void LookingForGroupInfo::Slot::clear () inline
Definition at line 312 of file Player.h.
References entry.
Referenced by LookingForGroupInfo::clear(), LookingForGroupClearLFG(), and LookingForGroupClearLFM().
empty()
bool LookingForGroupInfo::Slot::empty () const inline
Definition at line 311 of file Player.h.
References entry, and type.
Referenced by LookingForGroupInfo::isLFM(), LookingForGroupTryFill(), LookingForGroupTryJoin(), and set().
is()
bool LookingForGroupInfo::Slot::is (uint16 _entry, uint16 _type) const inline
Definition at line 314 of file Player.h.
References entry, and type.
Referenced by LookingForGroupInfo::isLFM().
isAuto()
bool LookingForGroupInfo::Slot::isAuto () const inline
Definition at line 315 of file Player.h.
References entry, LFG_TYPE_DUNGEON, LFG_TYPE_HEROIC_DUNGEON, and type.
Referenced by LookingForGroupInfo::isAutoFill().
set()
bool LookingForGroupInfo::Slot::set (uint16 _entry, uint16 _type) inline
Definition at line 313 of file Player.h.
References empty(), entry, and type.
Referenced by WorldSession::HandleSetLfgOpcode(), and WorldSession::HandleSetLfmOpcode().
Field Documentation
entry
uint16 LookingForGroupInfo::Slot::entry = 0
Definition at line 317 of file Player.h.
Referenced by clear(), empty(), is(), isAuto(), LookingForGroupInfo::isLFG(), LookingForGroupTryFill(), LookingForGroupTryJoin(), WorldSession::SendLFGListQueryResponse(), and set().
type
uint16 LookingForGroupInfo::Slot::type = LFG_TYPE_DUNGEON
Definition at line 318 of file Player.h.
Referenced by empty(), is(), isAuto(), LookingForGroupInfo::isLFG(), WorldSession::SendLFGListQueryResponse(), and set().
The documentation for this struct was generated from the following file:
Player.h