CMaNGOS_TBC: Util.h File Reference
Util.h File Reference
#include "Common.h"
#include <string>
#include <vector>
#include <random>
Data Structures
struct Die< Side, Default, Sides >
Typedefs
typedef std::vector< std::string > Tokens
Functions
Tokens StrSplit (const std::string &src, const std::string &sep)
uint32 GetUInt32ValueFromArray (Tokens const &data, uint16 index)
float GetFloatValueFromArray (Tokens const &data, uint16 index)
void stripLineInvisibleChars (std::string &str)
time_t GetLocalHourTimestamp (time_t time, uint8 hour, bool onlyAfterTime=true)
std::string secsToTimeString (time_t timeInSecs, bool shortText=false, bool hoursOnly=false)
uint32 TimeStringToSecs (const std::string &timestring)
std::string TimeToTimestampStr (time_t t)
time_t timeBitFieldsToSecs (uint32 packedDate)
uint32 secsToTimeBitFields (time_t secs)
std::mt19937 * GetRandomGenerator ()
int32 irand (int32 min, int32 max)
uint32 urand (uint32 min, uint32 max)
float frand (float min, float max)
int32 irand ()
uint32 urand ()
double rand_norm (void)
float rand_norm_f (void)
double rand_chance (void)
float rand_chance_f (void)
bool roll_chance_f (float chance)
bool roll_chance_i (int chance)
uint32 chance_u (float chance)
bool roll_chance_combat (float chance)
template<typename T , typename... Args>
T PickRandomValue (T first, Args ...rest)
void ApplyModUInt32Var (uint32 &var, int32 val, bool apply)
void ApplyModFloatVar (float &var, float val, bool apply)
void ApplyPercentModFloatVar (float &var, float val, bool apply)
bool Utf8toWStr (const std::string &utf8str, std::wstring &wstr, size_t max_len=0)
bool WStrToUtf8 (const std::wstring &wstr, std::string &utf8str)
size_t utf8length (std::string &utf8str)
size_t utf8limit (std::string &utf8str, size_t bytes)
void utf8truncate (std::string &utf8str, size_t len)
bool isBasicLatinCharacter (wchar_t wchar)
bool isExtendedLatinCharacter (wchar_t wchar)
bool isCyrillicCharacter (wchar_t wchar)
bool isEastAsianCharacter (wchar_t wchar)
bool isWhiteSpace (char c)
bool isNumeric (wchar_t wchar)
bool isNumeric (char c)
bool isNumericOrSpace (wchar_t wchar)
bool isNumeric (char const *str)
bool isNumeric (std::string const &str)
bool isNumeric (std::wstring const &str)
bool isBasicLatinString (const std::wstring &wstr, bool numericOrSpace)
bool isExtendedLatinString (const std::wstring &wstr, bool numericOrSpace)
bool isCyrillicString (const std::wstring &wstr, bool numericOrSpace)
bool isEastAsianString (const std::wstring &wstr, bool numericOrSpace)
void strToUpper (std::string &str)
void strToLower (std::string &str)
wchar_t wcharToUpper (wchar_t wchar)
wchar_t wcharToUpperOnlyLatin (wchar_t wchar)
wchar_t wcharToLower (wchar_t wchar)
void wstrToUpper (std::wstring &str)
void wstrToLower (std::wstring &str)
std::wstring GetMainPartOfName (const std::wstring &wname, uint32 declension)
bool utf8ToConsole (const std::string &utf8str, std::string &conStr)
bool consoleToUtf8 (const std::string &conStr, std::string &utf8str)
bool Utf8FitTo (const std::string &str, const std::wstring &search)
void utf8printf (FILE *out, const char *str,...)
void vutf8printf (FILE *out, const char *str, va_list *ap)
bool IsIPAddress (char const *ipaddress)
Check if the string is a valid ip address representation.
uint32 CreatePIDFile (const std::string &filename)
create PID file
void hexEncodeByteArray (uint8 *bytes, uint32 arrayLen, std::string &result)
template<typename E >
constexpr std::underlying_type< E >::type AsUnderlyingType (E enumValue)
Typedef Documentation
Tokens
typedef std::vector<std::string> Tokens
Definition at line 28 of file Util.h.
Function Documentation
ApplyModFloatVar()
void ApplyModFloatVar (float & var, float val, bool apply) inline
Definition at line 149 of file Util.h.
References ByteConverter::apply().
ApplyModUInt32Var()
void ApplyModUInt32Var (uint32 & var, int32 val, bool apply) inline
Definition at line 140 of file Util.h.
References ByteConverter::apply().
ApplyPercentModFloatVar()
void ApplyPercentModFloatVar (float & var, float val, bool apply) inline
Definition at line 156 of file Util.h.
References ByteConverter::apply().
Referenced by Unit::ApplyAttackTimePercentMod(), Aura::HandleAuraDummy(), Aura::HandleAuraModShapeshift(), and Aura::HandleModThreat().
AsUnderlyingType()
template<typename E > constexpr std::underlying_type<E>::type AsUnderlyingType (E enumValue) constexpr
Definition at line 396 of file Util.h.
Referenced by VisibilityData::SetVisibilityDistanceOverride().
chance_u()
uint32 chance_u (float chance) inline
Definition at line 93 of file Util.h.
Referenced by roll_chance_combat(), and Die< Side, Default, Sides >::set().
consoleToUtf8()
bool consoleToUtf8 (const std::string & conStr, std::string & utf8str)
Definition at line 508 of file Util.cpp.
References WStrToUtf8().
Referenced by CliRunnable::run().
CreatePIDFile()
uint32 CreatePIDFile (const std::string & filename)
create PID file
Definition at line 311 of file Util.cpp.
Referenced by main(), and Master::Run().
frand()
float frand (float min, float max)
Definition at line 80 of file Util.cpp.
Referenced by FleeingMovementGenerator::_setLocation(), FormationSlotData::AddPositionVariation(), Unit::CalculateDamage(), EffectDummyCreature_spell_dummy_npc(), Spell::EffectScriptEffect(), Spell::EffectSummonType(), ChaseMovementGenerator::FanOut(), PlayerbotClassAI::FleeFromPointIfCan(), npc_blastmaster_emi_shortfuseAI::JustSummoned(), NetherVaporLightning::OnPeriodicDummy(), and npc_shay_leafrunnerAI::UpdateFollowerAI().
GetFloatValueFromArray()
float GetFloatValueFromArray (Tokens const & data, uint16 index)
Definition at line 150 of file Util.cpp.
References GetUInt32ValueFromArray().
GetLocalHourTimestamp()
time_t GetLocalHourTimestamp (time_t time, uint8 hour, bool onlyAfterTime = true)
Definition at line 196 of file Util.cpp.
References DAY, HOUR, and TimeBreakdown().
GetMainPartOfName()
std::wstring GetMainPartOfName (const std::wstring & wname, uint32 declension)
Definition at line 445 of file Util.cpp.
References isCyrillicCharacter().
Referenced by ObjectMgr::CheckDeclinedNames(), WorldSession::HandlePetRename(), and WorldSession::HandleSetPlayerDeclinedNamesOpcode().
GetRandomGenerator()
std::mt19937* GetRandomGenerator ()
Definition at line 37 of file Util.cpp.
Referenced by boss_fankrissAI::Aggro(), npc_anubisath_sentinelAI::Aggro(), boss_kiljaedenAI::DoActivateDragonOrb(), boss_priestess_delrissaAI::DoInitializeCompanions(), instance_scholomance::DoRespawnEntranceRoom(), boss_moroesAI::DoSpawnGuests(), boss_ossirianAI::DoSpawnNextCrystal(), instance_stratholme::DoSpawnScourgeInvaders(), boss_netherspiteAI::DoSummonPortals(), Spell::EffectDummy(), priestess_commonAI::ExecuteAction(), boss_heiganAI::ExecuteAction(), boss_maexxnaAI::ExecuteAction(), boss_fankrissAI::ExecuteAction(), boss_skeramAI::ExecuteAction(), boss_high_astromancer_solarianAI::ExecuteAction(), PlayerAI::ExecuteSpells(), SpawnGroup::GetEligibleEntry(), WardenScanMgr::GetRandomScans(), boss_skeramAI::HandleInitImages(), boss_high_astromancer_solarianAI::HandleSplitPriests(), ThousandBladesRenataki::OnEffectExecute(), ChainsKelThuzad::OnEffectExecute(), LootTemplate::LootGroup::Roll(), PoolGroup< T >::RollOne(), SelectRandomFlameshockerSpawnTarget(), SpawnGroup::Spawn(), WorldState::StartScourgeInvasion(), instance_blackwing_lair::Update(), and UnitAI::UpdateSpellLists().
GetUInt32ValueFromArray()
uint32 GetUInt32ValueFromArray (Tokens const & data, uint16 index)
Definition at line 142 of file Util.cpp.
Referenced by Player::BuildEnumData(), GetFloatValueFromArray(), and Corpse::LoadFromDB().
hexEncodeByteArray()
void hexEncodeByteArray (uint8 * bytes, uint32 arrayLen, std::string & result)
Definition at line 567 of file Util.cpp.
Referenced by AccountMgr::CalculateShaPassHash().
irand() [1/2]
int32 irand ()
Definition at line 86 of file Util.cpp.
irand() [2/2]
int32 irand (int32 min, int32 max)
Definition at line 68 of file Util.cpp.
Referenced by boss_warbringer_omroggAI::Aggro(), WorldObject::CalculateSpellEffectValue(), Spell::CheckCast(), boss_warbringer_omroggAI::DoYellForThreat(), EffectDummyCreature_spell_dummy_npc(), Spell::EffectSchoolDMG(), ChaseMovementGenerator::FanOut(), GetItemEnchantMod(), ObjectMgr::GetRandomEntry(), Aura::HandleAuraModShapeshift(), Spell::HandleEffect(), boss_kiljaedenAI::JustDidDialogueStep(), boss_warbringer_omroggAI::KilledUnit(), roll_chance_i(), npc_doomfire_targetingAI::UpdateAI(), Player::UpdateSkillPro(), UnitAI::UpdateSpellLists(), and GameObject::Use().
isBasicLatinCharacter()
bool isBasicLatinCharacter (wchar_t wchar) inline
Definition at line 172 of file Util.h.
Referenced by isBasicLatinString(), isExtendedLatinCharacter(), NamreebAnticheat::AntispamMgr::NormalizeStringInternal(), and wcharToUpperOnlyLatin().
isBasicLatinString()
bool isBasicLatinString (const std::wstring & wstr, bool numericOrSpace) inline
Definition at line 279 of file Util.h.
References isBasicLatinCharacter(), and isNumericOrSpace().
Referenced by isValidString(), and NamreebAnticheat::AntispamMgr::NormalizeStringInternal().
isCyrillicCharacter()
bool isCyrillicCharacter (wchar_t wchar) inline
Definition at line 202 of file Util.h.
Referenced by ObjectMgr::CheckPublicMessageLanguage(), GetMainPartOfName(), WorldSession::HandleSetPlayerDeclinedNamesOpcode(), and isCyrillicString().
isCyrillicString()
bool isCyrillicString (const std::wstring & wstr, bool numericOrSpace) inline
Definition at line 295 of file Util.h.
References isCyrillicCharacter(), and isNumericOrSpace().
Referenced by isValidString().
isEastAsianCharacter()
bool isEastAsianCharacter (wchar_t wchar) inline
Definition at line 211 of file Util.h.
Referenced by ObjectMgr::CheckPublicMessageLanguage(), and isEastAsianString().
isEastAsianString()
bool isEastAsianString (const std::wstring & wstr, bool numericOrSpace) inline
Definition at line 303 of file Util.h.
References isEastAsianCharacter(), and isNumericOrSpace().
Referenced by isValidString().
isExtendedLatinCharacter()
bool isExtendedLatinCharacter (wchar_t wchar) inline
Definition at line 181 of file Util.h.
References isBasicLatinCharacter().
Referenced by ObjectMgr::CheckPublicMessageLanguage(), and isExtendedLatinString().
isExtendedLatinString()
bool isExtendedLatinString (const std::wstring & wstr, bool numericOrSpace) inline
Definition at line 287 of file Util.h.
References isExtendedLatinCharacter(), and isNumericOrSpace().
Referenced by isValidString().
IsIPAddress()
bool IsIPAddress (char const * ipaddress)
Check if the string is a valid ip address representation.
Definition at line 298 of file Util.cpp.
Referenced by ChatHandler::HandleBanHelper(), ChatHandler::HandleBanInfoIPCommand(), and ChatHandler::HandleUnBanHelper().
isNumeric() [1/5]
bool isNumeric (char c) inline
Definition at line 242 of file Util.h.
isNumeric() [2/5]
bool isNumeric (char const * str) inline
Definition at line 252 of file Util.h.
References isNumeric().
isNumeric() [3/5]
bool isNumeric (std::string const & str) inline
Definition at line 261 of file Util.h.
References isNumeric().
isNumeric() [4/5]
bool isNumeric (std::wstring const & str) inline
Definition at line 270 of file Util.h.
References isNumeric().
isNumeric() [5/5]
bool isNumeric (wchar_t wchar) inline
Definition at line 237 of file Util.h.
Referenced by ChatHandler::GetDeletedCharacterInfoList(), ChatHandler::HandleInstanceUnbindCommand(), isNumeric(), isNumericOrSpace(), and NamreebAnticheat::AntispamMgr::NormalizeStringInternal().
isNumericOrSpace()
bool isNumericOrSpace (wchar_t wchar) inline
Definition at line 247 of file Util.h.
References isNumeric().
Referenced by isBasicLatinString(), isCyrillicString(), isEastAsianString(), and isExtendedLatinString().
isWhiteSpace()
bool isWhiteSpace (char c) inline
Definition at line 232 of file Util.h.
Referenced by ChatHandler::ExtractFloat(), ChatHandler::ExtractInt32(), ChatHandler::ExtractLinkArg(), ChatHandler::ExtractLiteralArg(), ChatHandler::ExtractQuotedArg(), ChatHandler::ExtractUInt32Base(), and ChatHandler::SkipWhiteSpaces().
PickRandomValue()
template<typename T , typename... Args> T PickRandomValue (T first, Args ... rest)
Definition at line 134 of file Util.h.
References urand().
Referenced by ScourgeMinion::ExecuteAction(), PallidHorrorAI::ExecuteAction(), MouthAI::MouthAI(), MouthAI::ReceiveAIEvent(), ScourgeMinion::ReceiveAIEvent(), NecroticShard::SpellHit(), and WorldState::SummonPallid().
rand_chance()
double rand_chance (void)
Definition at line 110 of file Util.cpp.
Referenced by GetItemEnchantMod(), ScriptMgr::GetRandomScriptTemplateId(), roll_chance_f(), and PoolGroup< T >::RollOne().
rand_chance_f()
float rand_chance_f (void)
Definition at line 116 of file Util.cpp.
Referenced by LootTemplate::LootGroup::Roll().
rand_norm()
double rand_norm (void)
Definition at line 98 of file Util.cpp.
rand_norm_f()
float rand_norm_f (void)
Definition at line 104 of file Util.cpp.
Referenced by PathFinder::ComputePathToRandomPoint(), Spell::EffectTransmitted(), WorldObject::GetRandomPoint(), Map::GetRandomPointInTheAir(), Map::GetRandomPointUnderWater(), Map::GetReachableRandomPointOnGround(), FlignTorch::OnDestTarget(), Weather::ReGenerate(), Spell::SetTargetMap(), and npc_belnistraszAI::SpawnerSummon().
roll_chance_combat()
bool roll_chance_combat (float chance) inline
Definition at line 99 of file Util.h.
References chance_u(), and urand().
Referenced by Unit::RollAbilityPartialBlockOutcome(), Unit::RollSpellCritOutcome(), and Unit::SpellHitResult().
roll_chance_f()
bool roll_chance_f (float chance) inline
Definition at line 81 of file Util.h.
References rand_chance().
Referenced by Player::CastItemCombatSpell(), Unit::DealMeleeDamage(), Spell::DoCreateItem(), Spell::EffectDummy(), GetSkillDiscoverySpell(), Unit::HandleDamageDealt(), Unit::HandleDummyAuraProc(), Aura::HandleFeignDeath(), Unit::HandleProcTriggerSpellAuraProc(), Unit::HandleRemoveByDamageChanceProc(), Unit::IsTriggeredAtSpellProcEvent(), spell_judgement::OnEffectExecute(), spell_paladin_tier_6_trinket::OnProc(), Loot::Release(), LootStoreItem::Roll(), Player::UpdateCombatSkills(), and SpellAuraHolder::UpdateHeartbeatResist().
roll_chance_i()
bool roll_chance_i (int chance) inline
Definition at line 87 of file Util.h.
References irand().
Referenced by npc_wildaAI::Aggro(), npc_kineloryAI::Aggro(), npc_captured_arkonarinAI::Aggro(), npc_disciple_of_naralexAI::AttackedBy(), Spell::Delayed(), Spell::DelayedChannel(), npc_wildaAI::DoSpawnAssassin(), npc_eris_havenfireAI::DoSummonWave(), Spell::EffectDummy(), Spell::EffectResurrect(), Spell::EffectSchoolDMG(), Spell::EffectScriptEffect(), Spell::EffectTeleportUnits(), Player::GetResurrectionSpellId(), Aura::HandleAuraDummy(), Unit::HandleDummyAuraProc(), Unit::HandleOverrideClassScriptAuraProc(), WorldSession::HandlePetAction(), CheatDeathRogue::OnAbsorb(), spell_judgement::OnEffectExecute(), Aura::PeriodicDummyTick(), Spell::ProcessDispelList(), Spell::ProcSpellAuraTriggers(), Unit::SelectMagnetTarget(), SpawnGroup::Spawn(), instance_sunken_temple::Update(), npc_chess_piece_genericAI::UpdateAI(), boss_zumrahAI::UpdateAI(), and npc_keeper_remulosAI::UpdateEscortAI().
secsToTimeBitFields()
uint32 secsToTimeBitFields (time_t secs) inline
Definition at line 42 of file Util.h.
Referenced by AuctionHouseMgr::SendAuctionSalePendingMail(), and Player::SendInitialPacketsBeforeAddToMap().
secsToTimeString()
std::string secsToTimeString (time_t timeInSecs, bool shortText = false, bool hoursOnly = false)
Definition at line 211 of file Util.cpp.
References DAY, HOUR, and MINUTE.
Referenced by ChatHandler::HandleBanHelper(), ChatHandler::HandleBanInfoHelper(), ChatHandler::HandleBanInfoIPCommand(), ChatHandler::HandleBanListHelper(), ChatHandler::HandleEventInfoCommand(), ChatHandler::HandleGameObjectTargetCommand(), ChatHandler::HandleInstanceListBindsCommand(), ChatHandler::HandleInstanceUnbindCommand(), WorldSession::HandleMessagechatOpcode(), ChatHandler::HandleNpcInfoCommand(), ChatHandler::HandlePInfoCommand(), ChatHandler::HandleServerInfoCommand(), WorldSession::HandleTextEmoteOpcode(), GMTicketMgr::Print(), GMTicketMgr::ShowMOTD(), and World::ShutdownMsg().
stripLineInvisibleChars()
void stripLineInvisibleChars (std::string & str)
Definition at line 159 of file Util.cpp.
Referenced by WorldSession::CheckChatChannelNameAndPassword(), and WorldSession::CheckChatMessage().
StrSplit()
Tokens StrSplit (const std::string & src, const std::string & sep)
Definition at line 122 of file Util.cpp.
Referenced by MapPersistentStateManager::_DelHelper(), Object::_LoadIntoDataField(), Player::_LoadIntoDataField(), Player::BuildEnumData(), GMTicketMgr::Comment(), MySQLConnection::Initialize(), Taxi::Tracker::Load(), Item::LoadFromDB(), Corpse::LoadFromDB(), CharmInfo::LoadPetActionBar(), Pet::LoadPetFromDB(), PlayerTaxi::LoadTaxiMask(), GMTicketMgr::Print(), BattleGroundMgr::RewardArenaSeason(), and RealmList::UpdateRealm().
strToLower()
void strToLower (std::string & str) inline
Definition at line 316 of file Util.h.
Referenced by ChatHandler::HandleLookupPoolCommand(), and ChatHandler::HandleTicketsCommand().
strToUpper()
void strToUpper (std::string & str) inline
Definition at line 311 of file Util.h.
Referenced by GMTicketMgr::ShowMOTD().
timeBitFieldsToSecs()
time_t timeBitFieldsToSecs (uint32 packedDate)
Definition at line 282 of file Util.cpp.
TimeStringToSecs()
uint32 TimeStringToSecs (const std::string & timestring)
Definition at line 234 of file Util.cpp.
References DAY, HOUR, and MINUTE.
Referenced by ChatHandler::HandleBanHelper().
TimeToTimestampStr()
std::string TimeToTimestampStr (time_t t)
Definition at line 266 of file Util.cpp.
Referenced by GMTicketMgr::Comment(), ChatHandler::HandleCharacterDeletedListHelper(), ChatHandler::HandleEventInfoCommand(), and GMTicketMgr::Print().
urand() [1/2]
uint32 urand ()
Definition at line 92 of file Util.cpp.
urand() [2/2]
uint32 urand (uint32 min, uint32 max)
Definition at line 74 of file Util.cpp.
Referenced by mob_water_globuleAI::AcquireNewTarget(), PlayerbotAI::AddAuction(), UnitAI::AddInitialCooldowns(), AuctionHouseBot::AddLootToItemMap(), boss_swamplord_muselekAI::Aggro(), boss_plugger_spazzringAI::Aggro(), boss_emperor_dagran_thaurissanAI::Aggro(), boss_kazzakAI::Aggro(), boss_aranAI::Aggro(), boss_anubrekhanAI::Aggro(), boss_alexandros_mograineAI::Aggro(), boss_heiganAI::Aggro(), boss_nothAI::Aggro(), boss_patchwerkAI::Aggro(), boss_razuviousAI::Aggro(), boss_thaddiusAI::Aggro(), npc_muglashAI::Aggro(), npc_magwinAI::Aggro(), npc_thrall_old_hillsbradAI::Aggro(), npc_volcorAI::Aggro(), npc_oox22feAI::Aggro(), npc_clintar_dw_spiritAI::Aggro(), npc_oox17tnAI::Aggro(), npc_anubisath_defenderAI::Aggro(), boss_exarch_maladaarAI::Aggro(), boss_nexusprince_shaffarAI::Aggro(), boss_pandemoniusAI::Aggro(), boss_darkweaver_sythAI::Aggro(), boss_talon_king_ikissAI::Aggro(), boss_ambassador_hellmawAI::Aggro(), boss_blackheart_the_inciterAI::Aggro(), boss_grandmaster_vorpilAI::Aggro(), boss_doomlordkazzakAI::Aggro(), boss_lady_vashjAI::Aggro(), boss_thespiaAI::Aggro(), boss_mekgineer_steamriggerAI::Aggro(), boss_warlord_kalithreshAI::Aggro(), boss_the_makerAI::Aggro(), boss_vazrudenAI::Aggro(), boss_omor_the_unscarredAI::Aggro(), boss_watchkeeper_gargolmarAI::Aggro(), mob_fel_orc_convertAI::Aggro(), boss_warchief_kargath_bladefistAI::Aggro(), npc_shattered_hand_legionnaire::Aggro(), npc_protectorate_demolitionistAI::Aggro(), boss_highlord_kruulAI::Aggro(), npc_marshal_windsorAI::Aggro(), npc_00x09hlAI::Aggro(), npc_rinjiAI::Aggro(), npc_prospector_remtravelAI::Aggro(), npc_stinky_ignatzAI::Aggro(), npc_captured_arkonarinAI::Aggro(), npc_willix_the_importerAI::Aggro(), npc_giltharesAI::Aggro(), npc_ame01AI::Aggro(), mob_lumpAI::Aggro(), npc_kindal_moonweaverAI::Aggro(), guardAI::Aggro(), npc_dorius_stonetenderAI::Aggro(), npc_deathstalker_erlandAI::Aggro(), npc_galen_goodwardAI::Aggro(), npc_defias_traitorAI::Aggro(), boss_veknilashAI::Aggro(), boss_veklorAI::Aggro(), mob_shadowmoon_channelerAI::Aggro(), mob_bt_battle_fighterAI::Aggro(), BossAI::Aggro(), AreaTrigger_at_beggar(), npc_blastmaster_emi_shortfuseAI::AttackedBy(), npc_belnistraszAI::AttackedBy(), npc_dragonmaw_racer_mulverickAI::AttackPlayer(), npc_dragonmaw_racer_skyshatterAI::AttackPlayer(), boss_plugger_spazzringAI::AttackThief(), npc_lazy_peonAI::Awaken(), boss_highlord_kruulAI::boss_highlord_kruulAI(), boss_mekgineer_steamriggerAI::boss_mekgineer_steamriggerAI(), boss_twin_emperorsAI::boss_twin_emperorsAI(), boss_veklorAI::boss_veklorAI(), boss_veknilashAI::boss_veknilashAI(), boss_vemAI::boss_vemAI(), boss_yaujAI::boss_yaujAI(), Unit::CalculateGlanceAmount(), npc_shattered_hand_legionnaire::CallForReinforcements(), Pet::CheckLearning(), Creature::ChooseDisplayId(), GossipNPCAI::ChooseEvent(), npc_bt_battle_sensor::ChooseIllidariAttack(), npc_bt_battle_sensor::ChooseIllidariNotRavagers3or4(), npc_bt_battle_sensor::ChooseIllidariRavagers3or4(), UnitAI::ChooseTarget(), FormationMap::claimFormationMarker(), npc_ringoAI::ClearFaint(), boss_majordomoAI::CorpseRemoved(), BattleGroundMgr::CreateNewBattleGround(), npc_apexis_flayerAI::CrystalStrike(), npc_ranshallaAI::DoChannelTorchSpell(), npc_ranshallaAI::DoContinueEscort(), boss_lady_vashjAI::DoInformGeneratorStopped(), boss_malacrassAI::DoInitializeAdds(), boss_alarAI::DoPlatformMove(), instance_scholomance::DoRespawnEntranceRoom(), boss_gathios_the_shattererAI::DoSelectCouncilMember(), boss_selin_fireheartAI::DoSelectNearestCrystal(), instance_blackrock_spire::DoSendNextFlamewreathWave(), npc_simon_game_bunnyAI::DoSetupLevel(), world_map_eastern_kingdoms::DoSpawn(), npc_wildaAI::DoSpawnAssassin(), instance_dark_portal::DoSpawnNextPortal(), instance_stratholme::DoSpawnPlaguedCritters(), npc_forest_frogAI::DoSpawnRandom(), instance_stratholme::DoSpawnScourgeInvaders(), mob_illidari_councilAI::DoStartEvent(), npc_time_riftAI::DoSummon(), boss_anzuAI::DoSummonBroodsOfAnzu(), boss_nothAI::DoSummonPlaguedChampions(), boss_nothAI::DoSummonPlaguedGuardians(), boss_lajAI::DoSummons(), boss_high_astromancer_solarianAI::DoSummonSpotlights(), npc_eris_havenfireAI::DoSummonWave(), hyjalAI::DoTalk(), boss_grand_warlock_nethekurseAI::DoTauntPeons(), instance_zulaman::DoTimeRunSay(), boss_lajAI::DoTransform(), npc_manaforge_control_consoleAI::DoWaveSpawnForCreature(), boss_grand_warlock_nethekurseAI::DoYellForPeonAggro(), boss_grand_warlock_nethekurseAI::DoYellForPeonDeath(), Spell::EffectActivateObject(), Spell::EffectDummy(), EffectDummyCreature_spell_anchor(), EffectDummyCreature_spell_boss_thermaplugg(), EffectDummyGameObj_spell_dummy_go(), Spell::EffectEnergize(), Spell::EffectPickPocket(), Spell::EffectSchoolDMG(), Spell::EffectScriptEffect(), Spell::EffectSummonType(), Spell::EffectTeleportUnits(), Spell::EffectTransmitted(), Spell::EffectTriggerSpell(), npc_thrall_old_hillsbradAI::EnterEvadeMode(), hyjalAI::EventStarted(), npc_sunblade_scoutAI::ExecuteAction(), npc_sunblade_protectorAI::ExecuteAction(), mob_ohganAI::ExecuteAction(), boss_ahuneAI::ExecuteAction(), boss_alarAI::ExecuteAction(), boss_broodlordAI::ExecuteAction(), boss_ebonrocAI::ExecuteAction(), boss_firemawAI::ExecuteAction(), boss_flamegorAI::ExecuteAction(), boss_nefarianAI::ExecuteAction(), boss_razorgoreAI::ExecuteAction(), boss_vaelastraszAI::ExecuteAction(), boss_victor_nefariusAI::ExecuteAction(), npc_dawnblade_blood_knight::ExecuteAction(), boss_curatorAI::ExecuteAction(), boss_maiden_of_virtueAI::ExecuteAction(), boss_attumenAI::ExecuteAction(), boss_nightbaneAI::ExecuteAction(), boss_malchezaarAI::ExecuteAction(), boss_aranAI::ExecuteAction(), boss_terestianAI::ExecuteAction(), boss_bigbadwolfAI::ExecuteAction(), boss_felblood_kaelthasAI::ExecuteAction(), priestess_commonAI::ExecuteAction(), boss_priestess_delrissaAI::ExecuteAction(), npc_kagani_nightstrikeAI::ExecuteAction(), npc_ellrys_duskhallowAI::ExecuteAction(), npc_eramas_brightblazeAI::ExecuteAction(), npc_yazzaiAI::ExecuteAction(), npc_warlord_salarisAI::ExecuteAction(), npc_garaxxasAI::ExecuteAction(), npc_apokoAI::ExecuteAction(), npc_zelfanAI::ExecuteAction(), boss_garrAI::ExecuteAction(), boss_gehennasAI::ExecuteAction(), boss_lucifronAI::ExecuteAction(), boss_magmadarAI::ExecuteAction(), boss_majordomoAI::ExecuteAction(), boss_ragnarosAI::ExecuteAction(), boss_shazzrahAI::ExecuteAction(), boss_sulfuronAI::ExecuteAction(), mob_flamewaker_priestAI::ExecuteAction(), boss_faerlinaAI::ExecuteAction(), boss_heiganAI::ExecuteAction(), boss_maexxnaAI::ExecuteAction(), boss_nothAI::ExecuteAction(), boss_high_inquisitor_whitemaneAI::ExecuteAction(), mob_arugal_voidwalkerAI::ExecuteAction(), boss_arugalAI::ExecuteAction(), boss_brutallusAI::ExecuteAction(), boss_alythessAI::ExecuteAction(), boss_sacrolashAI::ExecuteAction(), boss_felmystAI::ExecuteAction(), boss_kalecgosAI::ExecuteAction(), boss_sathrovarrAI::ExecuteAction(), boss_kiljaedenAI::ExecuteAction(), npc_sinister_reflectionAI::ExecuteAction(), boss_entropiusAI::ExecuteAction(), boss_akilzonAI::ExecuteAction(), boss_halazziAI::ExecuteAction(), boss_spirit_lynxAI::ExecuteAction(), boss_nalorakkAI::ExecuteAction(), boss_zuljinAI::ExecuteAction(), boss_azuregosAI::ExecuteAction(), boss_anetheronAI::ExecuteAction(), boss_archimondeAI::ExecuteAction(), boss_kazrogalAI::ExecuteAction(), boss_rage_winterchillAI::ExecuteAction(), hyjalAI::ExecuteAction(), npc_jaina_proudmooreAI::ExecuteAction(), npc_thrallAI::ExecuteAction(), npc_tyrande_whisperwindAI::ExecuteAction(), boss_onyxiaAI::ExecuteAction(), boss_ayamissAI::ExecuteAction(), boss_kurinnaxxAI::ExecuteAction(), boss_ossirianAI::ExecuteAction(), npc_general_andorovAI::ExecuteAction(), npc_kaldorei_eliteAI::ExecuteAction(), boss_kriAI::ExecuteAction(), boss_vemAI::ExecuteAction(), boss_yaujAI::ExecuteAction(), boss_eye_of_cthunAI::ExecuteAction(), boss_fankrissAI::ExecuteAction(), boss_huhuranAI::ExecuteAction(), boss_sarturaAI::ExecuteAction(), boss_skeramAI::ExecuteAction(), boss_twin_emperorsAI::ExecuteAction(), boss_veknilashAI::ExecuteAction(), boss_veklorAI::ExecuteAction(), boss_viscidusAI::ExecuteAction(), npc_anubisath_defenderAI::ExecuteAction(), boss_nexusprince_shaffarAI::ExecuteAction(), npc_bonechewer_brawler::ExecuteAction(), boss_gurtogg_bloodboilAI::ExecuteAction(), boss_illidan_stormrageAI::ExecuteAction(), npc_akama_illidanAI::ExecuteAction(), boss_maievAI::ExecuteAction(), boss_shahrazAI::ExecuteAction(), boss_teron_gorefiendAI::ExecuteAction(), boss_najentusAI::ExecuteAction(), boss_gathios_the_shattererAI::ExecuteAction(), boss_high_nethermancer_zerevorAI::ExecuteAction(), boss_lady_malandeAI::ExecuteAction(), boss_fathomguard_sharkkisAI::ExecuteAction(), boss_fathomguard_tidalvessAI::ExecuteAction(), boss_lady_vashjAI::ExecuteAction(), boss_leotheras_the_blindAI::ExecuteAction(), boss_morogrim_tidewalkerAI::ExecuteAction(), boss_the_lurker_belowAI::ExecuteAction(), boss_hungarfenAI::ExecuteAction(), boss_swamplord_muselekAI::ExecuteAction(), boss_gruulAI::ExecuteAction(), boss_high_king_maulgarAI::ExecuteAction(), boss_olm_the_summonerAI::ExecuteAction(), boss_kiggler_the_crazedAI::ExecuteAction(), boss_blindeye_the_seerAI::ExecuteAction(), boss_broggokAI::ExecuteAction(), boss_kelidan_the_breakerAI::ExecuteAction(), mob_shadowmoon_channelerAI::ExecuteAction(), boss_the_makerAI::ExecuteAction(), boss_vazruden_heraldAI::ExecuteAction(), boss_vazrudenAI::ExecuteAction(), boss_omor_the_unscarredAI::ExecuteAction(), boss_magtheridonAI::ExecuteAction(), mob_hellfire_channelerAI::ExecuteAction(), npc_shattered_hand_legionnaire::ExecuteAction(), npc_razorthorn_ravager::ExecuteAction(), boss_dalliahAI::ExecuteAction(), boss_high_astromancer_solarianAI::ExecuteAction(), boss_void_reaverAI::ExecuteAction(), npc_burster_wormAI::ExecuteAction(), ScourgeMinion::ExecuteAction(), PallidHorrorAI::ExecuteAction(), boss_kazzakAI::ExecuteActions(), boss_kaelthasAI::ExecuteActions(), ScriptAction::ExecuteDbscriptCommand(), PlayerAI::ExecuteSpells(), Spell::FillTargetMap(), Spell::FilterTargetMap(), World::GenerateEventGroupEvents(), Loot::GenerateMoneyLoot(), ObjectMgr::GeneratePetName(), GossipNPCAppearanceAllSpiritOfCompetition::GetAuraScriptCustomizationValue(), GossipNPCAppearanceAllPirateDay::GetAuraScriptCustomizationValue(), NamreebAnticheat::AnticheatConfig::GetBanDelay(), ObjectMgr::GetCreatureCooldown(), ObjectMgr::GetCreatureModelRandomGender(), SpawnGroup::GetEligibleEntry(), boss_kazzakAI::GetInitialActionTimer(), boss_azgalorAI::GetInitialActionTimer(), boss_kazrogalAI::GetInitialActionTimer(), boss_rage_winterchillAI::GetInitialActionTimer(), mob_bt_battle_fighterAI::GetInitialActionTimer(), boss_highlord_kruulAI::GetInitialActionTimer(), boss_essence_of_desireAI::GetInitialActionTimer(), boss_dorotheeAI::GetInitialActionTimer(), boss_teron_gorefiendAI::GetInitialActionTimer(), boss_gurtogg_bloodboilAI::GetInitialActionTimer(), boss_illidan_stormrageAI::GetInitialActionTimer(), boss_shahrazAI::GetInitialActionTimer(), boss_supremusAI::GetInitialActionTimer(), boss_terokkAI::GetInitialActionTimer(), npc_skyguard_rangerAI::GetInitialActionTimer(), npc_apexis_flayerAI::GetInitialActionTimer(), NamreebAnticheat::AnticheatConfig::GetIPBanDelay(), NamreebAnticheat::AnticheatConfig::GetKickDelay(), WardenModuleMgr::GetMacModule(), Unit::GetNextRandomRaidMember(), FormationMap::getRandomOccupant(), CreatureData::GetRandomRespawnTime(), GameObjectData::GetRandomRespawnTime(), ScriptMgr::GetRandomScriptTemplateId(), boss_sacrolashAI::GetRandomTargetAtDist(), GetRandomText(), GetRandomWavePath(), Creature::GetSpellCooldown(), npc_magister_aledisAI::GetSubsequentActionTimer(), boss_kazzakAI::GetSubsequentActionTimer(), boss_moroesAI::GetSubsequentActionTimer(), boss_anetheronAI::GetSubsequentActionTimer(), boss_archimondeAI::GetSubsequentActionTimer(), boss_azgalorAI::GetSubsequentActionTimer(), boss_kazrogalAI::GetSubsequentActionTimer(), boss_rage_winterchillAI::GetSubsequentActionTimer(), boss_talon_king_ikissAI::GetSubsequentActionTimer(), boss_warlord_kalithreshAI::GetSubsequentActionTimer(), boss_black_stalkerAI::GetSubsequentActionTimer(), boss_swamplord_muselekAI::GetSubsequentActionTimer(), mob_bt_battle_fighterAI::GetSubsequentActionTimer(), boss_highlord_kruulAI::GetSubsequentActionTimer(), boss_dorotheeAI::GetSubsequentActionTimer(), boss_watchkeeper_gargolmarAI::GetSubsequentActionTimer(), boss_teron_gorefiendAI::GetSubsequentActionTimer(), boss_gurtogg_bloodboilAI::GetSubsequentActionTimer(), boss_maievAI::GetSubsequentActionTimer(), npc_nether_rayAI::GetSubsequentActionTimer(), boss_nexusprince_shaffarAI::GetSubsequentActionTimer(), boss_shahrazAI::GetSubsequentActionTimer(), boss_supremusAI::GetSubsequentActionTimer(), boss_terokkAI::GetSubsequentActionTimer(), boss_sapphironAI::GetSubsequentActionTimer(), npc_corrupted_furbolgAI::GetSubsequentActionTimer(), boss_maiden_of_virtueAI::GetSubsequentActionTimer(), boss_midnightAI::GetSubsequentActionTimer(), boss_attumenAI::GetSubsequentActionTimer(), boss_terestianAI::GetSubsequentActionTimer(), boss_selin_fireheartAI::GetSubsequentActionTimer(), boss_gluthAI::GetSubsequentActionTimer(), boss_grobbulusAI::GetSubsequentActionTimer(), boss_heiganAI::GetSubsequentActionTimer(), boss_scarlet_commander_mograineAI::GetSubsequentActionTimer(), boss_high_inquisitor_whitemaneAI::GetSubsequentActionTimer(), npc_skyguard_rangerAI::GetSubsequentActionTimer(), npc_apexis_flayerAI::GetSubsequentActionTimer(), npc_chess_piece_genericAI::GetTargetByType(), WardenModuleMgr::GetWindowsModule(), world_map_kalimdor::GhostOPlasmEventStep(), GossipSelect_npc_tobias_seecher(), GOUse_go_ossirian_crystal(), GOUse_go_strange_pool(), WorldState::HandleActiveZone(), npc_disobedient_dragonmaw_peonAI::HandleAngry(), boss_kiljaedenAI::HandleAttackDelay(), Aura::HandleAuraDummy(), instance_blackrock_depths::HandleBarPatrons(), world_map_outland::HandleBashirEnemyAttack(), boss_warchief_kargath_bladefistAI::HandleBladeDance(), npc_disobedient_dragonmaw_peonAI::HandleBooterang(), boss_lady_vashjAI::HandleCoilfangElite(), boss_lady_vashjAI::HandleCoilfangStrider(), Unit::HandleDamageDealt(), boss_felmystAI::HandleDemonicVapor(), Unit::HandleDummyAuraProc(), boss_ahuneAI::HandleEmerge(), boss_lady_vashjAI::HandleEnchantedElemental(), boss_eye_of_cthunAI::HandleEndDarkGlare(), WorldState::HandleExternalEvent(), boss_soccothratesAI::HandleFelfireLineup(), boss_skeramAI::HandleInitImages(), boss_brutallusAI::HandleMadrigosaFrostbolt(), Aura::HandleModPossess(), boss_murmurAI::HandleOocAttack(), boss_murmurAI::HandleOocCasterAttack(), boss_archimondeAI::HandleOutro(), WorldSession::HandlePetAction(), WorldSession::HandlePetCastSpellOpcode(), boss_vazruden_heraldAI::HandlePhaseChange(), boss_nightbaneAI::HandlePhaseTransition(), boss_ragnarosAI::HandlePhaseTransition(), boss_onyxiaAI::HandlePhaseTransition(), boss_illidan_stormrageAI::HandlePhaseTransition(), boss_leotheras_the_blindAI::HandlePhaseTransition(), boss_alarAI::HandlePhaseTransition(), boss_felmystAI::HandlePreBreath(), WorldSession::HandleRandomRollOpcode(), NecroticShard::HandleShardMinionSpawnerSmall(), world_map_outland::HandleShartuulAddSpawns(), boss_high_astromancer_solarianAI::HandleSplitPhaseDelay(), boss_high_astromancer_solarianAI::HandleSplitPriests(), boss_lady_vashjAI::HandleSporebat(), boss_lady_vashjAI::HandleTaintedElemental(), boss_felmystAI::HandleTransitionDelay(), npc_voidwalker_summoner::HandleTravellerSummon(), hyjalAI::hyjalAI(), instance_arcatraz::JustDidDialogueStep(), boss_kiljaedenAI::JustDidDialogueStep(), npc_anchorite_baradaAI::JustDidDialogueStep(), npc_thrall_old_hillsbradAI::JustDied(), PallidHorrorAI::JustDied(), BossAI::JustDied(), npc_human_footmanAI::JustDied(), npc_orc_gruntAI::JustDied(), mob_webbed_creatureAI::JustDied(), mob_netherweb_victimAI::JustDied(), npc_shattered_sun_fighterAI::JustRespawned(), npc_soulflayerAI::JustRespawned(), npc_magrami_spectre::JustRespawned(), npc_skyguard_prisonerAI::JustRespawned(), boss_highlord_kruulAI::JustRespawned(), npc_thrall_old_hillsbradAI::JustSummoned(), npc_credit_marker_they_must_burnAI::JustSummoned(), npc_skyguard_prisonerAI::JustSummoned(), boss_curatorAI::JustSummoned(), boss_midnightAI::JustSummoned(), boss_ayamissAI::JustSummoned(), boss_terokkAI::JustSummoned(), CombatAI::KilledUnit(), boss_aranAI::KilledUnit(), boss_faerlinaAI::KilledUnit(), boss_alexandros_mograineAI::KilledUnit(), boss_patchwerkAI::KilledUnit(), npc_thrall_old_hillsbradAI::KilledUnit(), boss_fathomlord_karathressAI::KilledUnit(), boss_hydross_the_unstableAI::KilledUnit(), boss_lady_vashjAI::KilledUnit(), boss_morogrim_tidewalkerAI::KilledUnit(), boss_kelidan_the_breakerAI::KilledUnit(), boss_the_makerAI::KilledUnit(), boss_vazrudenAI::KilledUnit(), boss_omor_the_unscarredAI::KilledUnit(), boss_watchkeeper_gargolmarAI::KilledUnit(), npc_wounded_blood_elfAI::KilledUnit(), boss_warp_splinterAI::KilledUnit(), boss_kaelthasAI::KilledUnit(), boss_nethermancer_sepethreaAI::KilledUnit(), boss_pathaleon_the_calculatorAI::KilledUnit(), boss_vaelastraszAI::KilledUnit(), boss_kazzakAI::KilledUnit(), boss_doomlordkazzakAI::KilledUnit(), boss_doomwalkerAI::KilledUnit(), boss_mechano_lord_capacitusAI::KilledUnit(), boss_nefarianAI::KilledUnit(), boss_kelthuzadAI::KilledUnit(), boss_leotheras_the_blindAI::KilledUnit(), boss_high_astromancer_solarianAI::KilledUnit(), boss_void_reaverAI::KilledUnit(), Creature::LoadFromDB(), WardenWin::LoadScriptedScans(), Loot::Loot(), LootItem::LootItem(), Unit::MagicSpellHitResult(), Unit::MeleeSpellHitResult(), mob_scarlet_traineeAI::mob_scarlet_traineeAI(), Pet::ModifyLoyalty(), ChatHandler::ModifyMountCommandHelper(), MouthAI::MouthAI(), npc_draenei_survivorAI::MoveInLineOfSight(), npc_aged_dying_ancient_kodoAI::MoveInLineOfSight(), npc_shay_leafrunnerAI::MoveInLineOfSight(), npc_supplicantAI::MoveInLineOfSight(), npc_creditmarker_visit_with_ancestorsAI::MoveInLineOfSight(), npc_harkorAI::MoveInLineOfSight(), npc_ashliAI::MoveInLineOfSight(), boss_ossirianAI::MoveInLineOfSight(), NetherCharge::MovementInform(), npc_akama_illidanAI::MovementInform(), mob_soaring_eagleAI::MovementInform(), npc_lazy_peonAI::MovementInform(), npc_rookery_hatcherAI::MovementInform(), npc_dragonmaw_peonAI::MovementInform(), NetherCharge::MoveToRandomPoint(), npc_akama_illidanAI::npc_akama_illidanAI(), npc_disruptor_towerAI::npc_disruptor_towerAI(), npc_grimstoneAI::npc_grimstoneAI(), npc_nether_vaporAI::npc_nether_vaporAI(), DarknessOfSouls::OnApply(), BrewfestBarkerBunny::OnApply(), CurseOfDoom::OnApply(), GDRPeriodicDamage::OnAuraValueCalculate(), FaceRandomTarget::OnCast(), Beatdown::OnCast(), RibbonPoleDancerCheck::OnCast(), instance_blackrock_depths::OnCreatureDeath(), instance_blackrock_spire::OnCreatureDeath(), instance_karazhan::OnCreatureDeath(), PolarityShift::OnEffectExecute(), RotateTrigger::OnEffectExecute(), AQWhirlwind::OnEffectExecute(), ThrowTorch::OnEffectExecute(), WondervoltTrap::OnEffectExecute(), RighteousDefense::OnEffectExecute(), DestroyEgg::OnEffectExecute(), ChainsKelThuzad::OnEffectExecute(), LeoWhirlwindProc::OnEffectExecute(), Spout::OnEffectExecute(), BearCommand::OnEffectExecute(), QuakeMagth::OnEffectExecute(), CursedScarabPeriodicTrigger::OnEffectExecute(), TestRibbonPoleChannelTrigger::OnEffectExecute(), RevelerApplauseCheer::OnEffectExecute(), ImpInABottleSay::OnEffectExecute(), HorsemanConflagrateTargetTest::OnEffectExecute(), DawnbladeAttack::OnEffectExecute(), FlameSear::OnInit(), go_ai_suppression::OnLootStateChange(), Player::OnMirrorTimerExpirationPulse(), ForsakenSkill::OnPeriodicDummy(), TransformVisualPeriodic::OnPeriodicDummy(), AllergiesAura::OnPeriodicDummy(), Armageddon::OnPeriodicTrigger(), EarthquakeGuardian::OnPeriodicTrigger(), instance_karazhan::OnPlayerEnter(), boss_exarch_maladaarAI::OnSpellCast(), boss_anzuAI::OnSpellCast(), boss_thespiaAI::OnSpellCast(), boss_dalliahAI::OnSpellCast(), boss_harbinger_skyrissAI::OnSpellCast(), boss_high_botanist_freywinnAI::OnSpellCast(), boss_felmystAI::OnSpellCooldownAdded(), boss_azgalorAI::OnSpellCooldownAdded(), npc_venture_co_lookoutAI::OnStealthAlert(), Aura::PeriodicDummyTick(), npc_ouro_moundAI::PickNewTarget(), PickRandomValue(), Pet::PlayDismissSound(), Player::Player(), GroupLootRoll::PlayerVote(), Spell::ProcessDispelList(), CreatureEventAI::ProcessEvent(), boss_illidan_stormrageAI::ReceiveAIEvent(), boss_maievAI::ReceiveAIEvent(), boss_moroesAI::ReceiveAIEvent(), boss_kiljaedenAI::ReceiveAIEvent(), boss_murmurAI::ReceiveAIEvent(), boss_magtheridonAI::ReceiveAIEvent(), npc_sinister_reflectionAI::ReceiveAIEvent(), npc_bonechewer_brawler::ReceiveAIEvent(), boss_alarAI::ReceiveAIEvent(), npc_supplicantAI::ReceiveAIEvent(), npc_shattered_sun_marksmanAI::ReceiveAIEvent(), npc_bt_battle_sensor::ReceiveAIEvent(), npc_headless_horseman_fireAI::ReceiveAIEvent(), npc_mojoAI::ReceiveEmote(), npc_chicken_cluckAI::ReceiveEmote(), Weather::ReGenerate(), npc_bt_battle_sensor::ReinforceAldorScryerFrontline(), Loot::Release(), Warden::RequestChallenge(), guardAI::Reset(), npc_kineloryAI::Reset(), npc_ironhand_guardianAI::Reset(), boss_ambassador_flamelashAI::Reset(), boss_general_angerforgeAI::Reset(), npc_rookery_hatcherAI::Reset(), boss_thermapluggAI::Reset(), boss_aranAI::Reset(), mob_arcane_sphereAI::Reset(), boss_anubrekhanAI::Reset(), boss_gothikAI::Reset(), boss_kelthuzadAI::Reset(), boss_thaddiusAddsAI::Reset(), boss_stalaggAI::Reset(), boss_feugenAI::Reset(), boss_arcanist_doanAI::Reset(), boss_headless_horsemanAI::Reset(), boss_jandicebarovAI::Reset(), npc_spectral_tutorAI::Reset(), npc_reginald_windsorAI::Reset(), npc_shadow_imageAI::Reset(), boss_archaedasAI::Reset(), npc_taelan_fordringAI::Reset(), npc_isillienAI::Reset(), npc_tirion_fordringAI::Reset(), mob_soaring_eagleAI::Reset(), npc_soulflayerAI::Reset(), boss_mawsAI::Reset(), npc_doomfire_targetingAI::Reset(), npc_thrall_old_hillsbradAI::Reset(), npc_kerlonianAI::Reset(), npc_rabid_bearAI::Reset(), boss_tethyrAI::Reset(), npc_captured_arkonarinAI::Reset(), npc_areiAI::Reset(), npc_captured_sprite_darterAI::Reset(), npc_kindal_moonweaverAI::Reset(), mob_anubisath_guardianAI::Reset(), npc_solenorAI::Reset(), boss_fankrissAI::Reset(), npc_ringoAI::Reset(), npc_simone_seductressAI::Reset(), npc_simone_the_inconspicuousAI::Reset(), npc_artoriusAI::Reset(), boss_zumrahAI::Reset(), boss_shahrazAI::Reset(), npc_bloodmaul_dire_wolfAI::Reset(), npc_apexis_flayerAI::Reset(), boss_doomlordkazzakAI::Reset(), boss_doomwalkerAI::Reset(), boss_fathomlord_karathressAI::Reset(), boss_fathomguard_caribdisAI::Reset(), npc_inner_demonAI::Reset(), npc_rethhedronAI::Reset(), npc_captured_vanguardAI::Reset(), npc_saeed_escortAI::Reset(), npc_dimensiusAI::Reset(), npc_shadowlord_deathwailAI::Reset(), npc_disobedient_dragonmaw_peonAI::Reset(), npc_millhouse_manastormAI::Reset(), npc_arcatraz_defenderAI::Reset(), boss_lajAI::Reset(), boss_thorngrinAI::Reset(), boss_warp_splinterAI::Reset(), boss_alarAI::Reset(), boss_thaladred_the_darkenerAI::Reset(), boss_mechano_lord_capacitusAI::Reset(), boss_nethermancer_sepethreaAI::Reset(), npc_raging_flamesAI::Reset(), boss_pathaleon_the_calculatorAI::Reset(), mob_nether_wraithAI::Reset(), npc_isla_starmaneAI::Reset(), npc_fhwoorAI::Reset(), boss_emerald_dragonAI::Reset(), npc_shade_of_the_horsemanAI::Reset(), Timer::ResetTimer(), WorldState::RespawnEmeraldDragons(), WorldState::RespawnHighlordKruul(), npc_lazy_peonAI::RestartWakeTimer(), Player::RewardHonor(), LootTemplate::LootGroup::Roll(), roll_chance_combat(), Unit::RollMagicResistanceMultiplierOutcomeAgainst(), Unit::RollMeleeOutcomeAgainst(), npc_corrupted_furbolgAI::SeekPurification(), Unit::SelectAttackingTarget(), Creature::SelectLevel(), Unit::SelectRandomFriendlyTarget(), instance_zulgurub::SelectRandomPantherTrigger(), Unit::SelectRandomUnfriendlyTarget(), ScriptedAI::SelectSpell(), world_map_kalimdor::SetData(), instance_sunken_temple::SetData(), npc_ringoAI::SetFaint(), npc_kerlonianAI::SetSleeping(), Creature::SetSpellList(), npc_regthar_deathgateAI::SpawnAllSlot(), npc_soulgrinderAI::SpawnCreature(), npc_regthar_deathgateAI::SpawnCreature(), instance_mount_hyjal::SpawnInfernals(), instance_mount_hyjal::SpawnOres(), world_map_outland::SpawnRandomBashirMob(), boss_kelthuzadAI::SpellHit(), boss_razuviousAI::SpellHit(), guardAI_stormwind::SpellHit(), boss_najentusAI::SpellHit(), npc_forest_frogAI::SpellHit(), mobs_nether_drakeAI::SpellHit(), npc_injured_patientAI::SpellHit(), npc_nagrand_captiveAI::SpellHitTarget(), boss_swamplord_muselekAI::SpellHitTarget(), boss_malacrassAI::SpellHitTarget(), npc_dragonmaw_racerAI::StartAttack(), npc_ethereum_prisonerAI::StartEvent(), WorldState::StartNewCityAttack(), WorldState::StartNewCityAttackIfTime(), npc_brewfest_barker::StartScript(), mob_blood_elf_council_voice_triggerAI::StartVoiceEvent(), boss_malacrassAI::SummonedCreatureJustDied(), npc_regthar_deathgateAI::SummonedCreatureJustDied(), npc_daphne_stilwellAI::SummonedCreatureJustDied(), npc_manaforge_control_consoleAI::SummonedMovementInform(), boss_lady_vashjAI::SummonedMovementInform(), boss_warp_splinterAI::SummonTreants(), npc_lord_illidan_stormrageAI::SummonWave(), boss_onyxiaAI::SummonWhelps(), boss_gurtogg_bloodboilAI::SwitchPhase(), TerrainInfo::TerrainInfo(), Aura::TriggerSpell(), UncommonMinionspawner(), AuctionHouseBot::Update(), FormationData::Update(), instance_blackwing_lair::Update(), instance_karazhan::Update(), instance_naxxramas::Update(), instance_stratholme::Update(), instance_sunken_temple::Update(), instance_sunwell_plateau::Update(), instance_dark_portal::Update(), instance_zulfarrak::Update(), instance_blood_furnace::Update(), instance_magtheridons_lair::Update(), instance_shattered_halls::Update(), instance_arcatraz::Update(), instance_temple_of_ahnqiraj::Update(), AbstractRandomMovementGenerator::Update(), boss_stalaggAI::UpdateAddAI(), boss_feugenAI::UpdateAddAI(), PetAI::UpdateAI(), npc_ironhand_guardianAI::UpdateAI(), npc_shattered_sun_marksmanAI::UpdateAI(), mob_arcane_sphereAI::UpdateAI(), boss_anubrekhanAI::UpdateAI(), boss_gothikAI::UpdateAI(), boss_kelthuzadAI::UpdateAI(), boss_thaddiusAddsAI::UpdateAI(), npc_forest_frogAI::UpdateAI(), npc_amanishi_tempestAI::UpdateAI(), npc_harkorAI::UpdateAI(), npc_tanzarAI::UpdateAI(), npc_krazAI::UpdateAI(), npc_ashliAI::UpdateAI(), npc_amanishi_scoutAI::UpdateAI(), npc_bonechewer_combatant::UpdateAI(), npc_disobedient_dragonmaw_peonAI::UpdateAI(), boss_thorngrinAI::UpdateAI(), boss_mechano_lord_capacitusAI::UpdateAI(), go_brewfest_music::UpdateAI(), generic_creatureAI::UpdateAI(), npc_snakesAI::UpdateAI(), npc_orphanAI::UpdateAI(), npc_shade_of_the_horsemanAI::UpdateAI(), npc_headless_horseman_fireAI::UpdateAI(), boss_plugger_spazzringAI::UpdateAI(), boss_ambassador_flamelashAI::UpdateAI(), boss_emperor_dagran_thaurissanAI::UpdateAI(), boss_general_angerforgeAI::UpdateAI(), boss_overlordwyrmthalakAI::UpdateAI(), npc_rookery_hatcherAI::UpdateAI(), npc_eris_havenfireAI::UpdateAI(), npc_apprentice_mirvedaAI::UpdateAI(), boss_thermapluggAI::UpdateAI(), npc_converted_sentryAI::UpdateAI(), boss_roarAI::UpdateAI(), boss_croneAI::UpdateAI(), boss_julianneAI::UpdateAI(), boss_romuloAI::UpdateAI(), npc_echo_of_medivhAI::UpdateAI(), boss_arcanist_doanAI::UpdateAI(), boss_headless_horsemanAI::UpdateAI(), boss_herodAI::UpdateAI(), boss_darkmaster_gandlingAI::UpdateAI(), boss_jandicebarovAI::UpdateAI(), npc_spectral_tutorAI::UpdateAI(), boss_baroness_anastariAI::UpdateAI(), boss_cannon_master_willeyAI::UpdateAI(), boss_dathrohan_balnazzarAI::UpdateAI(), boss_maleki_the_pallidAI::UpdateAI(), mob_restless_soulAI::UpdateAI(), npc_shadow_imageAI::UpdateAI(), boss_archaedasAI::UpdateAI(), go_infernaling_summoner_portal_hound::UpdateAI(), npc_soulflayerAI::UpdateAI(), example_creatureAI::UpdateAI(), go_ai_lightning::UpdateAI(), boss_mawsAI::UpdateAI(), npc_draenei_survivorAI::UpdateAI(), npc_rabid_bearAI::UpdateAI(), npc_restless_apparitionAI::UpdateAI(), mob_invis_firework_helper::UpdateAI(), boss_tethyrAI::UpdateAI(), npc_solenorAI::UpdateAI(), npc_simone_seductressAI::UpdateAI(), npc_simone_the_inconspicuousAI::UpdateAI(), npc_artoriusAI::UpdateAI(), boss_zumrahAI::UpdateAI(), mobs_nether_drakeAI::UpdateAI(), npc_bloodmaul_stout_triggerAI::UpdateAI(), npc_bloodmaul_dire_wolfAI::UpdateAI(), npc_supplicantAI::UpdateAI(), boss_doomlordkazzakAI::UpdateAI(), boss_doomwalkerAI::UpdateAI(), boss_fathomlord_karathressAI::UpdateAI(), boss_fathomguard_caribdisAI::UpdateAI(), npc_inner_demonAI::UpdateAI(), npc_rethhedronAI::UpdateAI(), npc_saeed_escortAI::UpdateAI(), npc_dimensiusAI::UpdateAI(), mob_mature_netherwing_drakeAI::UpdateAI(), npc_shadowlord_deathwailAI::UpdateAI(), npc_spawned_oronok_tornheartAI::UpdateAI(), npc_millhouse_manastormAI::UpdateAI(), npc_arcatraz_defenderAI::UpdateAI(), boss_lajAI::UpdateAI(), boss_warp_splinterAI::UpdateAI(), boss_kaelthasAI::UpdateAI(), boss_thaladred_the_darkenerAI::UpdateAI(), boss_grand_astromancer_capernianAI::UpdateAI(), boss_master_engineer_telonicusAI::UpdateAI(), boss_nethermancer_sepethreaAI::UpdateAI(), npc_raging_flamesAI::UpdateAI(), boss_pathaleon_the_calculatorAI::UpdateAI(), mob_nether_wraithAI::UpdateAI(), go_infernaling_summoner::UpdateAI(), boss_emerald_dragonAI::UpdateAI(), npc_doctorAI::UpdateAI(), boss_emerissAI::UpdateDragonAI(), boss_taerarAI::UpdateDragonAI(), boss_ysondreAI::UpdateDragonAI(), npc_reginald_windsorAI::UpdateEscortAI(), npc_taelan_fordringAI::UpdateEscortAI(), npc_isillienAI::UpdateEscortAI(), npc_tirion_fordringAI::UpdateEscortAI(), npc_captured_sprite_darterAI::UpdateEscortAI(), npc_keeper_remulosAI::UpdateEscortAI(), npc_kineloryAI::UpdateEscortAI(), npc_grimstoneAI::UpdateEscortAI(), npc_rizzle_sprysprocketAI::UpdateEscortAI(), npc_thrall_old_hillsbradAI::UpdateEscortAI(), npc_captured_arkonarinAI::UpdateEscortAI(), npc_areiAI::UpdateEscortAI(), npc_belnistraszAI::UpdateEscortAI(), npc_disciple_of_naralexAI::UpdateEscortAI(), npc_nagrand_captiveAI::UpdateEscortAI(), npc_captured_vanguardAI::UpdateEscortAI(), npc_akunoAI::UpdateEscortAI(), npc_isla_starmaneAI::UpdateEscortAI(), npc_fhwoorAI::UpdateEscortAI(), npc_kindal_moonweaverAI::UpdateFollowerAI(), npc_shay_leafrunnerAI::UpdateFollowerAI(), npc_kerlonianAI::UpdateFollowerAI(), npc_toogaAI::UpdateFollowerAI(), npc_ringoAI::UpdateFollowerAI(), boss_lady_blaumeuxAI::UpdateHorsmenAI(), boss_alexandros_mograineAI::UpdateHorsmenAI(), boss_thane_korthazzAI::UpdateHorsmenAI(), boss_sir_zeliekAI::UpdateHorsmenAI(), CreatureEventAIHolder::UpdateRepeatTimer(), Player::UpdateSkill(), UnitAI::UpdateSpellLists(), AuctionHouseBot::ValueWithVariance(), boss_plugger_spazzringAI::WarnThief(), WindowsCodeScan::WindowsCodeScan(), WindowsDriverScan::WindowsDriverScan(), WindowsHookScan::WindowsHookScan(), and WindowsModuleScan::WindowsModuleScan().
Utf8FitTo()
bool Utf8FitTo (const std::string & str, const std::wstring & search)
Definition at line 523 of file Util.cpp.
References Utf8toWStr(), and wstrToLower().
Referenced by WorldSession::BuildListAuctionItems(), PlayerbotAI::CreatureLocalization(), PlayerbotAI::GameObjectLocalization(), PlayerbotAI::getPetSpellId(), PlayerbotAI::getSpellId(), ChatHandler::HandleLearnAllRecipesCommand(), ChatHandler::HandleLookupAreaCommand(), ChatHandler::HandleLookupCreatureCommand(), ChatHandler::HandleLookupEventCommand(), ChatHandler::HandleLookupFactionCommand(), ChatHandler::HandleLookupItemCommand(), ChatHandler::HandleLookupItemSetCommand(), ChatHandler::HandleLookupObjectCommand(), ChatHandler::HandleLookupQuestCommand(), ChatHandler::HandleLookupSkillCommand(), ChatHandler::HandleLookupSpellCommand(), ChatHandler::HandleLookupTaxiNodeCommand(), ChatHandler::HandleLookupTitleCommand(), WorldSession::HandleWhoOpcode(), PlayerbotAI::ItemLocalization(), and PlayerbotAI::QuestLocalization().
utf8length()
size_t utf8length (std::string & utf8str)
Definition at line 366 of file Util.cpp.
Referenced by AccountMgr::ChangePassword(), AccountMgr::ChangeUsername(), and AccountMgr::CreateAccount().
utf8limit()
size_t utf8limit (std::string & utf8str, size_t bytes)
Definition at line 380 of file Util.cpp.
Referenced by WorldSession::CheckChatChannelNameAndPassword(), WorldSession::CheckChatMessage(), GMTicket::GMTicket(), PlayerbotAI::HandleCommand(), WorldSession::HandleGMSurveySubmitOpcode(), GMTicket::Load(), GMTicket::Recycle(), and GMTicket::SetUpdated().
utf8printf()
void utf8printf (FILE * out, const char * str, ...)
Definition at line 536 of file Util.cpp.
References vutf8printf().
utf8ToConsole()
bool utf8ToConsole (const std::string & utf8str, std::string & conStr)
Definition at line 491 of file Util.cpp.
References Utf8toWStr().
Utf8toWStr()
bool Utf8toWStr (const std::string & utf8str, std::wstring & wstr, size_t max_len = 0)
Definition at line 329 of file Util.cpp.
Referenced by AuctionHouseObject::AddAuction(), ObjectMgr::AddGameTele(), ObjectMgr::CheckDeclinedNames(), ObjectMgr::CheckPetName(), ObjectMgr::CheckPlayerName(), ObjectMgr::CheckPublicMessageLanguage(), AuctionEntry::CompareAuctionEntry(), ObjectMgr::DeleteGameTele(), ChannelMgr::GetChannel(), GetChatChannelsEntryFor(), ObjectMgr::GetGameTele(), ChannelMgr::GetJoinChannel(), PlayerbotAI::getPetSpellId(), PlayerbotAI::getSpellId(), WorldSession::HandleAuctionListItems(), ChatHandler::HandleLearnAllRecipesCommand(), ChatHandler::HandleLookupAreaCommand(), ChatHandler::HandleLookupCreatureCommand(), ChatHandler::HandleLookupEventCommand(), ChatHandler::HandleLookupFactionCommand(), ChatHandler::HandleLookupItemCommand(), ChatHandler::HandleLookupItemSetCommand(), ChatHandler::HandleLookupObjectCommand(), ChatHandler::HandleLookupQuestCommand(), ChatHandler::HandleLookupSkillCommand(), ChatHandler::HandleLookupSpellCommand(), ChatHandler::HandleLookupTaxiNodeCommand(), ChatHandler::HandleLookupTeleCommand(), ChatHandler::HandleLookupTitleCommand(), ChatHandler::HandleModifyRepCommand(), WorldSession::HandlePetRename(), WorldSession::HandleSetPlayerDeclinedNamesOpcode(), WorldSession::HandleWhoOpcode(), ObjectMgr::IsReservedName(), ObjectMgr::IsValidCharterName(), ChannelMgr::LeftChannel(), AuctionHouseMgr::LoadAuctions(), ObjectMgr::LoadGameTele(), ObjectMgr::LoadReservedPlayersNames(), normalizePlayerName(), AccountMgr::normalizeString(), NamreebAnticheat::AntispamMgr::NormalizeStringInternal(), Utf8FitTo(), utf8print(), utf8ToConsole(), utf8truncate(), and vutf8printf().
utf8truncate()
void utf8truncate (std::string & utf8str, size_t len)
Definition at line 407 of file Util.cpp.
References Utf8toWStr(), and WStrToUtf8().
Referenced by PlayerSocial::SetFriendNote(), and Guild::SetGuildBankTabText().
vutf8printf()
void vutf8printf (FILE * out, const char * str, va_list * ap)
Definition at line 544 of file Util.cpp.
References Utf8toWStr().
Referenced by Log::outBasic(), Log::outCommand(), Log::outDebug(), Log::outDetail(), Log::outError(), Log::outErrorDb(), Log::outErrorEventAI(), Log::outErrorScriptLib(), Log::outString(), and utf8printf().
wcharToLower()
wchar_t wcharToLower (wchar_t wchar) inline
Definition at line 349 of file Util.h.
Referenced by normalizePlayerName(), and wstrToLower().
wcharToUpper()
wchar_t wcharToUpper (wchar_t wchar) inline
Definition at line 321 of file Util.h.
Referenced by normalizePlayerName(), wcharToUpperOnlyLatin(), and wstrToUpper().
wcharToUpperOnlyLatin()
wchar_t wcharToUpperOnlyLatin (wchar_t wchar) inline
Definition at line 344 of file Util.h.
References isBasicLatinCharacter(), and wcharToUpper().
Referenced by AccountMgr::normalizeString().
wstrToLower()
void wstrToLower (std::wstring & str) inline
Definition at line 377 of file Util.h.
References wcharToLower().
Referenced by ObjectMgr::AddGameTele(), ObjectMgr::DeleteGameTele(), ChannelMgr::GetChannel(), ObjectMgr::GetGameTele(), ChannelMgr::GetJoinChannel(), PlayerbotAI::getPetSpellId(), PlayerbotAI::getSpellId(), WorldSession::HandleAuctionListItems(), ChatHandler::HandleLearnAllRecipesCommand(), ChatHandler::HandleLookupAreaCommand(), ChatHandler::HandleLookupCreatureCommand(), ChatHandler::HandleLookupEventCommand(), ChatHandler::HandleLookupFactionCommand(), ChatHandler::HandleLookupItemCommand(), ChatHandler::HandleLookupItemSetCommand(), ChatHandler::HandleLookupObjectCommand(), ChatHandler::HandleLookupQuestCommand(), ChatHandler::HandleLookupSkillCommand(), ChatHandler::HandleLookupSpellCommand(), ChatHandler::HandleLookupTaxiNodeCommand(), ChatHandler::HandleLookupTeleCommand(), ChatHandler::HandleLookupTitleCommand(), ChatHandler::HandleModifyRepCommand(), WorldSession::HandleWhoOpcode(), ObjectMgr::IsReservedName(), ChannelMgr::LeftChannel(), ObjectMgr::LoadGameTele(), ObjectMgr::LoadReservedPlayersNames(), and Utf8FitTo().
wstrToUpper()
void wstrToUpper (std::wstring & str) inline
Definition at line 372 of file Util.h.
References wcharToUpper().
Referenced by NamreebAnticheat::AntispamMgr::NormalizeStringInternal().
WStrToUtf8()
bool WStrToUtf8 (const std::wstring & wstr, std::string & utf8str)
Definition at line 421 of file Util.cpp.
Referenced by consoleToUtf8(), normalizePlayerName(), AccountMgr::normalizeString(), and utf8truncate().