CMaNGOS_TBC: Warlock.cpp File Reference
Warlock.cpp File Reference
#include "Spells/Scripts/SpellScript.h"
#include "Spells/SpellAuras.h"
#include "Spells/SpellMgr.h"
Data Structures
struct UnstableAffliction
struct CurseOfAgony
struct LifeTap
struct DemonicKnowledge
struct SoulLink
struct SiphonLife
struct Corruption
struct EyeOfKilrogg
struct CurseOfDoom
struct CurseOfDoomEffect
struct DevourMagic
struct SeedOfCorruption
struct SeedOfCorruptionDamage
struct SoulLeech
struct CurseDiminishingDuration
Enumerations
enum { SPELL_UNSTABLE_AFFLICTION_SILENCE = 31117 }
enum { SPELL_SEED_DAMAGE = 27285 }
Functions
void RemoveShadowEmbraceIfNecessary (Aura *aura)
void LoadWarlockScripts ()
Variables
static uint32 const shadowEmbraceSpellList [5] = { 32386,32388,32389,32390,32391 }
static uint32 const causesShadowEmbraceSpellList [23] = { 172,6222,6223,7648,11671,11672,25311,27216,18265,18879,18880,18881,27264,30911,27243,980,1014,6217,11711,11712,11713,27218 }
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SPELL_UNSTABLE_AFFLICTION_SILENCE
Definition at line 23 of file Warlock.cpp.
anonymous enum
anonymous enum
Enumerator
SPELL_SEED_DAMAGE
Definition at line 255 of file Warlock.cpp.
Function Documentation
LoadWarlockScripts()
void LoadWarlockScripts ()
Definition at line 334 of file Warlock.cpp.
Referenced by SpellScriptMgr::LoadScripts().
RemoveShadowEmbraceIfNecessary()
void RemoveShadowEmbraceIfNecessary (Aura * aura)
Definition at line 31 of file Warlock.cpp.
References causesShadowEmbraceSpellList, Unit::GetAurasByType(), Aura::GetCasterGuid(), Aura::GetTarget(), Unit::RemoveAurasDueToSpell(), shadowEmbraceSpellList, SPELL_AURA_MOD_DAMAGE_PERCENT_DONE, and SPELL_AURA_PERIODIC_DAMAGE.
Referenced by CurseOfAgony::OnApply(), SiphonLife::OnApply(), Corruption::OnApply(), and SeedOfCorruption::OnApply().
Variable Documentation
causesShadowEmbraceSpellList
uint32 const causesShadowEmbraceSpellList[23] = { 172,6222,6223,7648,11671,11672,25311,27216,18265,18879,18880,18881,27264,30911,27243,980,1014,6217,11711,11712,11713,27218 } static
Definition at line 29 of file Warlock.cpp.
Referenced by RemoveShadowEmbraceIfNecessary().
shadowEmbraceSpellList
uint32 const shadowEmbraceSpellList[5] = { 32386,32388,32389,32390,32391 } static
Definition at line 28 of file Warlock.cpp.
Referenced by RemoveShadowEmbraceIfNecessary().