CMaNGOS_TBC: world_map_scripts.cpp File Reference
world_map_scripts.cpp File Reference
#include "AI/ScriptDevAI/include/sc_common.h"
#include "world_map_scripts.h"
#include "World/WorldState.h"
#include "World/WorldStateDefines.h"
#include "Entities/TemporarySpawn.h"
#include "GameEvents/GameEventMgr.h"
#include <array>
#include <ctime>
#include <cstring>
#include "AI/ScriptDevAI/scripts/world/scourge_invasion.h"
#include "World/World.h"
#include "brewfest.h"
Enumerations
enum {
EVENT_UC_FROM_GROMGOL_ARRIVAL = 15312 , EVENT_GROMGOL_FROM_UC_ARRIVAL = 15314 , EVENT_OG_FROM_UC_ARRIVAL = 15318 , EVENT_UC_FROM_OG_ARRIVAL = 15320 ,
EVENT_OG_FROM_GROMGOL_ARRIVAL = 15322 , EVENT_GROMGOL_FROM_OG_ARRIVAL = 15324 , SOUND_ZEPPELIN_HORN = 11804
}
Functions
bool ProcessEventTransports (uint32 uiEventId, Object *pSource, Object *, bool)
void AddSC_world_map_scripts ()
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EVENT_UC_FROM_GROMGOL_ARRIVAL
EVENT_GROMGOL_FROM_UC_ARRIVAL
EVENT_OG_FROM_UC_ARRIVAL
EVENT_UC_FROM_OG_ARRIVAL
EVENT_OG_FROM_GROMGOL_ARRIVAL
EVENT_GROMGOL_FROM_OG_ARRIVAL
SOUND_ZEPPELIN_HORN
Definition at line 37 of file world_map_scripts.cpp.
Function Documentation
AddSC_world_map_scripts()
void AddSC_world_map_scripts ()
Definition at line 211 of file world_map_scripts.cpp.
References Script::Name, Script::pProcessEventId, ProcessEventTransports(), and Script::RegisterSelf().
Referenced by AddScripts().
ProcessEventTransports()
bool ProcessEventTransports (uint32 uiEventId, Object * pSource, Object * , bool)
Definition at line 49 of file world_map_scripts.cpp.
References EVENT_GROMGOL_FROM_OG_ARRIVAL, EVENT_GROMGOL_FROM_UC_ARRIVAL, EVENT_OG_FROM_GROMGOL_ARRIVAL, EVENT_OG_FROM_UC_ARRIVAL, EVENT_UC_FROM_GROMGOL_ARRIVAL, EVENT_UC_FROM_OG_ARRIVAL, Object::GetEntry(), Map::GetInstanceData(), WorldObject::GetMap(), ScriptedInstance::GetSingleCreatureFromStorage(), NPC_FREZZA, NPC_HINDENBURG, NPC_NEZRAZ, NPC_SNURK_BUCKSQUICK, NPC_SQUIBBY_OVERSPECK, NPC_ZAPETTA, SOUND_ZEPPELIN_HORN, and sWorldState.
Referenced by AddSC_world_map_scripts().